//! Shard manifest CRUD operations using Diesel.
//!
//! Shard manifests track the encoding state for each content item —
//! what erasure coding strategy was used, the resulting shard hashes,
//! and sizes. This is per-peer local state (Category C), not DHT-notarized.

use diesel::prelude::*;

use super::diesel_schema::shard_manifests;
use super::models::{NewShardManifest, ShardManifestRow};
use crate::blob_store::BlobStore;
use crate::sharding::ShardManifest;
use crate::StorageError;

/// Persist a manifest that was already generated by a byte-handling path.
///
/// Callers retain their honest scope: distribution supplies the application
/// content id it is placing, while bare blob ingress supplies the blob's
/// canonical raw CID (prefixed as a local projection key). This keeps the
/// shard-to-blob relation available to the custody-facing fold without
/// asserting a new DHT fact or fabricating an application content record.
pub fn record_generated_manifest(
    conn: &mut SqliteConnection,
    content_id: &str,
    h_app_id: &str,
    manifest: &ShardManifest,
) -> Result<ShardManifestRow, StorageError> {
    let shard_hashes_json = serde_json::to_string(&manifest.shard_hashes)?;
    let new_manifest = NewShardManifest {
        content_id,
        h_app_id,
        blob_hash: &manifest.blob_hash,
        blob_cid: Some(&manifest.blob_cid),
        encoding: &manifest.encoding,
        data_shard_count: manifest.data_shards as i32,
        parity_shard_count: (manifest.total_shards - manifest.data_shards) as i32,
        shard_hashes_json: &shard_hashes_json,
        total_size_bytes: manifest.total_size as i64,
        shard_size_bytes: manifest.shard_size as i64,
        mime_type: &manifest.mime_type,
        reach: &manifest.reach,
    };

    upsert_manifest(conn, &new_manifest)
}

/// Encode `data` into a shard manifest and upsert it for `(content_id, h_app_id)`.
///
/// Single source of truth for "blob bytes → persisted shard manifest". Both the
/// `POST /db/content` create path (`http.rs`) and the startup backfill
/// (`services::shard_manifest_backfill`) converge here so the encoding +
/// persistence shape never drifts between them.
///
/// `blob_cid` is the optional content-addressed CID captured on the content row;
/// `content_format` becomes the manifest mime_type; `reach` is recorded verbatim.
#[allow(clippy::too_many_arguments)]
pub fn record_manifest_from_bytes(
    conn: &mut SqliteConnection,
    content_id: &str,
    h_app_id: &str,
    blob_hash: &str,
    blob_cid: Option<&str>,
    data: &[u8],
    content_format: &str,
    reach: &str,
) -> Result<ShardManifestRow, StorageError> {
    let encoder = crate::sharding::ShardEncoder::new(crate::sharding::ShardConfig::default());
    let manifest = encoder
        .create_manifest(data, content_format, reach)
        .map_err(StorageError::from)?;

    let shard_hashes_json = serde_json::to_string(&manifest.shard_hashes)?;

    let new_manifest = NewShardManifest {
        content_id,
        h_app_id,
        blob_hash,
        blob_cid,
        encoding: &manifest.encoding,
        data_shard_count: manifest.data_shards as i32,
        parity_shard_count: (manifest.total_shards - manifest.data_shards) as i32,
        shard_hashes_json: &shard_hashes_json,
        total_size_bytes: manifest.total_size as i64,
        shard_size_bytes: manifest.shard_size as i64,
        mime_type: &manifest.mime_type,
        reach,
    };

    upsert_manifest(conn, &new_manifest)
}

/// Shape-aware entry point every manifest PRODUCER (`POST /db/content`,
/// `/db/content/bulk`, `services::shard_manifest_backfill`) should call instead
/// of the bare `blob_store.get(blob_hash)` → `record_manifest_from_bytes` pair.
///
/// `put_blob_bytes` (`PUT /blob/{hash}`, proxied at `PUT /admin/seed/blob`)
/// already shard-encodes and persists a manifest for EVERY blob it stores —
/// but a `"chunked"`/`"rs-*"` blob (> `sharding::SINGLE_SHARD_MAX`, ~16MB)
/// never stores its composite under the blob's own hash, only its shards
/// under their own hashes. So a bare `blob_store.get(blob_hash)` NotFounds for
/// that shape even though the manifest — and every shard byte it names — is
/// already sitting on disk. [`resolve_manifest_by_hash`] finds that existing
/// manifest (any `(content_id, h_app_id)` row keyed to the same `blob_hash`
/// names the same shard set, content-addressed) and this function reuses it
/// for the NEW `(content_id, h_app_id)` projection at chunk-list cost — no
/// bytes read, no reassembly of a multi-megabyte bundle.
///
/// Falls back to reading the composite and deriving a fresh manifest via
/// [`record_manifest_from_bytes`] only when no manifest is known yet for this
/// hash (a genuinely new, `"none"`-encoded blob whose composite IS stored
/// under its own name).
#[allow(clippy::too_many_arguments)]
pub async fn record_manifest_for_blob(
    conn: &mut SqliteConnection,
    blob_store: &BlobStore,
    content_id: &str,
    h_app_id: &str,
    blob_hash: &str,
    blob_cid: Option<&str>,
    content_format: &str,
    reach: &str,
) -> Result<ShardManifestRow, StorageError> {
    if let Some(existing) = resolve_manifest_by_hash(conn, blob_hash) {
        return record_generated_manifest(conn, content_id, h_app_id, &existing);
    }

    let data = blob_store.get(blob_hash).await?;

    record_manifest_from_bytes(
        conn,
        content_id,
        h_app_id,
        blob_hash,
        blob_cid,
        &data,
        content_format,
        reach,
    )
}

/// Shape-aware blob byte read for producers that need the ACTUAL bytes, not
/// just a manifest — e.g. `p2p::distribute_shards`, which pushes real shard
/// payloads to peers over the wire.
///
/// Tries the composite first (the common, cheap case: a `"none"`-encoded blob
/// ≤ `sharding::SINGLE_SHARD_MAX` is stored whole under its own hash). Falls
/// back to reassembling from an EXISTING manifest's already-stored shards —
/// the shape a `"chunked"`/`"rs-*"` blob actually takes, where the composite
/// is never written under its own address. Reads only the shard bytes a known
/// manifest names; never invents shard hashes and never reassembles when no
/// manifest is known (that case has nothing to reassemble FROM, so it is a
/// plain `NotFound`).
pub async fn read_blob_bytes_for_manifest(
    conn: &mut SqliteConnection,
    blob_store: &BlobStore,
    hash: &str,
) -> Result<Vec<u8>, StorageError> {
    if let Ok(bytes) = blob_store.get(hash).await {
        return Ok(bytes);
    }

    let manifest = resolve_manifest_by_hash(conn, hash)
        .ok_or_else(|| StorageError::NotFound(hash.to_string()))?;

    let encoder = crate::sharding::ShardEncoder::new(crate::sharding::ShardConfig::default());
    let mut shards = Vec::with_capacity(manifest.shard_hashes.len());
    for shard_hash in &manifest.shard_hashes {
        let shard = blob_store.get(shard_hash).await.map_err(|e| {
            StorageError::Internal(format!(
                "shard {shard_hash} missing while reassembling {hash} from its manifest: {e}"
            ))
        })?;
        shards.push(Some(shard));
    }

    encoder
        .reconstruct(&manifest, &shards)
        .map_err(StorageError::from)
}

pub fn upsert_manifest(
    conn: &mut SqliteConnection,
    manifest: &NewShardManifest,
) -> Result<ShardManifestRow, StorageError> {
    // Q11 atomic timing budget: the durable write + read-back, the whole
    // "manifest persist" atom every generation/receipt path shares.
    let manifest_persist_started = std::time::Instant::now();
    let result: Result<ShardManifestRow, StorageError> = (|| {
        diesel::replace_into(shard_manifests::table)
            .values(manifest)
            .execute(conn)?;

        shard_manifests::table
            .filter(shard_manifests::content_id.eq(manifest.content_id))
            .filter(shard_manifests::h_app_id.eq(manifest.h_app_id))
            .first(conn)
            .map_err(StorageError::from)
    })();
    crate::metrics::observe_atom_duration(
        crate::metrics::ConvergenceAtom::ManifestPersist,
        manifest_persist_started.elapsed(),
    );
    result
}

pub fn get_manifest(
    conn: &mut SqliteConnection,
    h_app_id: &str,
    content_id: &str,
) -> Result<Option<ShardManifestRow>, StorageError> {
    shard_manifests::table
        .filter(shard_manifests::content_id.eq(content_id))
        .filter(shard_manifests::h_app_id.eq(h_app_id))
        .first(conn)
        .optional()
        .map_err(StorageError::from)
}

/// Resolve the durable manifest projection for a blob's canonical hash.
///
/// The serving path only ever holds a `sha256-{hex}` address, while rows are
/// keyed by `(content_id, h_app_id)` — ingest files them under a
/// `blob:{blob_cid}` projection id, distribution under the application content
/// id. Both carry the same `blob_hash`, and the encoding is deterministic from
/// the bytes, so any row for the hash names the same shard set. `created_at`
/// ordering makes the pick stable rather than storage-order dependent.
pub fn get_manifest_by_blob_hash(
    conn: &mut SqliteConnection,
    blob_hash: &str,
) -> Result<Option<ShardManifestRow>, StorageError> {
    shard_manifests::table
        .filter(shard_manifests::blob_hash.eq(blob_hash))
        .order(shard_manifests::created_at.desc())
        .first(conn)
        .optional()
        .map_err(StorageError::from)
}

/// Rehydrate the in-memory [`ShardManifest`] from its durable row.
///
/// `author_id` / `verified_at` are not columns on the projection, so they come
/// back `None` — neither participates in reassembly.
pub fn hydrate_manifest(row: &ShardManifestRow) -> Result<ShardManifest, StorageError> {
    let shard_hashes: Vec<String> = serde_json::from_str(&row.shard_hashes_json)?;

    Ok(ShardManifest {
        blob_cid: row.blob_cid.clone().unwrap_or_default(),
        blob_hash: row.blob_hash.clone(),
        total_size: row.total_size_bytes.max(0) as u64,
        mime_type: row.mime_type.clone(),
        encoding: row.encoding.clone(),
        data_shards: row.data_shard_count.max(0) as u8,
        total_shards: (row.data_shard_count.max(0) + row.parity_shard_count.max(0)) as u8,
        shard_size: row.shard_size_bytes.max(0) as u64,
        shard_hashes,
        reach: row.reach.clone(),
        author_id: None,
        created_at: row.created_at.clone(),
        verified_at: None,
    })
}

/// Resolve + hydrate a shard manifest for a blob hash directly from the
/// durable projection — no in-process cache. Q2's `HttpServer::resolve_manifest`
/// checks its own `manifests` map first and falls back to
/// `get_manifest_by_blob_hash` + `hydrate_manifest` here; this function IS
/// that fallback, exposed standalone so callers with no `HttpServer` (the P2P
/// blob-fetch responder, `src/p2p/mod.rs`, which runs in a separate actor with
/// no access to `HttpServer`'s cache) get the same durable answer without
/// duplicating the lookup-then-hydrate glue. Errors are logged and folded to
/// `None` — a manifest miss is a normal "I don't have this" outcome, not a
/// caller-visible failure.
pub fn resolve_manifest_by_hash(conn: &mut SqliteConnection, hash: &str) -> Option<ShardManifest> {
    let row = get_manifest_by_blob_hash(conn, hash)
        .map_err(|e| tracing::warn!(hash = %hash, error = %e, "shard manifest lookup failed"))
        .ok()
        .flatten()?;
    hydrate_manifest(&row)
        .map_err(|e| tracing::warn!(hash = %hash, error = %e, "shard manifest hydration failed"))
        .ok()
}

pub fn list_manifests_by_encoding(
    conn: &mut SqliteConnection,
    h_app_id: &str,
    encoding: &str,
) -> Result<Vec<ShardManifestRow>, StorageError> {
    shard_manifests::table
        .filter(shard_manifests::h_app_id.eq(h_app_id))
        .filter(shard_manifests::encoding.eq(encoding))
        .load(conn)
        .map_err(StorageError::from)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_util::test_pool;

    fn fixture_manifest(blob_hash: &str) -> ShardManifest {
        ShardManifest {
            blob_cid: format!("bafkrei-{blob_hash}"),
            blob_hash: blob_hash.to_string(),
            total_size: 2_000_000,
            mime_type: "application/octet-stream".to_string(),
            encoding: "chunked".to_string(),
            data_shards: 2,
            total_shards: 2,
            shard_size: 1_000_000,
            shard_hashes: vec!["sha256-shardA".to_string(), "sha256-shardB".to_string()],
            reach: "commons".to_string(),
            author_id: None,
            created_at: "2026-08-16T00:00:00Z".to_string(),
            verified_at: None,
        }
    }

    /// `resolve_manifest_by_hash` — Q3's shared, `HttpServer`-free lookup —
    /// must find a manifest persisted under ANY `(content_id, h_app_id)` key,
    /// since rows are addressed by `blob_hash` here, not by the caller's own
    /// projection id (mirrors `get_manifest_by_blob_hash`'s doc comment).
    #[test]
    fn resolve_manifest_by_hash_finds_persisted_manifest() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        let manifest = fixture_manifest("sha256-composite-a");
        record_generated_manifest(&mut conn, "blob:composite-a", "lamad", &manifest)
            .expect("persist manifest");

        let resolved = resolve_manifest_by_hash(&mut conn, "sha256-composite-a")
            .expect("manifest must resolve from the durable projection");
        assert_eq!(resolved.blob_hash, manifest.blob_hash);
        assert_eq!(resolved.shard_hashes, manifest.shard_hashes);
        assert_eq!(resolved.encoding, "chunked");
    }

    /// A hash with no persisted manifest resolves to `None`, not an error —
    /// this is the normal "I don't have this" answer the P2P responder relies
    /// on to fall through to a plain `NotFound` reply.
    #[test]
    fn resolve_manifest_by_hash_returns_none_when_absent() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        assert!(resolve_manifest_by_hash(&mut conn, "sha256-never-persisted").is_none());
    }

    /// Seeds a `"chunked"`-encoded blob exactly the shape `put_blob_bytes`
    /// leaves for anything above `sharding::SINGLE_SHARD_MAX`: each shard
    /// stored under its OWN hash, no composite ever written under the
    /// blob_hash. Returns the manifest (real, content-addressed shard hashes
    /// — never invented) and the full composite bytes for assertions.
    async fn seed_chunk_stored_blob(blob_store: &BlobStore) -> (ShardManifest, Vec<u8>) {
        let shard_a = blob_store
            .store(b"first shard payload-")
            .await
            .expect("store shard a");
        let shard_b = blob_store
            .store(b"second shard payload")
            .await
            .expect("store shard b");

        let mut composite = Vec::new();
        composite.extend_from_slice(b"first shard payload-");
        composite.extend_from_slice(b"second shard payload");
        let composite_hash = BlobStore::compute_hash(&composite);

        let manifest = ShardManifest {
            blob_cid: format!("bafkrei-{composite_hash}"),
            blob_hash: composite_hash,
            total_size: composite.len() as u64,
            mime_type: "html5-app".to_string(),
            encoding: "chunked".to_string(),
            data_shards: 2,
            total_shards: 2,
            shard_size: shard_a.size_bytes,
            shard_hashes: vec![shard_a.hash.clone(), shard_b.hash.clone()],
            reach: "commons".to_string(),
            author_id: None,
            created_at: "2026-08-21T00:00:00Z".to_string(),
            verified_at: None,
        };

        (manifest, composite)
    }

    /// The core defect this closes: a `"chunked"` blob (no composite under its
    /// own hash — landing-bundle shape) already has a manifest from ingest
    /// (`put_blob_bytes`, filed under a `blob:{cid}` projection id). A LATER
    /// producer for a DIFFERENT `(content_id, h_app_id)` — the `POST
    /// /db/content` create path, standing in for `elohim-host-landing` — must
    /// reuse that manifest's REAL shard hashes rather than NotFound-ing on a
    /// bare composite read.
    #[tokio::test]
    async fn record_manifest_for_blob_reuses_existing_manifest_for_chunk_stored_blob() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        let blob_store = BlobStore::new_memory();

        let (manifest, _composite) = seed_chunk_stored_blob(&blob_store).await;
        record_generated_manifest(
            &mut conn,
            &format!("blob:{}", manifest.blob_cid),
            "lamad",
            &manifest,
        )
        .expect("seed ingest-time manifest projection");

        // Confirms the shape under test: the composite is genuinely absent, so
        // a passing assertion below cannot be a silent fallback to a
        // successful composite read.
        assert!(
            blob_store.get(&manifest.blob_hash).await.is_err(),
            "a chunked blob's composite must never be stored under its own hash"
        );

        let row = record_manifest_for_blob(
            &mut conn,
            &blob_store,
            "elohim-host-landing",
            "lamad",
            &manifest.blob_hash,
            Some(&manifest.blob_cid),
            "html5-app",
            "commons",
        )
        .await
        .expect("manifest must be produced from the already-known shard set");

        assert_eq!(row.content_id, "elohim-host-landing");
        assert_eq!(row.encoding, "chunked");
        assert_eq!(row.blob_hash, manifest.blob_hash);
        let shard_hashes: Vec<String> =
            serde_json::from_str(&row.shard_hashes_json).expect("decode shard hashes");
        assert_eq!(
            shard_hashes, manifest.shard_hashes,
            "shard hashes must be the REAL, already-stored chunk hashes — never re-derived or invented"
        );
    }

    /// Composite blob (`"none"` encoding, ≤ `SINGLE_SHARD_MAX`) with no
    /// pre-existing manifest: unchanged behaviour — derive fresh from bytes.
    #[tokio::test]
    async fn record_manifest_for_blob_derives_from_bytes_when_no_manifest_known() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        let blob_store = BlobStore::new_memory();

        let stored = blob_store
            .store(b"<html>small composite blob</html>")
            .await
            .expect("store composite blob");

        let row = record_manifest_for_blob(
            &mut conn,
            &blob_store,
            "small-doc",
            "lamad",
            &stored.hash,
            None,
            "html5-app",
            "commons",
        )
        .await
        .expect("manifest derived from composite bytes");

        assert_eq!(row.encoding, "none");
        let shard_hashes: Vec<String> =
            serde_json::from_str(&row.shard_hashes_json).expect("decode shard hashes");
        assert_eq!(shard_hashes, vec![stored.hash.clone()]);
    }

    /// `read_blob_bytes_for_manifest` — the bytes-needing sibling
    /// (`p2p::distribute_shards`) — must reassemble the composite from a known
    /// manifest's already-stored shards when the composite itself is absent.
    #[tokio::test]
    async fn read_blob_bytes_for_manifest_reassembles_from_shards_when_composite_absent() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        let blob_store = BlobStore::new_memory();

        let (manifest, composite) = seed_chunk_stored_blob(&blob_store).await;
        record_generated_manifest(
            &mut conn,
            &format!("blob:{}", manifest.blob_cid),
            "lamad",
            &manifest,
        )
        .expect("seed manifest");

        let bytes = read_blob_bytes_for_manifest(&mut conn, &blob_store, &manifest.blob_hash)
            .await
            .expect("bytes reassembled from the manifest's shards");

        assert_eq!(
            bytes, composite,
            "reassembled bytes must equal the original composite"
        );
    }

    /// No composite AND no manifest known: honestly `NotFound`, never a panic
    /// or an invented reassembly.
    #[tokio::test]
    async fn read_blob_bytes_for_manifest_errors_when_truly_absent() {
        let pool = test_pool();
        let mut conn = pool.get().expect("conn");
        let blob_store = BlobStore::new_memory();

        let result =
            read_blob_bytes_for_manifest(&mut conn, &blob_store, "sha256-never-seen").await;
        assert!(matches!(result, Err(StorageError::NotFound(_))));
    }
}
