apiVersion: v1
kind: ConfigMap
metadata:
  name: elohim-config-prod
  namespace: elohim-prod
  labels:
    app.kubernetes.io/name: elohim-site
    app.kubernetes.io/instance: elohim-site-prod
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: elohim
    app.kubernetes.io/managed-by: jenkins
data:
  config.json: |
    {
      "logLevel": "info",
      "environment": "prod",
      "doorwayUrl": "https://doorway.elohim.host"
    }
