//! Chaperone: Server-side admin protocol for Holochain connection setup.
//!
//! Replaces the browser's 11-step admin WebSocket dance with a single
//! `POST /hc/connect` call. The browser generates signing keys locally,
//! sends the public key + cap secret, and doorway handles all admin
//! operations (cap grants, credential authorization, token issuance)
//! on the correct conductor.
//!
//! This eliminates:
//! - Two-WebSocket routing problem (admin + app must hit same conductor)
//! - Session affinity cache
//! - Admin protocol exposure in production
//! - Key format matching between browser and conductor

use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use bytes::Bytes;
use http_body_util::{BodyExt, Full};
use hyper::{Request, Response, StatusCode};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tracing::{debug, error, info, warn};

use crate::auth::{extract_token_from_header, JwtValidator, TokenInput};
use crate::conductor::typed_admin::TypedAdminClient;
use crate::conductor::AgentProvisioner;
use crate::server::http::AppState;

/// Request body for `POST /hc/connect`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectRequest {
    /// Base64 Ed25519 public signing key (generated by browser)
    pub signing_key: String,
    /// Base64 capability secret (generated by browser)
    pub cap_secret: String,
}

/// Response body for `POST /hc/connect`.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectResponse {
    /// Base64 Holochain app auth token for AppWebsocket
    pub app_token: String,
    /// App WebSocket port
    pub app_port: u16,
    /// Base64 agent public key
    pub agent_pub_key: String,
    /// Installed app ID
    pub installed_app_id: String,
    /// Conductor ID (also embedded in refreshed JWT)
    pub conductor_id: String,
    /// Cell IDs: { role_name: [dna_hash_b64, agent_key_b64] }
    pub cell_ids: HashMap<String, [String; 2]>,
    /// Refreshed JWT with conductor_id embedded
    pub token: String,
}

/// Handle `POST /hc/connect` — the Chaperone endpoint.
///
/// Orchestration flow:
/// 1. Extract JWT from Authorization header
/// 2. Resolve conductor (from claims.conductor_id, registry, or auto-provision)
/// 3. Get app info (cell IDs per role)
/// 4. Grant capabilities per cell (with source chain retry)
/// 5. Authorize signing credentials per cell (with retry)
/// 6. Get app interface port
/// 7. Issue app authentication token
/// 8. Re-issue JWT with conductor_id if not already present
/// 9. Return ConnectResponse
pub async fn handle_hc_connect(
    req: Request<hyper::body::Incoming>,
    state: Arc<AppState>,
) -> Response<Full<Bytes>> {
    // --- Step 1: Extract and validate JWT ---
    let auth_header = req
        .headers()
        .get(hyper::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());

    let token_str = match extract_token_from_header(auth_header) {
        Some(t) => t.to_string(),
        None => {
            return json_error(StatusCode::UNAUTHORIZED, "Missing Authorization header");
        }
    };

    let jwt = if state.args.dev_mode {
        JwtValidator::new_dev()
    } else {
        match state.args.jwt_secret.as_ref() {
            Some(secret) => {
                match JwtValidator::new(secret.clone(), state.args.jwt_expiry_seconds) {
                    Ok(v) => v,
                    Err(_) => {
                        return json_error(StatusCode::INTERNAL_SERVER_ERROR, "JWT not configured")
                    }
                }
            }
            None => return json_error(StatusCode::INTERNAL_SERVER_ERROR, "JWT not configured"),
        }
    };

    let validation = jwt.verify_token(&token_str);
    let claims = match validation.claims {
        Some(c) if validation.valid => c,
        _ => return json_error(StatusCode::UNAUTHORIZED, "Invalid or expired token"),
    };

    // --- Read request body ---
    let body_bytes = match req.collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(e) => {
            warn!("Failed to read /hc/connect body: {}", e);
            return json_error(StatusCode::BAD_REQUEST, "Failed to read request body");
        }
    };

    let body: ConnectRequest = match serde_json::from_slice(&body_bytes) {
        Ok(b) => b,
        Err(e) => {
            return json_error(StatusCode::BAD_REQUEST, &format!("Invalid JSON: {e}"));
        }
    };

    // Decode base64 inputs
    let signing_key = match BASE64.decode(&body.signing_key) {
        Ok(k) => k,
        Err(_) => return json_error(StatusCode::BAD_REQUEST, "Invalid base64 signing_key"),
    };
    let cap_secret = match BASE64.decode(&body.cap_secret) {
        Ok(s) => s,
        Err(_) => return json_error(StatusCode::BAD_REQUEST, "Invalid base64 cap_secret"),
    };

    // --- Step 2: Resolve conductor ---
    let registry = match &state.conductor_registry {
        Some(r) => Arc::clone(r),
        None => {
            return json_error(
                StatusCode::SERVICE_UNAVAILABLE,
                "No conductor registry available",
            );
        }
    };

    // Try conductor_id from JWT claims first
    let (conductor_id, admin_url, installed_app_id) = if let Some(ref cid) = claims.conductor_id {
        if let Some(info) = registry.get_conductor_info(cid) {
            let app_id = claims
                .installed_app_id
                .clone()
                .unwrap_or_else(|| state.args.installed_app_id.clone());
            (cid.clone(), info.admin_url, app_id)
        } else {
            // Unknown conductor_id. If the claim was minted by a sibling
            // doorway, this is the expected shape of "hosted elsewhere" —
            // return the honest 409, not the misleading "not found in
            // registry" 502 (see `unknown_conductor_response`).
            return unknown_conductor_response(&claims, state.args.doorway_id.as_deref(), cid);
        }
    } else if let Some(entry) = registry.get_conductor_for_agent(&claims.agent_pub_key) {
        // Agent already registered in conductor registry
        if let Some(info) = registry.get_conductor_info(&entry.conductor_id) {
            (entry.conductor_id, info.admin_url, entry.app_id)
        } else {
            // Stale registry entry — the conductor_id stored in MongoDB no
            // longer exists in the current in-memory conductor pool (e.g.,
            // CONDUCTOR_URLS reordered, count changed, or hosts renamed
            // across deploys). The persisted agent map outlives the
            // ephemeral conductor map. Fall through to auto-provision:
            // the provisioner is idempotent — it searches every current
            // conductor for an existing app installation for this user
            // and re-binds the mapping. Self-healing, no operator step.
            warn!(
                agent = %claims.agent_pub_key,
                stale_conductor = %entry.conductor_id,
                "Stale agent→conductor mapping; re-provisioning to current pool"
            );
            registry.unregister_agent(&claims.agent_pub_key);
            match auto_provision(&state, &registry, &claims).await {
                Ok(triple) => triple,
                Err(resp) => return resp,
            }
        }
    } else {
        // Auto-provision (idempotent — handles logout→re-login)
        match auto_provision(&state, &registry, &claims).await {
            Ok(triple) => triple,
            Err(resp) => return resp,
        }
    };

    info!(
        identifier = %claims.identifier,
        conductor = %conductor_id,
        app = %installed_app_id,
        "Chaperone: resolved conductor"
    );

    // --- Step 3: Connect TypedAdminClient and get app info (with cell readiness polling) ---
    let admin = match TypedAdminClient::connect(&admin_url).await {
        Ok(a) => a,
        Err(e) => {
            error!("Chaperone: admin connect failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Admin connect");
        }
    };

    let app_info = {
        let max_polls = 20;
        let poll_interval = std::time::Duration::from_secs(1);
        let mut last_info = None;
        let mut app_found = false;

        for attempt in 1..=max_polls {
            match admin.get_app_info(&installed_app_id).await {
                Ok(info) => {
                    app_found = true;

                    if !info.cell_ids.is_empty() {
                        debug!(
                            app = %installed_app_id,
                            cells = info.cell_ids.len(),
                            polls = attempt,
                            "Cells ready"
                        );
                        last_info = Some(info);
                        break;
                    }

                    // App found but no cells yet — check if disabled
                    if let Some(ref status) = info.status {
                        if status.eq_ignore_ascii_case("disabled") {
                            warn!(
                                app = %installed_app_id,
                                "App is disabled — attempting re-enable"
                            );
                            if let Err(e) = admin.enable_app(&installed_app_id).await {
                                warn!(
                                    app = %installed_app_id,
                                    error = %e,
                                    "Failed to re-enable disabled app"
                                );
                            }
                        }
                    }

                    // Cells not ready yet — keep polling
                    if attempt < max_polls {
                        debug!(
                            app = %installed_app_id,
                            attempt,
                            status = ?info.status,
                            "Waiting for cells to initialize..."
                        );
                        tokio::time::sleep(poll_interval).await;
                    } else {
                        last_info = Some(info); // Last attempt — use whatever we got
                    }
                }
                Err(e) => {
                    if attempt == max_polls {
                        error!(
                            conductor = %conductor_id,
                            app = %installed_app_id,
                            error = %e,
                            attempts = max_polls,
                            "Chaperone: get_app_info failed after all attempts"
                        );
                        return sanitize_client_error(StatusCode::BAD_GATEWAY, "Get app info");
                    }
                    debug!(
                        app = %installed_app_id,
                        attempt,
                        error = %e,
                        "get_app_info not ready yet, retrying..."
                    );
                    tokio::time::sleep(poll_interval).await;
                }
            }
        }

        match last_info {
            Some(info) if !info.cell_ids.is_empty() => info,
            Some(info) => {
                warn!(
                    conductor = %conductor_id,
                    app = %installed_app_id,
                    status = ?info.status,
                    cell_count = info.cell_ids.len(),
                    "Chaperone: no cells after {}s polling",
                    max_polls
                );
                return json_error(
                    StatusCode::BAD_GATEWAY,
                    &format!(
                        "No cells found in app '{}' on conductor '{}' after {}s (status: {:?})",
                        installed_app_id, conductor_id, max_polls, info.status
                    ),
                );
            }
            None => {
                warn!(
                    conductor = %conductor_id,
                    app = %installed_app_id,
                    app_found,
                    "Chaperone: app info unavailable after polling"
                );
                return sanitize_client_error(StatusCode::BAD_GATEWAY, "Get app info");
            }
        }
    };

    // Track whether we've already attempted a re-enable for CellDisabled errors.
    // Only try once per connect — if it doesn't help, the cells need manual attention.
    let mut reenable_attempted = false;

    // --- Step 4: Grant capabilities per cell ---
    for (role_name, (ref dna_hash, ref agent_key)) in &app_info.cell_ids {
        let role = role_name.clone();
        let tag = format!("chaperone-{role}");
        let dna = dna_hash.clone();
        let agent = agent_key.clone();
        let sk = signing_key.clone();
        let cs = cap_secret.clone();

        let grant_result = TypedAdminClient::with_source_chain_retry(
            || {
                let url = admin.admin_url().to_string();
                let dna = dna.clone();
                let agent = agent.clone();
                let cs = cs.clone();
                let sk = sk.clone();
                let tag = tag.clone();
                async move {
                    let client = TypedAdminClient::connect(&url).await?;
                    client
                        .grant_zome_call_capability((&dna, &agent), &cs, &sk, &tag)
                        .await
                }
            },
            &format!("cap grant for {role}"),
            3,
        )
        .await;

        if let Err(e) = grant_result {
            // CellMissing is non-fatal — skip that cell
            if e.contains("CellMissing") {
                warn!("Chaperone: skipping cap grant for '{}': CellMissing", role);
                continue;
            }

            // CellDisabled — attempt to re-enable the app and retry once
            if e.contains("CellDisabled") && !reenable_attempted {
                reenable_attempted = true;
                warn!(
                    app = %installed_app_id,
                    role = %role,
                    "Cell is disabled — attempting app re-enable and retry"
                );
                if let Err(enable_err) = admin.enable_app(&installed_app_id).await {
                    warn!(
                        app = %installed_app_id,
                        error = %enable_err,
                        "Failed to re-enable app after CellDisabled"
                    );
                } else {
                    // Wait briefly for cells to come back online
                    tokio::time::sleep(std::time::Duration::from_secs(2)).await;

                    // Retry the cap grant for this cell
                    let retry_result = match TypedAdminClient::connect(admin.admin_url()).await {
                        Ok(retry_admin) => {
                            retry_admin
                                .grant_zome_call_capability((dna_hash, agent_key), &cs, &sk, &tag)
                                .await
                        }
                        Err(e) => Err(e),
                    };
                    match retry_result {
                        Ok(()) => {
                            info!(role = %role, "Cap grant succeeded after re-enable");
                            continue;
                        }
                        Err(retry_err) => {
                            if retry_err.contains("CellMissing")
                                || retry_err.contains("CellDisabled")
                            {
                                warn!(
                                    "Chaperone: skipping cap grant for '{}' after re-enable: {}",
                                    role, retry_err
                                );
                                continue;
                            }
                            error!(
                                "Chaperone: cap grant still failed for '{}' after re-enable: {}",
                                role, retry_err
                            );
                            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Cap grant");
                        }
                    }
                }
            }

            // CellDisabled after re-enable already attempted — skip
            if e.contains("CellDisabled") {
                warn!(
                    "Chaperone: skipping cap grant for '{}': CellDisabled (re-enable already attempted)",
                    role
                );
                continue;
            }

            error!("Chaperone: cap grant failed for '{}': {}", role, e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Cap grant");
        }
    }

    // NOTE: authorize_signing_credentials is a client-SDK helper that generates
    // keypairs via Lair — it is NOT a conductor admin API call. The browser
    // generates its own signing keys, and grant_zome_call_capability (Step 4)
    // is the actual admin call that authorizes them. No Step 5 needed.

    // --- Step 5: Get app interface port ---
    let app_port = match admin.list_app_interfaces().await {
        Ok(ports) if !ports.is_empty() => ports[0],
        Ok(_) => {
            error!("Chaperone: no app interfaces registered on conductor");
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "No app interfaces");
        }
        Err(e) => {
            error!("Chaperone: list_app_interfaces failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "List app interfaces");
        }
    };

    // --- Step 6: Issue app authentication token ---
    let app_token = match admin
        .issue_app_authentication_token(&installed_app_id, 3600)
        .await
    {
        Ok(token) => BASE64.encode(&token),
        Err(e) => {
            error!("Chaperone: issue_app_authentication_token failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Issue app token");
        }
    };

    // --- Step 7: Re-issue JWT with conductor_id ---
    let refreshed_token = if claims.conductor_id.is_none() || claims.installed_app_id.is_none() {
        let input = TokenInput {
            human_id: claims.human_id.clone(),
            agent_pub_key: claims.agent_pub_key.clone(),
            identifier: claims.identifier.clone(),
            permission_level: claims.permission_level,
            session_id: claims.session_id.clone(),
            doorway_id: state.args.doorway_id.clone(),
            doorway_url: state.args.doorway_url.clone(),
            conductor_id: Some(conductor_id.clone()),
            installed_app_id: Some(installed_app_id.clone()),
            is_steward: claims.is_steward,
            has_local_conductor: claims.has_local_conductor,
        };
        match jwt.generate_token(input) {
            Ok(t) => t,
            Err(e) => {
                warn!("Chaperone: failed to refresh JWT: {}", e);
                token_str.clone()
            }
        }
    } else {
        token_str.clone()
    };

    // --- Step 8: Build response ---
    let mut cell_ids_map = HashMap::new();
    for (role_name, (ref dna_hash, ref agent_key)) in &app_info.cell_ids {
        cell_ids_map.insert(
            role_name.clone(),
            [BASE64.encode(dna_hash), BASE64.encode(agent_key)],
        );
    }

    let response = ConnectResponse {
        app_token,
        app_port,
        agent_pub_key: BASE64.encode(&app_info.agent_pub_key),
        installed_app_id,
        conductor_id,
        cell_ids: cell_ids_map,
        token: refreshed_token,
    };

    info!(
        identifier = %claims.identifier,
        cells = response.cell_ids.len(),
        app_port = app_port,
        "Chaperone: connection established"
    );

    json_success(StatusCode::OK, &response)
}

// =============================================================================
// Helpers
// =============================================================================

// -----------------------------------------------------------------------
// Federation identity-fork guard (Task 2.3, doorway-federation-failover)
// -----------------------------------------------------------------------
//
// `AgentProvisioner::find_existing_app` folds `conductor_id` into the
// deterministic app id (`generate_app_id`), so when a hosted user lands on
// a doorway that is not their home doorway, this doorway can NEVER find
// the sibling's existing install — every conductor it checks computes a
// different app id than the one the sibling actually created. Left
// unguarded, `auto_provision` silently mints a brand-new, empty hosted
// identity for an already-hosted human. This guard converts that silent
// fork into an honest refusal, with zero DHT dependency (it reads only the
// JWT claims already on hand) — it lands even before cross-doorway JWKS
// verification exists (Task 2.1) and stays correct after.

/// True when `claims_doorway_id` names a doorway other than
/// `self_doorway_id` — i.e. the token was minted by a sibling doorway.
///
/// Empty/missing `claims_doorway_id` is treated as LOCAL, not foreign:
/// pre-federation tokens predate the `doorway_id` claim entirely (it was
/// added to `Claims` later), so an absent or empty value cannot be read as
/// "minted elsewhere" — it must fall back to today's behavior.
fn claims_are_foreign(claims_doorway_id: Option<&str>, self_doorway_id: Option<&str>) -> bool {
    match claims_doorway_id {
        None => false,
        Some("") => false,
        Some(id) => Some(id) != self_doorway_id,
    }
}

/// Build the honest-refusal response for a foreign-doorway auto-provision
/// attempt or an unknown conductor pinned by a foreign-doorway claim:
/// `409 {"error":"hosted-elsewhere","homeDoorway":"<url-or-id>"}`.
fn hosted_elsewhere_response(claims: &crate::auth::jwt::Claims) -> Response<Full<Bytes>> {
    let home_doorway = claims
        .doorway_url
        .clone()
        .or_else(|| claims.doorway_id.clone())
        .unwrap_or_default();
    let body = serde_json::json!({
        "error": "hosted-elsewhere",
        "homeDoorway": home_doorway,
    });
    Response::builder()
        .status(StatusCode::CONFLICT)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body.to_string())))
        .unwrap()
}

/// Decide the response for a JWT-pinned `conductor_id` this doorway has
/// never heard of. A foreign-doorway claim means the user is hosted
/// elsewhere — honest 409, not the misleading "not found in registry" 502.
/// A local claim (self-minted, or a legacy token with no `doorway_id`)
/// keeps the existing 502: this doorway lost track of a conductor it
/// should know about, which is a real registry problem.
fn unknown_conductor_response(
    claims: &crate::auth::jwt::Claims,
    self_doorway_id: Option<&str>,
    conductor_id: &str,
) -> Response<Full<Bytes>> {
    if claims_are_foreign(claims.doorway_id.as_deref(), self_doorway_id) {
        return hosted_elsewhere_response(claims);
    }
    json_error(
        StatusCode::BAD_GATEWAY,
        &format!("Conductor '{}' not found in registry", conductor_id),
    )
}

/// Resolve a conductor for the user via the idempotent provisioner.
///
/// Returns `(conductor_id, admin_url, installed_app_id)` on success, or a
/// pre-built error response on failure. Used from two paths in
/// `handle_hc_connect`:
/// 1. The unknown-agent path (agent never seen by this doorway before)
/// 2. The stale-mapping path (agent in MongoDB references a conductor_id
///    that is no longer in the current pool)
///
/// The provisioner walks every current conductor looking for an existing
/// app for this user (deterministic app_id) before installing a new one,
/// so calling this for a stale mapping naturally re-binds the agent.
async fn auto_provision(
    state: &Arc<AppState>,
    registry: &Arc<crate::conductor::ConductorRegistry>,
    claims: &crate::auth::jwt::Claims,
) -> Result<(String, String, String), Response<Full<Bytes>>> {
    // Guard: never silently fork a hosted identity for a human whose token
    // was minted by a sibling doorway. See the module comment above.
    if claims_are_foreign(
        claims.doorway_id.as_deref(),
        state.args.doorway_id.as_deref(),
    ) {
        warn!(
            identifier = %claims.identifier,
            claims_doorway = ?claims.doorway_id,
            self_doorway = ?state.args.doorway_id,
            "Refusing auto-provision: token was minted by a foreign doorway"
        );
        return Err(hosted_elsewhere_response(claims));
    }

    let provisioner = AgentProvisioner::new(Arc::clone(registry))
        .with_app_id(state.args.installed_app_id.clone())
        .with_bundle_path(state.args.happ_bundle_path.clone());

    let provisioned = match provisioner.provision_agent(&claims.identifier).await {
        Ok(p) => p,
        Err(e) => {
            error!("Chaperone auto-provision failed: {}", e);
            return Err(sanitize_client_error(
                StatusCode::SERVICE_UNAVAILABLE,
                "Auto-provision",
            ));
        }
    };

    let info = match registry.get_conductor_info(&provisioned.conductor_id) {
        Some(i) => i,
        None => {
            return Err(json_error(
                StatusCode::BAD_GATEWAY,
                "Provisioned conductor info not found",
            ));
        }
    };

    // Also register the JWT's agent_pub_key so Path 2 succeeds on future
    // connects without re-walking every conductor. The provisioner registers
    // the conductor-generated key; the JWT carries the auth-system key —
    // both need to resolve to the same conductor.
    if claims.agent_pub_key != provisioned.agent_pub_key {
        let _ = registry
            .register_agent(
                &claims.agent_pub_key,
                &provisioned.conductor_id,
                &provisioned.installed_app_id,
            )
            .await;
    }

    Ok((
        provisioned.conductor_id,
        info.admin_url,
        provisioned.installed_app_id,
    ))
}

/// Sanitize internal error details for client-facing responses.
/// Full errors are already logged server-side via `error!()` / `warn!()`.
fn sanitize_client_error(status: StatusCode, operation: &str) -> Response<Full<Bytes>> {
    let message = match status {
        StatusCode::BAD_GATEWAY => format!("{operation}: service temporarily unavailable"),
        StatusCode::SERVICE_UNAVAILABLE => "Service temporarily unavailable".to_string(),
        _ => format!("{operation} failed"),
    };
    json_error(status, &message)
}

fn json_error(status: StatusCode, message: &str) -> Response<Full<Bytes>> {
    let body = serde_json::json!({ "error": message });
    Response::builder()
        .status(status)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body.to_string())))
        .unwrap()
}

fn json_success<T: Serialize>(status: StatusCode, data: &T) -> Response<Full<Bytes>> {
    let body =
        serde_json::to_string(data).unwrap_or_else(|_| r#"{"error":"serialization"}"#.into());
    Response::builder()
        .status(status)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body)))
        .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::jwt::Claims;
    use crate::auth::PermissionLevel;
    use crate::conductor::registry::{ConductorInfo, ConductorRegistry};
    use crate::config::Args;
    use clap::Parser;

    /// Minimal Claims fixture. `doorway_id`/`doorway_url` are the only fields
    /// the foreign-doorway guard inspects.
    fn test_claims(doorway_id: Option<&str>, doorway_url: Option<&str>) -> Claims {
        Claims {
            human_id: "human-1".into(),
            agent_pub_key: "uhCAk-test".into(),
            identifier: "test@example.com".into(),
            permission_level: PermissionLevel::Authenticated,
            doorway_operator: None,
            session_id: None,
            doorway_id: doorway_id.map(str::to_string),
            doorway_url: doorway_url.map(str::to_string),
            conductor_id: None,
            installed_app_id: None,
            is_steward: false,
            has_local_conductor: false,
            version: 1,
            iat: 0,
            exp: u64::MAX,
        }
    }

    /// AppState carrying `self_doorway_id` as its own `DOORWAY_ID` and the
    /// given (possibly empty) conductor registry.
    fn test_state(self_doorway_id: Option<&str>, registry: ConductorRegistry) -> Arc<AppState> {
        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = self_doorway_id.map(str::to_string);
        let mut state = AppState::new(args);
        state.conductor_registry = Some(Arc::new(registry));
        Arc::new(state)
    }

    async fn body_json(resp: Response<Full<Bytes>>) -> serde_json::Value {
        let bytes = resp.into_body().collect().await.unwrap().to_bytes();
        serde_json::from_slice(&bytes).expect("response body must be JSON")
    }

    // ---- claims_are_foreign (pure classification) ----

    #[test]
    fn claims_are_foreign_treats_missing_and_empty_as_local() {
        assert!(!claims_are_foreign(None, Some("self-doorway")));
        assert!(!claims_are_foreign(Some(""), Some("self-doorway")));
    }

    #[test]
    fn claims_are_foreign_treats_self_id_as_local() {
        assert!(!claims_are_foreign(
            Some("self-doorway"),
            Some("self-doorway")
        ));
    }

    #[test]
    fn claims_are_foreign_flags_sibling_id() {
        assert!(claims_are_foreign(
            Some("sibling-doorway"),
            Some("self-doorway")
        ));
    }

    // ---- auto_provision guard (Task 2.3: kill the silent identity fork) ----

    /// Foreign `doorway_id` + unknown user (no agent→conductor mapping) must
    /// be refused with 409 hosted-elsewhere — never silently provisioned.
    /// A conductor IS registered here: if the guard did not fire first, the
    /// call would fall through to `provisioner.provision_agent`, which (with
    /// no live conductor to actually connect to) would eventually surface as
    /// 503, never 409. Getting 409 proves the guard short-circuited before
    /// the provisioner was ever invoked.
    #[tokio::test]
    async fn auto_provision_refuses_foreign_doorway_claim() {
        let registry = ConductorRegistry::new(None).await;
        registry.register_conductor(ConductorInfo {
            conductor_id: "conductor-0".into(),
            conductor_url: "ws://c0:4445".into(),
            admin_url: "ws://c0:4444".into(),
            capacity_used: 0,
            capacity_max: 50,
        });
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("sibling-doorway"), Some("https://sibling.elohim.host"));

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("foreign-doorway claim must be refused, not provisioned");
        assert_eq!(resp.status(), StatusCode::CONFLICT);
        let body = body_json(resp).await;
        assert_eq!(body["error"], "hosted-elsewhere");
        assert_eq!(body["homeDoorway"], "https://sibling.elohim.host");
    }

    /// Local `doorway_id` + unknown agent must still reach the pre-existing
    /// provisioning path. No conductors are registered, so a request that
    /// gets past the guard hits the original "no conductors available"
    /// error (503) — proving the new guard did not block a local claim.
    #[tokio::test]
    async fn auto_provision_proceeds_for_local_doorway_claim() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("self-doorway"), None);

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("no conductors registered");
        assert_eq!(resp.status(), StatusCode::SERVICE_UNAVAILABLE);
    }

    /// Legacy tokens minted before `doorway_id` existed on Claims carry
    /// `None`; tokens minted with an explicitly empty string must be treated
    /// the same way — local, not foreign.
    #[tokio::test]
    async fn auto_provision_treats_empty_doorway_id_as_local() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some(""), None);

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("no conductors registered");
        assert_eq!(resp.status(), StatusCode::SERVICE_UNAVAILABLE);
    }

    // ---- unknown_conductor_response (the conductor-pinned 502 vs 409 split) ----

    /// A JWT pinning a `conductor_id` this doorway has never heard of, minted
    /// by a sibling doorway, means the user is hosted elsewhere — 409, not
    /// the misleading "Conductor not found in registry" 502.
    #[test]
    fn unknown_conductor_with_foreign_doorway_is_409_hosted_elsewhere() {
        let claims = test_claims(Some("sibling-doorway"), Some("https://sibling.elohim.host"));
        let resp = unknown_conductor_response(&claims, Some("self-doorway"), "conductor-9");
        assert_eq!(resp.status(), StatusCode::CONFLICT);
    }

    /// A JWT pinning an unknown `conductor_id` minted by THIS doorway is a
    /// real registry problem (e.g. pool composition changed) — stays 502.
    #[test]
    fn unknown_conductor_with_local_doorway_stays_502() {
        let claims = test_claims(Some("self-doorway"), None);
        let resp = unknown_conductor_response(&claims, Some("self-doorway"), "conductor-9");
        assert_eq!(resp.status(), StatusCode::BAD_GATEWAY);
    }

    /// Captures the stale-agent-mapping bug class that previously surfaced
    /// as `502 {"error":"Conductor info not found"}` from `/hc/connect`.
    ///
    /// The agent→conductor map persists across doorway restarts (MongoDB
    /// `conductor_registry`), but the conductor map is in-memory only and
    /// is rebuilt from `CONDUCTOR_URLS` each boot. When pool composition
    /// changes (reorder, count change, host rename), persisted rows can
    /// reference conductor_ids that no longer exist in the pool.
    ///
    /// `handle_hc_connect` detects this (Path 2 `get_conductor_info`
    /// returns `None`), unregisters the stale local entry, then calls
    /// `auto_provision`. The provisioner is idempotent — it walks every
    /// current conductor for an existing app for this user and re-binds.
    /// This test exercises the registry-level shape of that recovery.
    #[tokio::test]
    async fn stale_agent_mapping_recovers_via_unregister_and_re_register() {
        let registry = ConductorRegistry::new(None).await;

        // Boot 1 (simulated): pool had a conductor-3; user was assigned to it.
        registry
            .register_agent("uhCAk_user_a", "conductor-3", "elohim-conductor-3-abc123")
            .await
            .unwrap();

        // Boot 2: pool now has only conductor-0; conductor-3 is gone.
        registry.register_conductor(ConductorInfo {
            conductor_id: "conductor-0".to_string(),
            conductor_url: "ws://c0:4445".to_string(),
            admin_url: "ws://c0:4444".to_string(),
            capacity_used: 0,
            capacity_max: 50,
        });

        // Bug shape: agent lookup succeeds but conductor lookup fails.
        let entry = registry.get_conductor_for_agent("uhCAk_user_a").unwrap();
        assert_eq!(entry.conductor_id, "conductor-3");
        assert!(
            registry.get_conductor_info(&entry.conductor_id).is_none(),
            "stale conductor_id should not resolve in current pool"
        );

        // Recovery shape that handle_hc_connect now performs on this case.
        registry.unregister_agent("uhCAk_user_a");
        assert!(
            registry.get_conductor_for_agent("uhCAk_user_a").is_none(),
            "stale entry must be cleared before re-provision"
        );

        // auto_provision (mocked here at the registry layer) picks a current
        // conductor and re-registers the JWT's agent_pub_key.
        registry
            .register_agent("uhCAk_user_a", "conductor-0", "elohim-conductor-0-xyz789")
            .await
            .unwrap();

        let recovered = registry.get_conductor_for_agent("uhCAk_user_a").unwrap();
        assert_eq!(recovered.conductor_id, "conductor-0");
        assert!(
            registry
                .get_conductor_info(&recovered.conductor_id)
                .is_some(),
            "recovered mapping must reach a current conductor"
        );
    }
}
