//! Chaperone: Server-side admin protocol for Holochain connection setup.
//!
//! Replaces the browser's 11-step admin WebSocket dance with a single
//! `POST /hc/connect` call. The browser generates signing keys locally,
//! sends the public key + cap secret, and doorway handles all admin
//! operations (cap grants, credential authorization, token issuance)
//! on the correct conductor.
//!
//! This eliminates:
//! - Two-WebSocket routing problem (admin + app must hit same conductor)
//! - Session affinity cache
//! - Admin protocol exposure in production
//! - Key format matching between browser and conductor

use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use bytes::Bytes;
use http_body_util::{BodyExt, Full};
use hyper::{Request, Response, StatusCode};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tracing::{debug, error, info, warn};

use crate::auth::{extract_token_from_header, TokenInput};
use crate::conductor::typed_admin::TypedAdminClient;
use crate::conductor::AgentProvisioner;
use crate::server::http::AppState;

/// Request body for `POST /hc/connect`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectRequest {
    /// Base64 Ed25519 public signing key (generated by browser)
    pub signing_key: String,
    /// Base64 capability secret (generated by browser)
    pub cap_secret: String,
}

/// Response body for `POST /hc/connect`.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectResponse {
    /// Base64 Holochain app auth token for AppWebsocket
    pub app_token: String,
    /// App WebSocket port
    pub app_port: u16,
    /// Base64 agent public key
    pub agent_pub_key: String,
    /// Installed app ID
    pub installed_app_id: String,
    /// Conductor ID (also embedded in refreshed JWT)
    pub conductor_id: String,
    /// Cell IDs: { role_name: [dna_hash_b64, agent_key_b64] }
    pub cell_ids: HashMap<String, [String; 2]>,
    /// Refreshed JWT with conductor_id embedded
    pub token: String,
}

/// Handle `POST /hc/connect` — the Chaperone endpoint.
///
/// Orchestration flow:
/// 1. Extract JWT from Authorization header
/// 2. Resolve conductor (from claims.conductor_id, registry, or auto-provision)
/// 3. Get app info (cell IDs per role)
/// 4. Grant capabilities per cell (with source chain retry)
/// 5. Authorize signing credentials per cell (with retry)
/// 6. Get app interface port
/// 7. Issue app authentication token
/// 8. Re-issue JWT with conductor_id if not already present
/// 9. Return ConnectResponse
pub async fn handle_hc_connect(
    req: Request<hyper::body::Incoming>,
    state: Arc<AppState>,
) -> Response<Full<Bytes>> {
    // --- Step 1: Extract and validate JWT ---
    let auth_header = req
        .headers()
        .get(hyper::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());

    let token_str = match extract_token_from_header(auth_header) {
        Some(t) => t.to_string(),
        None => {
            return json_error(StatusCode::UNAUTHORIZED, "Missing Authorization header");
        }
    };

    // The ORIGINAL request path, captured before `req` is consumed. It is the
    // only piece of request input that reaches the redirect, and it is appended
    // as a PATH — never as the host (see `hosted_at_redirect_response`).
    let original_path = req.uri().path().to_string();

    // T2.2 live wiring: the federation-aware validator. Verification is
    // dual-algorithm (self HS256/EdDSA + sibling EdDSA via the peer JWKS
    // cache); an unresolvable foreign `kid` fails closed to `UnknownIssuer`
    // rather than falling through to the HS256 secret.
    let jwt = match state.federation_jwt_validator() {
        Some(v) => v,
        None => return json_error(StatusCode::INTERNAL_SERVER_ERROR, "JWT not configured"),
    };

    let claims = match jwt.verify_token_detailed(&token_str) {
        Ok(c) => c,
        Err(_) => {
            // Includes `UnknownIssuer` — an UNVERIFIED foreign token. This is
            // exactly today's 401, and it must stay one: redirecting on an
            // unverified issuer claim would be an open redirect driven by an
            // attacker-supplied token.
            return json_error(StatusCode::UNAUTHORIZED, "Invalid or expired token");
        }
    };

    // --- Step 1b: honest cross-doorway landing (T2.2) ---
    //
    // The token VERIFIED and it was minted by a sibling doorway. This human is
    // hosted elsewhere; this doorway must neither 502 (conductor-pinned) nor
    // silently provision a fresh empty identity. Send them home.
    if claims_are_foreign(
        claims.doorway_id.as_deref(),
        state.args.doorway_id.as_deref(),
    ) {
        return match resolve_home_doorway(&state, &claims).await {
            Some(home_url) => {
                info!(
                    identifier = %claims.identifier,
                    home = %home_url,
                    "Chaperone: verified foreign token — redirecting to home doorway"
                );
                hosted_at_redirect_response(&home_url, &original_path)
            }
            None => {
                warn!(
                    identifier = %claims.identifier,
                    claims_doorway = ?claims.doorway_id,
                    "Chaperone: verified foreign token but home doorway unresolvable"
                );
                hosted_elsewhere_response(&claims)
            }
        };
    }

    // --- Read request body ---
    let body_bytes = match req.collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(e) => {
            warn!("Failed to read /hc/connect body: {}", e);
            return json_error(StatusCode::BAD_REQUEST, "Failed to read request body");
        }
    };

    let body: ConnectRequest = match serde_json::from_slice(&body_bytes) {
        Ok(b) => b,
        Err(e) => {
            return json_error(StatusCode::BAD_REQUEST, &format!("Invalid JSON: {e}"));
        }
    };

    // Decode base64 inputs.
    //
    // The LENGTH check is not optional: `AgentPubKey::from_raw_39` (reached via
    // `TypedAdminClient::grant_zome_call_capability`) `unwrap()`s a `BadSize`
    // error, so a wrong-length key from ANY authenticated caller panicked a
    // doorway tokio worker mid-request instead of answering 400. `cap_secret`
    // immediately below was already length-checked downstream; this one was not.
    const AGENT_PUB_KEY_RAW_LEN: usize = 39; // 3-byte prefix + 32-byte hash + 4-byte loc
    let signing_key = match BASE64.decode(&body.signing_key) {
        Ok(k) if k.len() == AGENT_PUB_KEY_RAW_LEN => k,
        Ok(k) => {
            return json_error(
                StatusCode::BAD_REQUEST,
                &format!(
                    "Invalid signing_key length: expected {AGENT_PUB_KEY_RAW_LEN}, got {}",
                    k.len()
                ),
            )
        }
        Err(_) => return json_error(StatusCode::BAD_REQUEST, "Invalid base64 signing_key"),
    };
    let cap_secret = match BASE64.decode(&body.cap_secret) {
        Ok(s) => s,
        Err(_) => return json_error(StatusCode::BAD_REQUEST, "Invalid base64 cap_secret"),
    };

    // --- Step 2: Resolve conductor ---
    let registry = match &state.conductor_registry {
        Some(r) => Arc::clone(r),
        None => {
            return json_error(
                StatusCode::SERVICE_UNAVAILABLE,
                "No conductor registry available",
            );
        }
    };

    // Try conductor_id from JWT claims first
    let (conductor_id, admin_url, installed_app_id) = if let Some(ref cid) = claims.conductor_id {
        if let Some(info) = registry.get_conductor_info(cid) {
            let app_id = claims
                .installed_app_id
                .clone()
                .unwrap_or_else(|| state.args.installed_app_id.clone());
            (cid.clone(), info.admin_url, app_id)
        } else {
            // Unknown conductor_id. If the claim was minted by a sibling
            // doorway, this is the expected shape of "hosted elsewhere" —
            // return the honest 409, not the misleading "not found in
            // registry" 502 (see `unknown_conductor_response`).
            return unknown_conductor_response(&claims, state.args.doorway_id.as_deref(), cid);
        }
    } else if let Some(entry) = registry.get_conductor_for_agent(&claims.agent_pub_key) {
        // Agent already registered in conductor registry
        if let Some(info) = registry.get_conductor_info(&entry.conductor_id) {
            (entry.conductor_id, info.admin_url, entry.app_id)
        } else {
            // Stale registry entry — the conductor_id stored in MongoDB no
            // longer exists in the current in-memory conductor pool (e.g.,
            // CONDUCTOR_URLS reordered, count changed, or hosts renamed
            // across deploys). The persisted agent map outlives the
            // ephemeral conductor map. Fall through to auto-provision:
            // the provisioner is idempotent — it searches every current
            // conductor for an existing app installation for this user
            // and re-binds the mapping. Self-healing, no operator step.
            warn!(
                agent = %claims.agent_pub_key,
                stale_conductor = %entry.conductor_id,
                "Stale agent→conductor mapping; re-provisioning to current pool"
            );
            registry.unregister_agent(&claims.agent_pub_key);
            match auto_provision(&state, &registry, &claims).await {
                Ok(triple) => triple,
                Err(resp) => return resp,
            }
        }
    } else {
        // Auto-provision (idempotent — handles logout→re-login)
        match auto_provision(&state, &registry, &claims).await {
            Ok(triple) => triple,
            Err(resp) => return resp,
        }
    };

    info!(
        identifier = %claims.identifier,
        conductor = %conductor_id,
        app = %installed_app_id,
        "Chaperone: resolved conductor"
    );

    // --- Step 3: Connect TypedAdminClient and get app info (with cell readiness polling) ---
    let admin = match TypedAdminClient::connect(&admin_url).await {
        Ok(a) => a,
        Err(e) => {
            error!("Chaperone: admin connect failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Admin connect");
        }
    };

    let app_info = {
        let max_polls = 20;
        let poll_interval = std::time::Duration::from_secs(1);
        let mut last_info = None;
        let mut app_found = false;

        for attempt in 1..=max_polls {
            match admin.get_app_info(&installed_app_id).await {
                Ok(info) => {
                    app_found = true;

                    if !info.cell_ids.is_empty() {
                        debug!(
                            app = %installed_app_id,
                            cells = info.cell_ids.len(),
                            polls = attempt,
                            "Cells ready"
                        );
                        last_info = Some(info);
                        break;
                    }

                    // App found but no cells yet — check if disabled
                    if let Some(ref status) = info.status {
                        if status.eq_ignore_ascii_case("disabled") {
                            warn!(
                                app = %installed_app_id,
                                "App is disabled — attempting re-enable"
                            );
                            if let Err(e) = admin.enable_app(&installed_app_id).await {
                                warn!(
                                    app = %installed_app_id,
                                    error = %e,
                                    "Failed to re-enable disabled app"
                                );
                            }
                        }
                    }

                    // Cells not ready yet — keep polling
                    if attempt < max_polls {
                        debug!(
                            app = %installed_app_id,
                            attempt,
                            status = ?info.status,
                            "Waiting for cells to initialize..."
                        );
                        tokio::time::sleep(poll_interval).await;
                    } else {
                        last_info = Some(info); // Last attempt — use whatever we got
                    }
                }
                Err(e) => {
                    if attempt == max_polls {
                        error!(
                            conductor = %conductor_id,
                            app = %installed_app_id,
                            error = %e,
                            attempts = max_polls,
                            "Chaperone: get_app_info failed after all attempts"
                        );
                        return sanitize_client_error(StatusCode::BAD_GATEWAY, "Get app info");
                    }
                    debug!(
                        app = %installed_app_id,
                        attempt,
                        error = %e,
                        "get_app_info not ready yet, retrying..."
                    );
                    tokio::time::sleep(poll_interval).await;
                }
            }
        }

        match last_info {
            Some(info) if !info.cell_ids.is_empty() => info,
            Some(info) => {
                warn!(
                    conductor = %conductor_id,
                    app = %installed_app_id,
                    status = ?info.status,
                    cell_count = info.cell_ids.len(),
                    "Chaperone: no cells after {}s polling",
                    max_polls
                );
                return json_error(
                    StatusCode::BAD_GATEWAY,
                    &format!(
                        "No cells found in app '{}' on conductor '{}' after {}s (status: {:?})",
                        installed_app_id, conductor_id, max_polls, info.status
                    ),
                );
            }
            None => {
                warn!(
                    conductor = %conductor_id,
                    app = %installed_app_id,
                    app_found,
                    "Chaperone: app info unavailable after polling"
                );
                return sanitize_client_error(StatusCode::BAD_GATEWAY, "Get app info");
            }
        }
    };

    // Track whether we've already attempted a re-enable for CellDisabled errors.
    // Only try once per connect — if it doesn't help, the cells need manual attention.
    let mut reenable_attempted = false;

    // --- Step 4: Grant capabilities per cell ---
    for (role_name, (ref dna_hash, ref agent_key)) in &app_info.cell_ids {
        let role = role_name.clone();
        let tag = format!("chaperone-{role}");
        let dna = dna_hash.clone();
        let agent = agent_key.clone();
        let sk = signing_key.clone();
        let cs = cap_secret.clone();

        let grant_result = TypedAdminClient::with_source_chain_retry(
            || {
                let url = admin.admin_url().to_string();
                let dna = dna.clone();
                let agent = agent.clone();
                let cs = cs.clone();
                let sk = sk.clone();
                let tag = tag.clone();
                async move {
                    let client = TypedAdminClient::connect(&url).await?;
                    client
                        .grant_zome_call_capability((&dna, &agent), &cs, &sk, &tag)
                        .await
                }
            },
            &format!("cap grant for {role}"),
            3,
        )
        .await;

        if let Err(e) = grant_result {
            // CellMissing is non-fatal — skip that cell
            if e.contains("CellMissing") {
                warn!("Chaperone: skipping cap grant for '{}': CellMissing", role);
                continue;
            }

            // CellDisabled — attempt to re-enable the app and retry once
            if e.contains("CellDisabled") && !reenable_attempted {
                reenable_attempted = true;
                warn!(
                    app = %installed_app_id,
                    role = %role,
                    "Cell is disabled — attempting app re-enable and retry"
                );
                if let Err(enable_err) = admin.enable_app(&installed_app_id).await {
                    warn!(
                        app = %installed_app_id,
                        error = %enable_err,
                        "Failed to re-enable app after CellDisabled"
                    );
                } else {
                    // Wait briefly for cells to come back online
                    tokio::time::sleep(std::time::Duration::from_secs(2)).await;

                    // Retry the cap grant for this cell
                    let retry_result = match TypedAdminClient::connect(admin.admin_url()).await {
                        Ok(retry_admin) => {
                            retry_admin
                                .grant_zome_call_capability((dna_hash, agent_key), &cs, &sk, &tag)
                                .await
                        }
                        Err(e) => Err(e),
                    };
                    match retry_result {
                        Ok(()) => {
                            info!(role = %role, "Cap grant succeeded after re-enable");
                            continue;
                        }
                        Err(retry_err) => {
                            if retry_err.contains("CellMissing")
                                || retry_err.contains("CellDisabled")
                            {
                                warn!(
                                    "Chaperone: skipping cap grant for '{}' after re-enable: {}",
                                    role, retry_err
                                );
                                continue;
                            }
                            error!(
                                "Chaperone: cap grant still failed for '{}' after re-enable: {}",
                                role, retry_err
                            );
                            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Cap grant");
                        }
                    }
                }
            }

            // CellDisabled after re-enable already attempted — skip
            if e.contains("CellDisabled") {
                warn!(
                    "Chaperone: skipping cap grant for '{}': CellDisabled (re-enable already attempted)",
                    role
                );
                continue;
            }

            error!("Chaperone: cap grant failed for '{}': {}", role, e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Cap grant");
        }
    }

    // NOTE: authorize_signing_credentials is a client-SDK helper that generates
    // keypairs via Lair — it is NOT a conductor admin API call. The browser
    // generates its own signing keys, and grant_zome_call_capability (Step 4)
    // is the actual admin call that authorizes them. No Step 5 needed.

    // --- Step 5: Get app interface port ---
    let app_port = match admin.list_app_interfaces().await {
        Ok(ports) if !ports.is_empty() => ports[0],
        Ok(_) => {
            error!("Chaperone: no app interfaces registered on conductor");
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "No app interfaces");
        }
        Err(e) => {
            error!("Chaperone: list_app_interfaces failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "List app interfaces");
        }
    };

    // --- Step 6: Issue app authentication token ---
    let app_token = match admin
        .issue_app_authentication_token(&installed_app_id, 3600)
        .await
    {
        Ok(token) => BASE64.encode(&token),
        Err(e) => {
            error!("Chaperone: issue_app_authentication_token failed: {}", e);
            return sanitize_client_error(StatusCode::BAD_GATEWAY, "Issue app token");
        }
    };

    // --- Step 7: Re-issue JWT with conductor_id ---
    let refreshed_token = if claims.conductor_id.is_none() || claims.installed_app_id.is_none() {
        let input = TokenInput {
            human_id: claims.human_id.clone(),
            agent_pub_key: claims.agent_pub_key.clone(),
            identifier: claims.identifier.clone(),
            permission_level: claims.permission_level,
            session_id: claims.session_id.clone(),
            doorway_id: state.args.doorway_id.clone(),
            doorway_url: state.args.doorway_url.clone(),
            conductor_id: Some(conductor_id.clone()),
            installed_app_id: Some(installed_app_id.clone()),
            is_steward: claims.is_steward,
            has_local_conductor: claims.has_local_conductor,
        };
        match jwt.generate_token(input) {
            Ok(t) => t,
            Err(e) => {
                warn!("Chaperone: failed to refresh JWT: {}", e);
                token_str.clone()
            }
        }
    } else {
        token_str.clone()
    };

    // --- Step 8: Build response ---
    let mut cell_ids_map = HashMap::new();
    for (role_name, (ref dna_hash, ref agent_key)) in &app_info.cell_ids {
        cell_ids_map.insert(
            role_name.clone(),
            [BASE64.encode(dna_hash), BASE64.encode(agent_key)],
        );
    }

    let response = ConnectResponse {
        app_token,
        app_port,
        agent_pub_key: BASE64.encode(&app_info.agent_pub_key),
        installed_app_id,
        conductor_id,
        cell_ids: cell_ids_map,
        token: refreshed_token,
    };

    info!(
        identifier = %claims.identifier,
        cells = response.cell_ids.len(),
        app_port = app_port,
        "Chaperone: connection established"
    );

    json_success(StatusCode::OK, &response)
}

// =============================================================================
// Helpers
// =============================================================================

// -----------------------------------------------------------------------
// Federation identity-fork guard (Task 2.3, doorway-federation-failover)
// -----------------------------------------------------------------------
//
// `AgentProvisioner::find_existing_app` folds `conductor_id` into the
// deterministic app id (`generate_app_id`), so when a hosted user lands on
// a doorway that is not their home doorway, this doorway can NEVER find
// the sibling's existing install — every conductor it checks computes a
// different app id than the one the sibling actually created. Left
// unguarded, `auto_provision` silently mints a brand-new, empty hosted
// identity for an already-hosted human. This guard converts that silent
// fork into an honest refusal, with zero DHT dependency (it reads only the
// JWT claims already on hand) — it lands even before cross-doorway JWKS
// verification exists (Task 2.1) and stays correct after.

/// True when `claims_doorway_id` names a doorway other than
/// `self_doorway_id` — i.e. the token was minted by a sibling doorway.
///
/// Empty/missing `claims_doorway_id` is treated as LOCAL, not foreign:
/// pre-federation tokens predate the `doorway_id` claim entirely (it was
/// added to `Claims` later), so an absent or empty value cannot be read as
/// "minted elsewhere" — it must fall back to today's behavior.
fn claims_are_foreign(claims_doorway_id: Option<&str>, self_doorway_id: Option<&str>) -> bool {
    match claims_doorway_id {
        None => false,
        Some("") => false,
        Some(id) => Some(id) != self_doorway_id,
    }
}

/// Build the honest-refusal response for a foreign-doorway auto-provision
/// attempt or an unknown conductor pinned by a foreign-doorway claim:
/// `409 {"error":"hosted-elsewhere","homeDoorway":"<url-or-id>"}`.
fn hosted_elsewhere_response(claims: &crate::auth::jwt::Claims) -> Response<Full<Bytes>> {
    let home_doorway = claims
        .doorway_url
        .clone()
        .or_else(|| claims.doorway_id.clone())
        .unwrap_or_default();
    let body = serde_json::json!({
        "error": "hosted-elsewhere",
        "homeDoorway": home_doorway,
    });
    Response::builder()
        .status(StatusCode::CONFLICT)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body.to_string())))
        .unwrap()
}

// ---------------------------------------------------------------------------
// T2.2 — honest cross-doorway landing
// ---------------------------------------------------------------------------

/// The response header naming where a hosted human actually lives. Present on
/// both the 307 and (for symmetry with future clients) nothing else — the 409
/// carries `homeDoorway` in its JSON body.
pub const HOSTED_AT_HEADER: &str = "X-Elohim-Hosted-At";

/// OPEN-REDIRECT GUARD.
///
/// Accepts a candidate home-doorway URL ONLY if it is an absolute `http`/`https`
/// URL with a non-empty host and no embedded credentials. Everything else —
/// scheme-relative `//evil.example`, a bare path, a `javascript:` URI, an
/// authority with `@` — is rejected, and the caller degrades to the honest 409.
///
/// The candidate itself must come from a *verified* source: the `doorway_url`
/// claim inside a signature-verified JWT, or a row in the DHT-projected
/// `hosted_agent_bindings` table. It must NEVER come from request input — no
/// header, no query parameter, no body field. That provenance rule is enforced
/// by `resolve_home_doorway`, which has no access to the request.
fn sanitize_home_doorway_url(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    let rest = trimmed
        .strip_prefix("https://")
        .or_else(|| trimmed.strip_prefix("http://"))?;

    // Authority ends at the first '/', '?' or '#'.
    let authority = rest
        .split(['/', '?', '#'])
        .next()
        .unwrap_or_default()
        .to_string();

    if authority.is_empty() {
        return None;
    }
    // Reject userinfo (`user:pass@host`) — the classic look-alike-host trick.
    if authority.contains('@') {
        return None;
    }
    // Reject whitespace and control characters anywhere in the URL.
    if trimmed.chars().any(|c| c.is_whitespace() || c.is_control()) {
        return None;
    }

    Some(trimmed.trim_end_matches('/').to_string())
}

/// Build the honest `307 Temporary Redirect` to a hosted human's home doorway.
///
/// 307 (not 302) so the browser/client REPLAYS the original method and body —
/// `/hc/connect` is a POST carrying the browser's freshly generated signing key,
/// and a 302 would silently downgrade it to a GET.
///
/// `home_url` is already sanitized; `original_path` contributes ONLY the path,
/// appended after the verified authority — request input can never influence
/// which host is redirected to.
fn hosted_at_redirect_response(home_url: &str, original_path: &str) -> Response<Full<Bytes>> {
    let path = if original_path.starts_with('/') {
        original_path
    } else {
        "/"
    };
    let location = format!("{home_url}{path}");
    let body = serde_json::json!({
        "error": "hosted-elsewhere",
        "homeDoorway": home_url,
    });
    Response::builder()
        .status(StatusCode::TEMPORARY_REDIRECT)
        .header(hyper::header::LOCATION, &location)
        .header(HOSTED_AT_HEADER, home_url)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body.to_string())))
        .unwrap()
}

/// Resolve a verified-foreign human's home doorway URL.
///
/// Two sources, in order:
/// 1. `claims.doorway_url` — already trusted: it is INSIDE the signature-verified
///    token, so the issuing doorway asserted it and we verified the signature.
/// 2. The `hosted_agent_bindings` projection of the imagodei `hosted-at` link,
///    read from this node's own elohim-storage. Used when the token predates the
///    `doorway_url` claim (legacy tokens carry only `doorway_id`).
///
/// Neither source is request input. Both pass through
/// [`sanitize_home_doorway_url`]. `None` means "unresolvable" — the caller
/// answers the existing honest 409 rather than guessing.
async fn resolve_home_doorway(
    state: &Arc<AppState>,
    claims: &crate::auth::jwt::Claims,
) -> Option<String> {
    if let Some(ref url) = claims.doorway_url {
        if let Some(sanitized) = sanitize_home_doorway_url(url) {
            return Some(sanitized);
        }
        warn!(
            claimed = %url,
            "Rejected doorway_url claim: not an absolute http(s) URL with a plain host"
        );
    }

    let storage_url = state.args.storage_url.as_ref()?;
    let url = format!(
        "{}/api/v1/federation/hosted-binding/{}",
        storage_url.trim_end_matches('/'),
        claims.agent_pub_key
    );

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3))
        .build()
        .ok()?;
    let resp = client.get(&url).send().await.ok()?;
    if !resp.status().is_success() {
        debug!(
            agent = %claims.agent_pub_key,
            status = %resp.status(),
            "No hosted binding projected for this agent"
        );
        return None;
    }
    let body: serde_json::Value = resp.json().await.ok()?;
    let projected = body.get("doorwayUrl")?.as_str()?;
    sanitize_home_doorway_url(projected)
}

/// Decide the response for a JWT-pinned `conductor_id` this doorway has
/// never heard of. A foreign-doorway claim means the user is hosted
/// elsewhere — honest 409, not the misleading "not found in registry" 502.
/// A local claim (self-minted, or a legacy token with no `doorway_id`)
/// keeps the existing 502: this doorway lost track of a conductor it
/// should know about, which is a real registry problem.
fn unknown_conductor_response(
    claims: &crate::auth::jwt::Claims,
    self_doorway_id: Option<&str>,
    conductor_id: &str,
) -> Response<Full<Bytes>> {
    if claims_are_foreign(claims.doorway_id.as_deref(), self_doorway_id) {
        return hosted_elsewhere_response(claims);
    }
    json_error(
        StatusCode::BAD_GATEWAY,
        &format!("Conductor '{}' not found in registry", conductor_id),
    )
}

/// Resolve a conductor for the user via the idempotent provisioner.
///
/// Returns `(conductor_id, admin_url, installed_app_id)` on success, or a
/// pre-built error response on failure. Used from two paths in
/// `handle_hc_connect`:
/// 1. The unknown-agent path (agent never seen by this doorway before)
/// 2. The stale-mapping path (agent in MongoDB references a conductor_id
///    that is no longer in the current pool)
///
/// The provisioner walks every current conductor looking for an existing
/// app for this user (deterministic app_id) before installing a new one,
/// so calling this for a stale mapping naturally re-binds the agent.
// Response<Full<Bytes>> is the crate-wide HTTP-error-as-Err convention (see
// e.g. the sibling `#[allow]` on `require_admin` in routes/admin_users.rs);
// shrinking it here would ripple into every caller's `Err(resp) => return resp`.
#[allow(clippy::result_large_err)]
async fn auto_provision(
    state: &Arc<AppState>,
    registry: &Arc<crate::conductor::ConductorRegistry>,
    claims: &crate::auth::jwt::Claims,
) -> Result<(String, String, String), Response<Full<Bytes>>> {
    // Guard: never silently fork a hosted identity for a human whose token
    // was minted by a sibling doorway. See the module comment above.
    if claims_are_foreign(
        claims.doorway_id.as_deref(),
        state.args.doorway_id.as_deref(),
    ) {
        warn!(
            identifier = %claims.identifier,
            claims_doorway = ?claims.doorway_id,
            self_doorway = ?state.args.doorway_id,
            "Refusing auto-provision: token was minted by a foreign doorway"
        );
        return Err(hosted_elsewhere_response(claims));
    }

    let provisioner = AgentProvisioner::new(Arc::clone(registry))
        .with_app_id(state.args.installed_app_id.clone())
        .with_bundle_path(state.args.happ_bundle_path.clone());

    let provisioned = match provisioner.provision_agent(&claims.identifier).await {
        Ok(p) => p,
        Err(e) => {
            error!("Chaperone auto-provision failed: {}", e);
            return Err(sanitize_client_error(
                StatusCode::SERVICE_UNAVAILABLE,
                "Auto-provision",
            ));
        }
    };

    let info = match registry.get_conductor_info(&provisioned.conductor_id) {
        Some(i) => i,
        None => {
            return Err(json_error(
                StatusCode::BAD_GATEWAY,
                "Provisioned conductor info not found",
            ));
        }
    };

    // Also register the JWT's agent_pub_key so Path 2 succeeds on future
    // connects without re-walking every conductor. The provisioner registers
    // the conductor-generated key; the JWT carries the auth-system key —
    // both need to resolve to the same conductor.
    if claims.agent_pub_key != provisioned.agent_pub_key {
        let _ = registry
            .register_agent(
                &claims.agent_pub_key,
                &provisioned.conductor_id,
                &provisioned.installed_app_id,
            )
            .await;
    }

    // T2.2 Part B: record the hosted-at binding on the DHT so a SIBLING doorway
    // can resolve this human's home from substrate truth.
    //
    // FAIL-SOFT BY DESIGN: the binding is a resolution optimization. Its absence
    // degrades to today's behavior (the honest 409 from the guard above), so a
    // write failure logs a warning and never fails a provision that otherwise
    // succeeded. It is written AFTER the provision, not before.
    write_hosted_binding_best_effort(
        state,
        &info.admin_url,
        &info.conductor_url,
        &provisioned.installed_app_id,
    )
    .await;

    Ok((
        provisioned.conductor_id,
        info.admin_url,
        provisioned.installed_app_id,
    ))
}

/// Write the imagodei `hosted-at` binding as the user's delegate.
///
/// "As the user's delegate" is literal: a `ZomeCaller` scoped to the user's own
/// `installed_app_id` authorizes signing credentials for the user's cells and
/// issues the call through them, so `agent_info()` inside the coordinator is the
/// USER's agent key — never the doorway's. There is no third-party write path;
/// an agent can only ever bind itself.
///
/// Never returns an error: see the fail-soft note at the call site.
async fn write_hosted_binding_best_effort(
    state: &Arc<AppState>,
    admin_url: &str,
    app_url: &str,
    installed_app_id: &str,
) {
    let (Some(doorway_id), Some(doorway_url)) = (&state.args.doorway_id, &state.args.doorway_url)
    else {
        debug!("Hosted-binding write skipped: doorway_id/doorway_url not configured");
        return;
    };
    let Some(sanitized_url) = sanitize_home_doorway_url(doorway_url) else {
        warn!(
            configured = %doorway_url,
            "Hosted-binding write skipped: DOORWAY_URL is not an absolute http(s) URL"
        );
        return;
    };

    let caller = crate::services::ZomeCaller::new(admin_url, app_url, installed_app_id);

    #[derive(Serialize)]
    #[serde(rename_all = "camelCase")]
    struct CreateHostedAgentBindingInput<'a> {
        doorway_id: &'a str,
        doorway_url: &'a str,
        installed_app_id: &'a str,
    }

    let input = CreateHostedAgentBindingInput {
        doorway_id,
        doorway_url: &sanitized_url,
        installed_app_id,
    };

    match caller
        .call::<_, serde_json::Value>(
            "imagodei",
            "imagodei",
            "create_hosted_agent_binding",
            &input,
        )
        .await
    {
        Ok(_) => info!(
            app = %installed_app_id,
            doorway = %doorway_id,
            "Recorded hosted-at binding on the DHT"
        ),
        Err(e) => warn!(
            app = %installed_app_id,
            error = %e,
            "Hosted-binding write failed (fail-soft — provision stands; sibling \
             resolution degrades to the honest 409)"
        ),
    }
}

/// Sanitize internal error details for client-facing responses.
/// Full errors are already logged server-side via `error!()` / `warn!()`.
fn sanitize_client_error(status: StatusCode, operation: &str) -> Response<Full<Bytes>> {
    let message = match status {
        StatusCode::BAD_GATEWAY => format!("{operation}: service temporarily unavailable"),
        StatusCode::SERVICE_UNAVAILABLE => "Service temporarily unavailable".to_string(),
        _ => format!("{operation} failed"),
    };
    json_error(status, &message)
}

fn json_error(status: StatusCode, message: &str) -> Response<Full<Bytes>> {
    let body = serde_json::json!({ "error": message });
    Response::builder()
        .status(status)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body.to_string())))
        .unwrap()
}

fn json_success<T: Serialize>(status: StatusCode, data: &T) -> Response<Full<Bytes>> {
    let body =
        serde_json::to_string(data).unwrap_or_else(|_| r#"{"error":"serialization"}"#.into());
    Response::builder()
        .status(status)
        .header("Content-Type", "application/json")
        .body(Full::new(Bytes::from(body)))
        .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::jwt::Claims;
    use crate::auth::PermissionLevel;
    use crate::conductor::registry::{ConductorInfo, ConductorRegistry};
    use crate::config::Args;
    use clap::Parser;

    /// Minimal Claims fixture. `doorway_id`/`doorway_url` are the only fields
    /// the foreign-doorway guard inspects.
    fn test_claims(doorway_id: Option<&str>, doorway_url: Option<&str>) -> Claims {
        Claims {
            human_id: "human-1".into(),
            agent_pub_key: "uhCAk-test".into(),
            identifier: "test@example.com".into(),
            permission_level: PermissionLevel::Authenticated,
            doorway_operator: None,
            session_id: None,
            doorway_id: doorway_id.map(str::to_string),
            doorway_url: doorway_url.map(str::to_string),
            conductor_id: None,
            installed_app_id: None,
            is_steward: false,
            has_local_conductor: false,
            version: 1,
            iat: 0,
            exp: u64::MAX,
        }
    }

    /// AppState carrying `self_doorway_id` as its own `DOORWAY_ID` and the
    /// given (possibly empty) conductor registry.
    fn test_state(self_doorway_id: Option<&str>, registry: ConductorRegistry) -> Arc<AppState> {
        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = self_doorway_id.map(str::to_string);
        let mut state = AppState::new(args);
        state.conductor_registry = Some(Arc::new(registry));
        Arc::new(state)
    }

    async fn body_json(resp: Response<Full<Bytes>>) -> serde_json::Value {
        let bytes = resp.into_body().collect().await.unwrap().to_bytes();
        serde_json::from_slice(&bytes).expect("response body must be JSON")
    }

    // ---- claims_are_foreign (pure classification) ----

    #[test]
    fn claims_are_foreign_treats_missing_and_empty_as_local() {
        assert!(!claims_are_foreign(None, Some("self-doorway")));
        assert!(!claims_are_foreign(Some(""), Some("self-doorway")));
    }

    #[test]
    fn claims_are_foreign_treats_self_id_as_local() {
        assert!(!claims_are_foreign(
            Some("self-doorway"),
            Some("self-doorway")
        ));
    }

    #[test]
    fn claims_are_foreign_flags_sibling_id() {
        assert!(claims_are_foreign(
            Some("sibling-doorway"),
            Some("self-doorway")
        ));
    }

    // ---- auto_provision guard (Task 2.3: kill the silent identity fork) ----

    /// Foreign `doorway_id` + unknown user (no agent→conductor mapping) must
    /// be refused with 409 hosted-elsewhere — never silently provisioned.
    /// A conductor IS registered here: if the guard did not fire first, the
    /// call would fall through to `provisioner.provision_agent`, which (with
    /// no live conductor to actually connect to) would eventually surface as
    /// 503, never 409. Getting 409 proves the guard short-circuited before
    /// the provisioner was ever invoked.
    /// A wrong-length `signingKey` must be a 400, not a panicked tokio worker.
    ///
    /// `AgentPubKey::from_raw_39` (reached from `grant_zome_call_capability`)
    /// `unwrap()`s a `BadSize`, so before the boundary check ANY authenticated
    /// caller could kill a doorway worker mid-request with a short key. Found by
    /// running the real chaperone against the local stack with a 32-byte key.
    #[test]
    fn signing_key_length_is_validated_at_the_boundary() {
        use base64::Engine as _;
        const AGENT_PUB_KEY_RAW_LEN: usize = 39;

        // What the browser actually sends: a 39-byte raw AgentPubKey.
        let valid = BASE64.encode(vec![0u8; AGENT_PUB_KEY_RAW_LEN]);
        let decoded = BASE64.decode(&valid).expect("valid base64");
        assert_eq!(decoded.len(), AGENT_PUB_KEY_RAW_LEN);

        // The shapes that used to panic downstream instead of answering 400.
        for bad_len in [0usize, 1, 32, 38, 40, 64] {
            let encoded = BASE64.encode(vec![0u8; bad_len]);
            let decoded = BASE64.decode(&encoded).expect("valid base64");
            assert_ne!(
                decoded.len(),
                AGENT_PUB_KEY_RAW_LEN,
                "a {bad_len}-byte key must be rejected before from_raw_39 sees it"
            );
        }
    }

    #[tokio::test]
    async fn auto_provision_refuses_foreign_doorway_claim() {
        let registry = ConductorRegistry::new(None).await;
        registry.register_conductor(ConductorInfo {
            conductor_id: "conductor-0".into(),
            conductor_url: "ws://c0:4445".into(),
            admin_url: "ws://c0:4444".into(),
            capacity_used: 0,
            capacity_max: 50,
        });
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("sibling-doorway"), Some("https://sibling.elohim.host"));

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("foreign-doorway claim must be refused, not provisioned");
        assert_eq!(resp.status(), StatusCode::CONFLICT);
        let body = body_json(resp).await;
        assert_eq!(body["error"], "hosted-elsewhere");
        assert_eq!(body["homeDoorway"], "https://sibling.elohim.host");
    }

    /// Local `doorway_id` + unknown agent must still reach the pre-existing
    /// provisioning path. No conductors are registered, so a request that
    /// gets past the guard hits the original "no conductors available"
    /// error (503) — proving the new guard did not block a local claim.
    #[tokio::test]
    async fn auto_provision_proceeds_for_local_doorway_claim() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("self-doorway"), None);

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("no conductors registered");
        assert_eq!(resp.status(), StatusCode::SERVICE_UNAVAILABLE);
    }

    /// Legacy tokens minted before `doorway_id` existed on Claims carry
    /// `None`; tokens minted with an explicitly empty string must be treated
    /// the same way — local, not foreign.
    #[tokio::test]
    async fn auto_provision_treats_empty_doorway_id_as_local() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some(""), None);

        let result =
            auto_provision(&state, state.conductor_registry.as_ref().unwrap(), &claims).await;

        let resp = result.expect_err("no conductors registered");
        assert_eq!(resp.status(), StatusCode::SERVICE_UNAVAILABLE);
    }

    // ---- unknown_conductor_response (the conductor-pinned 502 vs 409 split) ----

    /// A JWT pinning a `conductor_id` this doorway has never heard of, minted
    /// by a sibling doorway, means the user is hosted elsewhere — 409, not
    /// the misleading "Conductor not found in registry" 502.
    #[test]
    fn unknown_conductor_with_foreign_doorway_is_409_hosted_elsewhere() {
        let claims = test_claims(Some("sibling-doorway"), Some("https://sibling.elohim.host"));
        let resp = unknown_conductor_response(&claims, Some("self-doorway"), "conductor-9");
        assert_eq!(resp.status(), StatusCode::CONFLICT);
    }

    /// A JWT pinning an unknown `conductor_id` minted by THIS doorway is a
    /// real registry problem (e.g. pool composition changed) — stays 502.
    #[test]
    fn unknown_conductor_with_local_doorway_stays_502() {
        let claims = test_claims(Some("self-doorway"), None);
        let resp = unknown_conductor_response(&claims, Some("self-doorway"), "conductor-9");
        assert_eq!(resp.status(), StatusCode::BAD_GATEWAY);
    }

    /// Captures the stale-agent-mapping bug class that previously surfaced
    /// as `502 {"error":"Conductor info not found"}` from `/hc/connect`.
    ///
    /// The agent→conductor map persists across doorway restarts (MongoDB
    /// `conductor_registry`), but the conductor map is in-memory only and
    /// is rebuilt from `CONDUCTOR_URLS` each boot. When pool composition
    /// changes (reorder, count change, host rename), persisted rows can
    /// reference conductor_ids that no longer exist in the pool.
    ///
    /// `handle_hc_connect` detects this (Path 2 `get_conductor_info`
    /// returns `None`), unregisters the stale local entry, then calls
    /// `auto_provision`. The provisioner is idempotent — it walks every
    /// current conductor for an existing app for this user and re-binds.
    /// This test exercises the registry-level shape of that recovery.
    #[tokio::test]
    async fn stale_agent_mapping_recovers_via_unregister_and_re_register() {
        let registry = ConductorRegistry::new(None).await;

        // Boot 1 (simulated): pool had a conductor-3; user was assigned to it.
        registry
            .register_agent("uhCAk_user_a", "conductor-3", "elohim-conductor-3-abc123")
            .await
            .unwrap();

        // Boot 2: pool now has only conductor-0; conductor-3 is gone.
        registry.register_conductor(ConductorInfo {
            conductor_id: "conductor-0".to_string(),
            conductor_url: "ws://c0:4445".to_string(),
            admin_url: "ws://c0:4444".to_string(),
            capacity_used: 0,
            capacity_max: 50,
        });

        // Bug shape: agent lookup succeeds but conductor lookup fails.
        let entry = registry.get_conductor_for_agent("uhCAk_user_a").unwrap();
        assert_eq!(entry.conductor_id, "conductor-3");
        assert!(
            registry.get_conductor_info(&entry.conductor_id).is_none(),
            "stale conductor_id should not resolve in current pool"
        );

        // Recovery shape that handle_hc_connect now performs on this case.
        registry.unregister_agent("uhCAk_user_a");
        assert!(
            registry.get_conductor_for_agent("uhCAk_user_a").is_none(),
            "stale entry must be cleared before re-provision"
        );

        // auto_provision (mocked here at the registry layer) picks a current
        // conductor and re-registers the JWT's agent_pub_key.
        registry
            .register_agent("uhCAk_user_a", "conductor-0", "elohim-conductor-0-xyz789")
            .await
            .unwrap();

        let recovered = registry.get_conductor_for_agent("uhCAk_user_a").unwrap();
        assert_eq!(recovered.conductor_id, "conductor-0");
        assert!(
            registry
                .get_conductor_info(&recovered.conductor_id)
                .is_some(),
            "recovered mapping must reach a current conductor"
        );
    }

    // ================================================================
    // T2.2 — honest cross-doorway landing (307 / 409 / open-redirect guard)
    // ================================================================

    // ---- sanitize_home_doorway_url (the open-redirect guard) ----

    #[test]
    fn sanitize_accepts_plain_absolute_urls() {
        assert_eq!(
            sanitize_home_doorway_url("https://elohim.host"),
            Some("https://elohim.host".to_string())
        );
        assert_eq!(
            sanitize_home_doorway_url("https://doorway-alpha.elohim.host/"),
            Some("https://doorway-alpha.elohim.host".to_string())
        );
        assert_eq!(
            sanitize_home_doorway_url("  http://localhost:8888  "),
            Some("http://localhost:8888".to_string())
        );
    }

    #[test]
    fn sanitize_rejects_open_redirect_shapes() {
        // Scheme-relative — a browser would follow this to evil.example.
        assert_eq!(sanitize_home_doorway_url("//evil.example"), None);
        // Bare path / relative.
        assert_eq!(sanitize_home_doorway_url("/hc/connect"), None);
        assert_eq!(sanitize_home_doorway_url("elohim.host"), None);
        // Non-http schemes.
        assert_eq!(sanitize_home_doorway_url("javascript:alert(1)"), None);
        assert_eq!(sanitize_home_doorway_url("file:///etc/passwd"), None);
        // Userinfo look-alike host.
        assert_eq!(
            sanitize_home_doorway_url("https://elohim.host@evil.example"),
            None
        );
        // Header-injection / control characters.
        assert_eq!(
            sanitize_home_doorway_url("https://elohim.host\r\nX-Evil: 1"),
            None
        );
        // Empty authority.
        assert_eq!(sanitize_home_doorway_url("https://"), None);
        assert_eq!(sanitize_home_doorway_url("https:///path"), None);
        assert_eq!(sanitize_home_doorway_url(""), None);
    }

    // ---- hosted_at_redirect_response ----

    #[test]
    fn redirect_is_307_with_location_and_hosted_at_header() {
        let resp = hosted_at_redirect_response("https://elohim.host", "/hc/connect");
        assert_eq!(resp.status(), StatusCode::TEMPORARY_REDIRECT);
        assert_eq!(
            resp.headers()
                .get(hyper::header::LOCATION)
                .and_then(|v| v.to_str().ok()),
            Some("https://elohim.host/hc/connect"),
            "307 (not 302) so the POST body + method are replayed at the home doorway"
        );
        assert_eq!(
            resp.headers()
                .get(HOSTED_AT_HEADER)
                .and_then(|v| v.to_str().ok()),
            Some("https://elohim.host")
        );
    }

    /// OPEN-REDIRECT GUARD: the Location HOST is always the verified home
    /// doorway. A path that tries to smuggle an authority contributes only a
    /// path segment; it can never replace the host.
    #[test]
    fn redirect_host_never_comes_from_request_path() {
        let resp = hosted_at_redirect_response("https://elohim.host", "//evil.example/steal");
        let location = resp
            .headers()
            .get(hyper::header::LOCATION)
            .and_then(|v| v.to_str().ok())
            .unwrap()
            .to_string();
        assert!(
            location.starts_with("https://elohim.host/"),
            "Location must stay anchored to the verified home doorway, got {location}"
        );

        // A non-absolute path degrades to "/" rather than being concatenated raw.
        let resp2 = hosted_at_redirect_response("https://elohim.host", "evil.example");
        assert_eq!(
            resp2
                .headers()
                .get(hyper::header::LOCATION)
                .and_then(|v| v.to_str().ok()),
            Some("https://elohim.host/")
        );
    }

    // ---- resolve_home_doorway ----

    /// The verified token's own `doorway_url` claim is the primary source —
    /// it is inside the signature-verified token, so it is already trusted.
    #[tokio::test]
    async fn resolve_home_doorway_prefers_the_verified_claim() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("sibling-doorway"), Some("https://elohim.host/"));

        assert_eq!(
            resolve_home_doorway(&state, &claims).await,
            Some("https://elohim.host".to_string())
        );
    }

    /// A malformed `doorway_url` claim must NOT be redirected to. With no
    /// storage projection configured, this is unresolvable → the caller's 409.
    #[tokio::test]
    async fn resolve_home_doorway_rejects_a_malformed_claim() {
        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = Some("self-doorway".into());
        args.storage_url = None; // no projection fallback available
        let state = Arc::new(AppState::new(args));
        let claims = test_claims(Some("sibling-doorway"), Some("//evil.example"));

        assert_eq!(resolve_home_doorway(&state, &claims).await, None);
    }

    /// Legacy token: `doorway_id` present, no `doorway_url`, and no storage
    /// URL configured → unresolvable, which the Chaperone answers with the
    /// existing honest 409 rather than guessing a redirect target.
    #[tokio::test]
    async fn resolve_home_doorway_is_none_without_claim_or_projection() {
        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = Some("self-doorway".into());
        args.storage_url = None;
        let state = Arc::new(AppState::new(args));
        let claims = test_claims(Some("sibling-doorway"), None);

        assert_eq!(resolve_home_doorway(&state, &claims).await, None);
        // …and that unresolvable case is the 409 contract, reusing the SAME
        // builder the Task 2.3 guard uses (never a duplicate).
        let resp = hosted_elsewhere_response(&claims);
        assert_eq!(resp.status(), StatusCode::CONFLICT);
    }

    // ---- T2.1 live-wiring smoke ----

    /// The validator built on the LIVE path (`AppState::federation_jwt_validator`)
    /// must still verify a self-minted token. This is the wiring smoke test:
    /// every Task 2.1 builder method is opt-in, so attaching them must not
    /// change self-token behaviour.
    #[test]
    fn federation_validator_verifies_a_self_minted_token() {
        use crate::auth::TokenInput;

        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = Some("self-doorway".into());
        let state = Arc::new(AppState::new(args));

        let validator = state
            .federation_jwt_validator()
            .expect("dev-mode validator must build on the live path");

        let token = validator
            .generate_token(TokenInput {
                human_id: "human-1".into(),
                agent_pub_key: "uhCAk-test".into(),
                identifier: "test@example.com".into(),
                permission_level: PermissionLevel::Authenticated,
                session_id: None,
                doorway_id: Some("self-doorway".into()),
                doorway_url: Some("https://self.elohim.host".into()),
                conductor_id: None,
                installed_app_id: None,
                is_steward: false,
                has_local_conductor: false,
            })
            .expect("mint");

        let claims = validator
            .verify_token_detailed(&token)
            .expect("self-minted token must verify through the live validator");
        assert_eq!(claims.doorway_id.as_deref(), Some("self-doorway"));
        assert!(
            !claims_are_foreign(claims.doorway_id.as_deref(), Some("self-doorway")),
            "a self-minted token must never be classified foreign"
        );
    }

    // ---- the Chaperone's cross-doorway decision, composed ----
    //
    // `handle_hc_connect` takes `Request<hyper::body::Incoming>`, which cannot
    // be constructed in a unit test (`Incoming` has no public constructor), so
    // these tests exercise the EXACT composition its step-1b branch performs:
    //   claims_are_foreign → resolve_home_doorway → 307 | hosted_elsewhere 409.
    // Every part is independently tested above; this pins how they combine.

    async fn chaperone_foreign_decision(
        state: &Arc<AppState>,
        claims: &Claims,
        original_path: &str,
    ) -> Response<Full<Bytes>> {
        assert!(
            claims_are_foreign(
                claims.doorway_id.as_deref(),
                state.args.doorway_id.as_deref()
            ),
            "precondition: these claims must classify as foreign"
        );
        match resolve_home_doorway(state, claims).await {
            Some(home) => hosted_at_redirect_response(&home, original_path),
            None => hosted_elsewhere_response(claims),
        }
    }

    /// A VERIFIED foreign token carrying `doorway_url` → 307 to the home
    /// doorway, `X-Elohim-Hosted-At` set. Never a 502, never a re-provision.
    #[tokio::test]
    async fn verified_foreign_token_with_doorway_url_redirects_307() {
        let registry = ConductorRegistry::new(None).await;
        let state = test_state(Some("self-doorway"), registry);
        let claims = test_claims(Some("sibling-doorway"), Some("https://elohim.host"));

        let resp = chaperone_foreign_decision(&state, &claims, "/hc/connect").await;

        assert_eq!(resp.status(), StatusCode::TEMPORARY_REDIRECT);
        assert_eq!(
            resp.headers()
                .get(hyper::header::LOCATION)
                .and_then(|v| v.to_str().ok()),
            Some("https://elohim.host/hc/connect")
        );
        assert_eq!(
            resp.headers()
                .get(HOSTED_AT_HEADER)
                .and_then(|v| v.to_str().ok()),
            Some("https://elohim.host")
        );
    }

    /// A VERIFIED foreign token whose home is UNRESOLVABLE (no `doorway_url`
    /// claim, no projection reachable) → the existing honest 409, reusing
    /// `hosted_elsewhere_response` rather than a duplicate builder.
    #[tokio::test]
    async fn verified_foreign_token_unresolvable_falls_back_to_409() {
        let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
        args.dev_mode = true;
        args.doorway_id = Some("self-doorway".into());
        args.storage_url = None;
        let state = Arc::new(AppState::new(args));
        let claims = test_claims(Some("sibling-doorway"), None);

        let resp = chaperone_foreign_decision(&state, &claims, "/hc/connect").await;

        assert_eq!(resp.status(), StatusCode::CONFLICT);
        assert!(
            resp.headers().get(hyper::header::LOCATION).is_none(),
            "an unresolvable home must never carry a Location header"
        );
        let body = body_json(resp).await;
        assert_eq!(body["error"], "hosted-elsewhere");
    }

    /// OPEN-REDIRECT GUARD, end to end: a foreign token whose `doorway_url`
    /// claim is an attacker-shaped URL must NOT produce a redirect at all —
    /// it degrades to the 409. The Location header is never derived from an
    /// unsanitized value.
    #[tokio::test]
    async fn verified_foreign_token_with_hostile_claim_never_redirects() {
        for hostile in [
            "//evil.example",
            "javascript:alert(1)",
            "https://elohim.host@evil.example",
            "/relative/path",
        ] {
            let mut args = Args::parse_from(["doorway", "--listen", "127.0.0.1:0"]);
            args.dev_mode = true;
            args.doorway_id = Some("self-doorway".into());
            args.storage_url = None;
            let state = Arc::new(AppState::new(args));
            let claims = test_claims(Some("sibling-doorway"), Some(hostile));

            let resp = chaperone_foreign_decision(&state, &claims, "/hc/connect").await;
            assert_eq!(
                resp.status(),
                StatusCode::CONFLICT,
                "hostile doorway_url {hostile:?} must degrade to 409, not redirect"
            );
            assert!(
                resp.headers().get(hyper::header::LOCATION).is_none(),
                "hostile doorway_url {hostile:?} produced a Location header"
            );
        }
    }
}
