[package]
name = "mishpat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "mishpat"

[dependencies]
hdk.workspace = true
holochain_serialized_bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
mishpat_integrity = { path = "../mishpat_integrity" }
qahal-types = { path = "../../../../../sdk/domains/qahal/types" }
