// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Challenge } from "./Challenge";

/**
 * Output from mishpat::create_challenge coordinator function.
 */
export type ChallengeOutput = { action_hash: string, challenge: Challenge, };
