// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Challenge fields.
 *
 * Matches the integrity zome's Challenge entry type field-for-field.
 * The integrity zome wraps this with `#[hdk_entry_helper]` for DHT storage;
 * this version uses plain serde for wire format compatibility.
 */
export type Challenge = { id: string, entity_type: string, entity_id: string, challenger_id: string, challenger_name: string, challenger_standing: string, grounds: string, description: string, evidence_json: string, status: string, filed_at: string, acknowledged_at: string | null, sla_deadline: string | null, assigned_elohim: string | null, priority: string, resolution_json: string | null, created_at: string, updated_at: string, metadata_json: string, };
