// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ChallengeOutcome wire type. Field-for-field mirror of the integrity entry.
 */
export type ChallengeOutcome = { outcome_id: string, challenge_cid: string, verdict: string, reviewer_consensus: string, reasoning_json: string, decided_at: string, indemnification_actions_json: string, };
