// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChallengeOutcome } from "./ChallengeOutcome";

/**
 * Output from mishpat::create_challenge_outcome coordinator function.
 */
export type ChallengeOutcomeOutput = { action_hash: string, outcome: ChallengeOutcome, };
