// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_statement_vote coordinator function.
 */
export type CreateStatementVoteInput = { id: string | null, statement_id: string, voter_id: string, vote: string, metadata_json: string, };
