// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_precedent coordinator function.
 */
export type CreatePrecedentInput = { id: string | null, title: string, summary: string, full_reasoning: string, binding: string, scope_json: string, established_by: string, status: string, superseded_by: string | null, metadata_json: string, };
