// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_proposal coordinator function.
 */
export type CreateProposalInput = { id: string | null, title: string, proposal_type: string, description: string, proposer_id: string, proposer_name: string, rationale: string, status: string, phase: string, amendments_json: string, voting_config_json: string, current_votes_json: string, outcome_json: string | null, related_entity_type: string | null, related_entity_id: string | null, metadata_json: string, };
