// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_challenge_outcome coordinator function.
 *
 * ChallengeOutcome records the reviewer consensus verdict closing a
 * GateDecisionChallenge. Indemnification actions are carried as JSON to
 * keep the integrity entry shape flat; richer typed shape is future work.
 */
export type CreateChallengeOutcomeInput = { 
/**
 * CID of this outcome (self-addressing).
 */
outcome_id: string, 
/**
 * CID of the GateDecisionChallenge this outcome closes.
 */
challenge_cid: string, 
/**
 * Verdict: upheld | dismissed | superseded
 */
verdict: string, 
/**
 * AgentPubKeys of the reviewers who reached consensus (comma-separated, base64).
 */
reviewer_consensus: string, 
/**
 * Full ConstitutionalReasoning as JSON.
 */
reasoning_json: string, 
/**
 * ISO-8601 timestamp of decision.
 */
decided_at: string, 
/**
 * Indemnification actions as JSON array (empty if no action required).
 */
indemnification_actions_json: string, };
