// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_proposal_vote coordinator function.
 */
export type CreateProposalVoteInput = { id: string | null, proposal_id: string, voter_id: string, voter_name: string, position: string, reasoning: string | null, version: number, previous_position: string | null, metadata_json: string, };
