// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::set_governance_state coordinator function.
 */
export type CreateGovernanceStateInput = { id: string | null, entity_type: string, entity_id: string, status: string, status_basis_json: string, labels_json: string, active_challenges_json: string, active_proposals_json: string, precedent_ids_json: string, metadata_json: string, };
