// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_opinion_statement coordinator function.
 */
export type CreateOpinionStatementInput = { id: string | null, context_id: string, author_id: string, text: string, status: string, metadata_json: string, };
