// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_challenge coordinator function.
 */
export type CreateChallengeInput = { id: string | null, entity_type: string, entity_id: string, challenger_id: string, challenger_name: string, challenger_standing: string, grounds: string, description: string, evidence_json: string, status: string, priority: string, sla_deadline: string | null, assigned_elohim: string | null, resolution_json: string | null, metadata_json: string, };
