// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_graduated_feedback coordinator function.
 */
export type CreateGraduatedFeedbackInput = { id: string | null, content_id: string, content_type: string, responder_id: string, feedback_context: string, position: number, intensity: number, reasoning: string | null, metadata_json: string, };
