// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_discussion coordinator function.
 */
export type CreateDiscussionInput = { id: string | null, entity_type: string, entity_id: string, category: string, title: string, messages_json: string, status: string, metadata_json: string, };
