// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_gate_decision_attestation coordinator function.
 *
 * All fields are flat Strings — no AgentPubKey or specific types — to avoid
 * HDK version drift concerns when this crate is consumed from native targets.
 */
export type CreateGateDecisionAttestationInput = { 
/**
 * CID of this attestation (self-addressing, computed by caller from content hash).
 */
decision_id: string, 
/**
 * Phase discriminator: "dev-context" | "elohim-active"
 */
phase: string, 
/**
 * AgentPubKey of the elohim that made the decision (base64 encoded).
 */
elohim_id: string, 
/**
 * CID of the elohim's substance declaration (model-weights + constitution + deployment-context).
 */
elohim_substance_cid: string, 
/**
 * Name of the gate that produced this decision (e.g. "discernment-gate-v1-mechanical").
 */
gate_name: string, 
/**
 * CID of the GateProcessDeclaration DAG that was executed.
 */
gate_process_cid: string, 
/**
 * Serialized RequestRef — identifies the RelationalImpactEvent that triggered the gate.
 */
request_ref_json: string, 
/**
 * Serialized GateStatus: "allow" | "decline" | "escalate" | "verdict"
 */
decision: string, 
/**
 * Full ConstitutionalReasoning as JSON.
 */
reasoning_json: string, 
/**
 * CID of the assembled GateContext summary (privacy-respecting snapshot).
 */
context_summary_cid: string, 
/**
 * ISO-8601 timestamp of the decision.
 */
decided_at: string, 
/**
 * CID of the universal-band DAG declaration that ran above the domain gate.
 */
universal_band_cid: string, };
