// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_governance_reaction coordinator function.
 */
export type CreateGovernanceReactionInput = { id: string | null, content_id: string, content_type: string, reactor_id: string, reaction: string, intensity: number, mediated: boolean, mediation_accepted: boolean, context_json: string, metadata_json: string, };
