// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for mishpat::create_gate_decision_challenge coordinator function.
 *
 * A GateDecisionChallenge is a formal challenge filed against a prior
 * GateDecisionAttestation. Per the Challenge + Indemnification spec
 * (genesis/docs/superpowers/specs/2026-04-19-gate-challenge-and-indemnification-design.md).
 */
export type CreateGateDecisionChallengeInput = { 
/**
 * CID of this challenge (self-addressing, computed by caller from content hash).
 */
challenge_id: string, 
/**
 * CID of the GateDecisionAttestation being challenged.
 */
challenged_decision_cid: string, 
/**
 * AgentPubKey of the challenger (base64 encoded).
 */
challenger_id: string, 
/**
 * Grounds: factual-error | safety | policy | constitutional | indemnification-request
 */
grounds: string, 
/**
 * Challenger's articulation of the grievance.
 */
summary: string, 
/**
 * Content-addressed evidence refs (comma-separated CIDs; empty if none).
 */
evidence_refs: string, 
/**
 * ISO-8601 timestamp of filing.
 */
filed_at: string, 
/**
 * Reach level: self | intimate | community | commons
 */
reach: string, };
