// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerificationStatus } from "./VerificationStatus";

/**
 * Result of verifying a single credential against the DHT.
 */
export type CredentialVerification = { hash: string, status: VerificationStatus, entry_type: string | null, agent: string | null, };
