// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discussion fields.
 *
 * Matches the integrity zome's Discussion entry type field-for-field.
 */
export type Discussion = { id: string, entity_type: string, entity_id: string, category: string, title: string, messages_json: string, status: string, message_count: number, last_activity_at: string, created_at: string, updated_at: string, metadata_json: string, };
