// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Discussion } from "./Discussion";

/**
 * Output from mishpat::create_discussion coordinator function.
 */
export type DiscussionOutput = { action_hash: string, discussion: Discussion, };
