// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GateDecisionAttestation wire type.
 *
 * Matches the integrity zome's GateDecisionAttestation entry type field-for-field.
 */
export type GateDecisionAttestation = { decision_id: string, phase: string, elohim_id: string, elohim_substance_cid: string, gate_name: string, gate_process_cid: string, request_ref_json: string, decision: string, reasoning_json: string, context_summary_cid: string, decided_at: string, universal_band_cid: string, };
