// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecisionChallenge } from "./GateDecisionChallenge";

/**
 * Output from mishpat::create_gate_decision_challenge coordinator function.
 */
export type GateDecisionChallengeOutput = { action_hash: string, challenge: GateDecisionChallenge, };
