// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GateDecisionChallenge wire type. Field-for-field mirror of the integrity entry.
 */
export type GateDecisionChallenge = { challenge_id: string, challenged_decision_cid: string, challenger_id: string, grounds: string, summary: string, evidence_refs: string, filed_at: string, reach: string, };
