// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecisionAttestation } from "./GateDecisionAttestation";

/**
 * Output from mishpat::create_gate_decision_attestation coordinator function.
 */
export type GateDecisionAttestationOutput = { action_hash: string, attestation: GateDecisionAttestation, };
