// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for getting governance state by entity.
 */
export type GetGovernanceStateInput = { entity_type: string, entity_id: string, };
