// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GovernanceState fields.
 *
 * Matches the integrity zome's GovernanceState entry type field-for-field.
 */
export type GovernanceState = { id: string, entity_type: string, entity_id: string, status: string, status_basis_json: string, labels_json: string, active_challenges_json: string, active_proposals_json: string, precedent_ids_json: string, last_updated: string, created_at: string, updated_at: string, metadata_json: string, };
