// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GovernanceReaction fields.
 *
 * Matches the integrity zome's GovernanceReaction entry type field-for-field.
 */
export type GovernanceReaction = { id: string, content_id: string, content_type: string, reactor_id: string, reaction: string, intensity: number, mediated: boolean, mediation_accepted: boolean, context_json: string, created_at: string, updated_at: string, metadata_json: string, };
