// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovernanceState } from "./GovernanceState";

/**
 * Output from mishpat::set_governance_state coordinator function.
 */
export type GovernanceStateOutput = { action_hash: string, governance_state: GovernanceState, };
