// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovernanceReaction } from "./GovernanceReaction";

/**
 * Output from mishpat::create_governance_reaction coordinator function.
 */
export type GovernanceReactionOutput = { action_hash: string, reaction: GovernanceReaction, };
