// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GraduatedFeedback fields.
 *
 * Matches the integrity zome's GraduatedFeedback entry type field-for-field.
 */
export type GraduatedFeedback = { id: string, content_id: string, content_type: string, responder_id: string, feedback_context: string, position: number, intensity: number, reasoning: string | null, updated_count: number, created_at: string, updated_at: string, metadata_json: string, };
