// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraduatedFeedback } from "./GraduatedFeedback";

/**
 * Output from mishpat::create_graduated_feedback coordinator function.
 */
export type GraduatedFeedbackOutput = { action_hash: string, feedback: GraduatedFeedback, };
