// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OpinionStatement fields.
 *
 * Matches the integrity zome's OpinionStatement entry type field-for-field.
 */
export type OpinionStatement = { id: string, context_id: string, author_id: string, text: string, status: string, vote_count: number, agree_count: number, disagree_count: number, pass_count: number, consensus_score: number, cluster_json: string | null, created_at: string, updated_at: string, metadata_json: string, };
