// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpinionStatement } from "./OpinionStatement";

/**
 * Output from mishpat::create_opinion_statement coordinator function.
 */
export type OpinionStatementOutput = { action_hash: string, statement: OpinionStatement, };
