// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Precedent fields.
 *
 * Matches the integrity zome's Precedent entry type field-for-field.
 */
export type Precedent = { id: string, title: string, summary: string, full_reasoning: string, binding: string, scope_json: string, citations: number, status: string, established_by: string, established_at: string, superseded_by: string | null, created_at: string, updated_at: string, metadata_json: string, };
