// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Precedent } from "./Precedent";

/**
 * Output from mishpat::create_precedent coordinator function.
 */
export type PrecedentOutput = { action_hash: string, precedent: Precedent, };
