// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalVote } from "./ProposalVote";

/**
 * Output from mishpat::create_proposal_vote coordinator function.
 */
export type ProposalVoteOutput = { action_hash: string, vote: ProposalVote, };
