// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ProposalVote fields.
 *
 * Matches the integrity zome's ProposalVote entry type field-for-field.
 */
export type ProposalVote = { id: string, proposal_id: string, voter_id: string, voter_name: string, position: string, reasoning: string | null, version: number, previous_position: string | null, created_at: string, updated_at: string, metadata_json: string, };
