// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proposal fields.
 *
 * Matches the integrity zome's Proposal entry type field-for-field.
 */
export type Proposal = { id: string, title: string, proposal_type: string, description: string, proposer_id: string, proposer_name: string, rationale: string, status: string, phase: string, amendments_json: string, voting_config_json: string, current_votes_json: string, outcome_json: string | null, related_entity_type: string | null, related_entity_id: string | null, created_at: string, updated_at: string, metadata_json: string, };
