// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Proposal } from "./Proposal";

/**
 * Output from mishpat::create_proposal coordinator function.
 */
export type ProposalOutput = { action_hash: string, proposal: Proposal, };
