// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying proposals.
 */
export type QueryProposalsInput = { proposal_type: string | null, proposer_id: string | null, status: string | null, limit: number | null, };
