// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying graduated feedback.
 */
export type QueryGraduatedFeedbackInput = { content_id: string | null, responder_id: string | null, feedback_context: string | null, limit: number | null, };
