// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying opinion statements.
 */
export type QueryOpinionStatementsInput = { context_id: string | null, author_id: string | null, limit: number | null, };
