// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying governance states.
 */
export type QueryGovernanceStatesInput = { status: string | null, limit: number | null, };
