// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying challenges.
 */
export type QueryChallengesInput = { entity_type: string | null, entity_id: string | null, challenger_id: string | null, status: string | null, limit: number | null, };
