// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying gate decision challenges.
 */
export type QueryGateChallengesInput = { 
/**
 * When set, filter by challenged_decision_cid (all challenges against a decision).
 */
challenged_decision_cid: string | null, 
/**
 * When set, filter by challenger_id (all challenges by an agent).
 */
challenger_id: string | null, limit: number | null, };
