// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying gate decision attestations.
 */
export type QueryGateDecisionsInput = { elohim_id: string | null, gate_name: string | null, phase: string | null, limit: number | null, };
