// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying statement votes.
 */
export type QueryStatementVotesInput = { statement_id: string | null, voter_id: string | null, limit: number | null, };
