// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying challenge outcomes.
 */
export type QueryChallengeOutcomesInput = { 
/**
 * When set, filter by verdict: upheld | dismissed | superseded.
 */
verdict: string | null, 
/**
 * When set, filter by challenge_cid (returns at most one outcome).
 */
challenge_cid: string | null, limit: number | null, };
