// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying governance reactions.
 */
export type QueryGovernanceReactionsInput = { content_id: string | null, reactor_id: string | null, reaction_type: string | null, limit: number | null, };
