// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying precedents.
 */
export type QueryPrecedentsInput = { status: string | null, binding: string | null, limit: number | null, };
