// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatementVote } from "./StatementVote";

/**
 * Output from mishpat::create_statement_vote coordinator function.
 */
export type StatementVoteOutput = { action_hash: string, statement_vote: StatementVote, };
