// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StatementVote fields.
 *
 * Matches the integrity zome's StatementVote entry type field-for-field.
 */
export type StatementVote = { id: string, statement_id: string, voter_id: string, vote: string, created_at: string, metadata_json: string, };
