// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a verified credential.
 */
export type VerificationStatus = "Valid" | "NotFound" | "Revoked" | "Expired";
