packages:
  - app/elohim-app
  - doorway/doorway-app
  - app/elohim-library
  - app/elohim-library/projects/elohim-service
  - steward/device
  - genesis/seeder
  - genesis/a2o
  - genesis/orchestrator
  - elohim/sdk/storage-client-ts
  - elohim/sdk/epr-ts
  - elohim/elohim-agent/mcp-servers/elohim-content
  - elohim/elohim-agent/elohim-agent-sdk
  - genesis/landing
