packages:
  - app/elohim-app
  - doorway/doorway-app
  - app/elohim-library
  - app/elohim-library/projects/elohim-service
  - app/elohim-elements/elohim-core
  - app/elohim-elements/elohim-shell
  - app/elohim-elements/elohim-imagodei
  - app/elohim-elements/elohim-lamad
  - app/elohim-elements/elohim-shefa
  - app/elohim-elements/elohim-qahal
  - app/elohim-elements/elohim-doorway
  - app/elohim-elements/elohim-avodah
  - steward/device
  - genesis/seeder
  - genesis/a2o
  - genesis/orchestrator
  - elohim/sdk/storage-client-ts
  - elohim/sdk/epr-ts
  - elohim/elohim-agent/mcp-servers/elohim-content
  - elohim/elohim-agent/elohim-agent-sdk
  - genesis/landing
