// @generated automatically by Diesel CLI.
// This file is normally auto-generated by `diesel migration run`.
// Manual maintenance may be required if you edit migrations.

diesel::table! {
    /// Schema version tracking (global, no app_id)
    schema_version (version) {
        version -> Integer,
    }
}

diesel::table! {
    /// App registry for validation and future features
    apps (id) {
        id -> Text,
        name -> Text,
        description -> Nullable<Text>,
        created_at -> Text,
        enabled -> Integer,
    }
}

diesel::table! {
    /// Content metadata table
    content (id) {
        id -> Text,
        app_id -> Text,
        title -> Text,
        description -> Nullable<Text>,
        content_type -> Text,
        content_format -> Text,
        blob_hash -> Nullable<Text>,
        blob_cid -> Nullable<Text>,
        content_size_bytes -> Nullable<BigInt>,
        metadata_json -> Nullable<Text>,
        reach -> Text,
        validation_status -> Text,
        created_by -> Nullable<Text>,
        created_at -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    /// Content tags with app scoping
    content_tags (app_id, content_id, tag) {
        app_id -> Text,
        content_id -> Text,
        tag -> Text,
    }
}

diesel::table! {
    /// Learning paths
    paths (id) {
        id -> Text,
        app_id -> Text,
        title -> Text,
        description -> Nullable<Text>,
        path_type -> Text,
        difficulty -> Nullable<Text>,
        estimated_duration -> Nullable<Text>,
        thumbnail_url -> Nullable<Text>,
        thumbnail_alt -> Nullable<Text>,
        metadata_json -> Nullable<Text>,
        visibility -> Text,
        created_by -> Nullable<Text>,
        created_at -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    /// Path tags with app scoping
    path_tags (app_id, path_id, tag) {
        app_id -> Text,
        path_id -> Text,
        tag -> Text,
    }
}

diesel::table! {
    /// Chapters (optional grouping within paths)
    chapters (id) {
        id -> Text,
        app_id -> Text,
        path_id -> Text,
        title -> Text,
        description -> Nullable<Text>,
        order_index -> Integer,
        estimated_duration -> Nullable<Text>,
    }
}

diesel::table! {
    /// Steps (learning items in a path)
    steps (id) {
        id -> Text,
        app_id -> Text,
        path_id -> Text,
        chapter_id -> Nullable<Text>,
        title -> Text,
        description -> Nullable<Text>,
        step_type -> Text,
        resource_id -> Nullable<Text>,
        resource_type -> Nullable<Text>,
        order_index -> Integer,
        estimated_duration -> Nullable<Text>,
        metadata_json -> Nullable<Text>,
    }
}

diesel::table! {
    /// Attestations granted upon path completion
    path_attestations (app_id, path_id, attestation_type) {
        app_id -> Text,
        path_id -> Text,
        attestation_type -> Text,
        attestation_name -> Text,
    }
}

// Define table relationships for joins
diesel::joinable!(content_tags -> content (content_id));
diesel::joinable!(path_tags -> paths (path_id));
diesel::joinable!(chapters -> paths (path_id));
diesel::joinable!(steps -> paths (path_id));
diesel::joinable!(steps -> chapters (chapter_id));
diesel::joinable!(path_attestations -> paths (path_id));

diesel::allow_tables_to_appear_in_same_query!(
    schema_version,
    apps,
    content,
    content_tags,
    paths,
    path_tags,
    chapters,
    steps,
    path_attestations,
);
