#!/usr/bin/env python3
"""
state-machine-gen.py — generate the doc state-machine's directory gates.

The directory a doc lives in IS its state; a transition is a `git mv` (link-safe via
path-update-apply.py, operator-gated). This script (re)creates the PRESSURE state-dirs
under a single root and writes a CLAUDE.md GATE into each — the harness loads that gate
when an agent works in the dir, making it PAUSE before wasting tokens.

DESIGN INVARIANTS (operator):
  - SHALLOW. Reason lives in each doc's inline <!-- STATE-TAG -->, not in nested dirs
    (no blockers/shem/…). One level under the root.
  - EMPTY = EQUILIBRIUM. A pressure dir holding only its CLAUDE.md means "nothing in
    this problem state" = stable. Anything else = a pressure point.
  - ANTI-PROLIFERATION. One root (_state/), not N new top-level dirs. Add a state = add
    one STATES entry, not a deep tree.

Idempotent: re-run to refresh gates / add states. Creates only dirs + CLAUDE.md (never
moves docs — moving a doc between states is an operator-gated `git mv`).

Run:  python3 .claude/scripts/memory-kit/state-machine-gen.py [ROOT]
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[3]
STATE_ROOT = ROOT / "genesis/docs/_state"
AUDIT = "python3 .claude/scripts/memory-kit/placement-audit.py"

# Add a state here for finer resolution. kind=pressure → must trend EMPTY (equilibrium).
STATES = {
    "blockers": {
        "title": "BLOCKED-BY-ENV",
        "pause": "Everything here is OUT OF SCOPE right now because a required environment "
                 "resource is unavailable (a node/cluster/registry is down). This is **NOT a "
                 "regression** — the work isn't broken, it just can't be validated until the env "
                 "returns. **Do not 'fix' these. Do not spend tokens here** unless you are restoring "
                 "the env itself.",
        "reenable": "Each doc's inline `<!-- STATE-TAG -->` names the missing resource and the line "
                    "in `genesis/manifests/cluster-state.yaml` that re-enables it. Restore the resource, "
                    f"set it `available: true`, run `{AUDIT} --focus`, then `git mv <doc> <destination-dir>` "
                    f"and re-run `{AUDIT} --ledger` to lift the doc out.",
    },
    "regression": {
        "title": "REGRESSION",
        "pause": "Everything here was VERIFIED-STABLE and then BROKE on an available env. **This IS "
                 "the rework queue** — the one pressure dir you SHOULD work in. Pick the oldest, find "
                 "the cause, fix, re-verify.",
        "reenable": "Each doc's inline tag links the failing test / CI run. Fix → re-verify (CI green) → "
                    f"`git mv <doc> <destination-dir>` (back to active or promoted to verified), then "
                    f"re-run `{AUDIT} --ledger`.",
    },
    "unverified": {
        "title": "CLAIMED-ONLY",
        "pause": "Everything here CLAIMS done but has NO verification evidence. **Do not trust these as "
                 "done. Do not build on them** as if shipped. A 'landed' claim is as untrustworthy as a "
                 "checkbox (the iroh gates proved it).",
        "reenable": "Grade it: run ci-investigator / `/verify` (or wire the missing test into CI). Record "
                    "`verification:`/`landed_commit:`. Verified → promote; failed → move to regression.",
    },
    "needs-triage": {
        "title": "NEEDS-TRIAGE (no state)",
        "pause": "Everything here has NO machine-readable status — write-only, un-triaged. **Don't extend "
                 "or design from these blind.** They are the dumping-ground signal. Classify first: give a "
                 "status + a place in the graph (or distill to history if dead).",
        "reenable": "librarian/cartographer assign `status:` + links → the doc moves to its real state. "
                    f"`{AUDIT}` counts this pile; it must trend to 0.",
    },
}

GATE_TEMPLATE = """\
# ⚠ STATE GATE — {title}   (generated by state-machine-gen.py; do not hand-edit)

> **PAUSE before you spend tokens in this directory.**
>
> {pause}

**EQUILIBRIUM = this directory is empty of docs** (only this `CLAUDE.md` remains). If you see entries
below the gate, each one is an open pressure point.

**How a doc leaves this state:** {reenable}

— A doc's *directory is its state*. Moves are `git mv`, link-rewritten by the operator-gated
`path-update-apply.py`. The deterministic state is computed by `placement-audit.py`; the planner's
in-scope surface by `{audit} --focus`.
"""

README = """\
# `_state/` — the doc state-machine (pressure dirs)

The directory a doc lives in IS its lifecycle state; a transition is a `git mv`. These are the
**pressure** states — they exist to be **emptied**. At equilibrium every dir here holds only its
`CLAUDE.md` gate. Resolved work lives in the terminal homes (`../content/elohim-protocol/architecture/`
= canonical, `../content/elohim-protocol/history/` = retired). See `../PLACEMENT.md`.

Add a state = add one entry to `STATES` in `state-machine-gen.py` (anti-proliferation: one root, shallow).
Check health: `python3 .claude/scripts/memory-kit/placement-audit.py` (structural-equilibrium section).
"""


def main() -> int:
    STATE_ROOT.mkdir(parents=True, exist_ok=True)
    (STATE_ROOT / "README.md").write_text(README)
    made = []
    for name, cfg in STATES.items():
        d = STATE_ROOT / name
        d.mkdir(exist_ok=True)
        (d / "CLAUDE.md").write_text(GATE_TEMPLATE.format(
            title=cfg["title"], pause=cfg["pause"], reenable=cfg["reenable"], audit=AUDIT))
        docs = [f for f in d.glob("*.md") if f.name != "CLAUDE.md"]
        made.append((name, len(docs)))
    print(f"state-machine gates written under {STATE_ROOT.relative_to(ROOT)}/")
    for name, n in made:
        flag = "✅ empty (stable)" if n == 0 else f"⚠ {n} docs (pressure)"
        print(f"  {name:<14} {flag}")
    print("\nThese dirs are MEANT to be empty. A `git mv <doc> _state/<state>/` places a doc here on a")
    print("bad-state transition; resolution `git mv`s it out. Run placement-audit.py for the structural verdict.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
