#!/bin/bash
# Peer-executed a2o stage runner. Content-addressed: this file's CID IS the stage.
# Speaks the minimal libtest CLI the pinned rakia executor drives.
# Generated by build-stage-task.mjs — see
# genesis/docs/superpowers/specs/2026-09-08-peer-executed-stage-design.md §6.2.
set -uo pipefail

STAGE_NAME='@@STAGE_NAME@@'                 # federation-version-convergence
REPO='@@REPO_ROOT@@'
FEATURE='@@FEATURE_REL@@'                   # features/dataplane/federation-version-convergence.feature
FEATURE_SHA256='@@FEATURE_SHA256@@'
SUT_EXPECTED='@@SUT@@'                      # requester's computed source-under-test (lib/sut.ts)
TEST_PREFIX='@@TEST_PREFIX@@'               # feedback_signal::a2o::dataplane::federation-version-convergence
SCENARIOS=(@@SCENARIO_SLUGS@@)              # one quoted slug per declared scenario
WRITABLE=(@@WRITABLE_PATHS@@)               # absolute paths the stage must be able to write
NODE_BIN='@@NODE_BIN@@'                     # /usr/local/bin/node
JUST_BIN='@@JUST_BIN@@'                     # /usr/local/bin/just

export PATH="$(dirname "$NODE_BIN"):$(dirname "$JUST_BIN"):/usr/bin:/bin"
SCRATCH="${TMPDIR:-/tmp}"
export HOME="$SCRATCH"

# ---- inventory mode: any argv containing --list -------------------------------
for a in "$@"; do
  if [ "$a" = "--list" ]; then
    for s in "${SCENARIOS[@]}"; do printf '%s::%s: test\n' "$TEST_PREFIX" "$s"; done
    printf '\n%d tests, 0 benchmarks\n' "${#SCENARIOS[@]}"
    exit 0
  fi
done

refuse() { printf 'STAGE-PRECONDITION-UNMET: %s\n' "$1" >&2; exit 2; }

# ---- preconditions (D8) --------------------------------------------------------
[ -x "$NODE_BIN" ] || refuse "node not executable at $NODE_BIN"
[ -x "$JUST_BIN" ] || refuse "just not executable at $JUST_BIN"
[ -r "$REPO/genesis/a2o/$FEATURE" ] || refuse "feature unreadable: $REPO/genesis/a2o/$FEATURE"
have="$(sha256sum "$REPO/genesis/a2o/$FEATURE" | cut -d' ' -f1)"
[ "$have" = "$FEATURE_SHA256" ] || refuse "feature drifted: $have != $FEATURE_SHA256"
# The guest UID almost never owns $REPO (a root/other-owned checkout): git refuses every
# call with "detected dubious ownership" unless told otherwise, and — since createSutProbe's
# git() swallows every failure to null (by design, so a component with no answer falls into
# `unknown` rather than throwing) — a probe run under a hostile git config does not crash; it
# silently resolves EVERY component to null and reports the hash of the empty tuple
# (sha256:e3b0c44298fc1c14, sha256("") truncated) as if it were a real, drifted answer.
# guestEnvironment (worker.mjs) strips everything but PATH/LD_LIBRARY_PATH/
# COMPUTE_RUNTIME_IMAGE/TMPDIR, so these must be set here, not inherited:
#   - GIT_CONFIG_* exempts $REPO from the ownership check without a writable HOME/global config.
#   - GIT_CONFIG_NOSYSTEM skips /etc/gitconfig, which on a mode-0640 group-owned system config
#     the guest UID cannot even read — git aborts the whole command on that alone, dubious
#     ownership or not (verified 2026-09-25 via setpriv reproduction as the guest UID).
export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0=safe.directory
export GIT_CONFIG_VALUE_0="$REPO"
export GIT_CONFIG_NOSYSTEM=1

# S3.0 — the honest artifact: recompute the same source-under-test the requester computed
# (lib/sut.ts, the household receipt's own identity) against THIS checkout, right now. A
# provider running a different tree than the one the requester pinned proves nothing about
# it — refuse before running anything rather than reporting a green that measured the wrong
# source. `node -e` with a dynamic import() so the absolute module path is built from $REPO
# at runtime (a static import specifier cannot be interpolated). Fail loud: a rejected probe
# prints its stack to stderr and exits 1 rather than leaving stdout — and this refusal —
# empty; the printed value is then asserted against the schema's own sut shape before it is
# ever compared, so a swallowed git failure (a valid-shaped hash of nothing, not a crash) is
# caught here too, not just an outright process failure.
sut_stderr="$(mktemp "$SCRATCH/sut-probe-stderr.XXXXXX")"
have_sut="$("$NODE_BIN" -e '
const repo = process.argv[1];
import("file://" + repo + "/genesis/a2o/scripts/lib/sut.ts").then(({ createSutProbe, computeSut }) => {
  const probe = createSutProbe(repo);
  process.stdout.write(computeSut(probe).sut);
}).catch((e) => { console.error(String((e && e.stack) || e)); process.exit(1); });
' "$REPO" 2>"$sut_stderr")"
sut_rc=$?
sut_err_tail="$(tail -c 500 "$sut_stderr" 2>/dev/null | tr '\n' ' ')"
rm -f "$sut_stderr"
if [ "$sut_rc" -ne 0 ] || ! printf '%s' "$have_sut" | grep -Eq '^sha256:[0-9a-f]{16}$'; then
  refuse "sut probe failed: ${sut_err_tail:-no stderr captured}"
fi
[ "$have_sut" = "$SUT_EXPECTED" ] || refuse "sut drifted: $have_sut != $SUT_EXPECTED"
# The pinned copy travels in the dna slot; when the executor exposes it, cross-check.
if [ -n "${SWEETTEST_DNA_DIR:-}" ] && [ -r "$SWEETTEST_DNA_DIR/lamad.dna" ]; then
  staged="$(sha256sum "$SWEETTEST_DNA_DIR/lamad.dna" | cut -d' ' -f1)"
  [ "$staged" = "$FEATURE_SHA256" ] || refuse "staged feature != pinned feature"
fi
for p in "${WRITABLE[@]}"; do [ -w "$p" ] || refuse "not writable: $p"; done

# ---- run -----------------------------------------------------------------------
REPORT="$SCRATCH/cucumber.json"
export REPORT   # the framing step below reads process.env.REPORT — a plain shell var never reaches node
rm -f "$REPORT"
printf 'running %d test\n' "${#SCENARIOS[@]}"
cd "$REPO" || refuse "cannot cd $REPO"
# The guest's inner `just test mesh` must never publish household evidence on its own — the
# requester's own collector (S3a) is the only writer of the peer-stage receipt, and a
# household-lane sprint-report side effect here would carry the PROVIDER's workspace key, a
# claim this run has no standing to make.
export A2O_POST_REPORT=0
# So the inner mesh berth claim is attributable to this stage, not to whatever ambient
# session (or none) launched the guest process.
export BERTH_SESSION="stage:$STAGE_NAME"
export BERTH_CLASS="verify"
CUCUMBER_JSON_REPORT="$REPORT" "$JUST_BIN" test mesh "$FEATURE"
rc=$?
[ -s "$REPORT" ] || { printf 'STAGE-NO-REPORT: just test mesh exited %d and wrote no report\n' "$rc" >&2; exit 101; }

# ---- libtest result lines + the framed report ----------------------------------
"$NODE_BIN" -e '
const fs=require("fs");
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,96).replace(/-+$/,"");
const prefix=process.argv[1], want=process.argv.slice(2);
const doc=JSON.parse(fs.readFileSync(process.env.REPORT,"utf8"));
const seen=new Map();
for(const f of doc) for(const e of (f.elements||[])){
  if(e.type!=="scenario") continue;
  const ok=(e.steps||[]).every(s=>s.result&&s.result.status==="passed");
  seen.set(slug(e.name), ok);
}
let failed=0;
for(const s of want){
  const v=seen.get(s);
  const verdict = v===true ? "ok" : "FAILED";
  if(v!==true) failed++;
  process.stdout.write(`test ${prefix}::${s} ... ${verdict}\n`);
}
process.stdout.write("\n-----BEGIN ELOHIM STAGE REPORT-----\n");
process.stdout.write(Buffer.from(fs.readFileSync(process.env.REPORT)).toString("base64")+"\n");
process.stdout.write("-----END ELOHIM STAGE REPORT-----\n");
process.stdout.write(`\ntest result: ${failed?"FAILED":"ok"}. ${want.length-failed} passed; ${failed} failed; 0 ignored; 0 measured; 0 filtered out\n`);
process.exit(failed?101:0);
' "$TEST_PREFIX" "${SCENARIOS[@]}"
node_rc=$?
if [ "$rc" -ne 0 ] || [ "$node_rc" -ne 0 ]; then exit 101; fi
exit 0
