#!/bin/bash
# Peer-executed a2o stage runner. Content-addressed: this file's CID IS the stage.
# Speaks the minimal libtest CLI the pinned rakia executor drives.
# Generated by build-stage-task.mjs — see
# genesis/docs/superpowers/specs/2026-09-08-peer-executed-stage-design.md §6.2.
set -uo pipefail

STAGE_NAME='@@STAGE_NAME@@'                 # federation-version-convergence
REPO='@@REPO_ROOT@@'
FEATURE='@@FEATURE_REL@@'                   # features/dataplane/federation-version-convergence.feature
FEATURE_SHA256='@@FEATURE_SHA256@@'
TEST_PREFIX='@@TEST_PREFIX@@'               # feedback_signal::a2o::dataplane::federation-version-convergence
SCENARIOS=(@@SCENARIO_SLUGS@@)              # one quoted slug per declared scenario
WRITABLE=(@@WRITABLE_PATHS@@)               # absolute paths the stage must be able to write
NODE_BIN='@@NODE_BIN@@'                     # /usr/local/bin/node
JUST_BIN='@@JUST_BIN@@'                     # /usr/local/bin/just

export PATH="$(dirname "$NODE_BIN"):$(dirname "$JUST_BIN"):/usr/bin:/bin"
SCRATCH="${TMPDIR:-/tmp}"
export HOME="$SCRATCH"

# ---- inventory mode: any argv containing --list -------------------------------
for a in "$@"; do
  if [ "$a" = "--list" ]; then
    for s in "${SCENARIOS[@]}"; do printf '%s::%s: test\n' "$TEST_PREFIX" "$s"; done
    printf '\n%d tests, 0 benchmarks\n' "${#SCENARIOS[@]}"
    exit 0
  fi
done

refuse() { printf 'STAGE-PRECONDITION-UNMET: %s\n' "$1" >&2; exit 2; }

# ---- preconditions (D8) --------------------------------------------------------
[ -x "$NODE_BIN" ] || refuse "node not executable at $NODE_BIN"
[ -x "$JUST_BIN" ] || refuse "just not executable at $JUST_BIN"
[ -r "$REPO/genesis/a2o/$FEATURE" ] || refuse "feature unreadable: $REPO/genesis/a2o/$FEATURE"
have="$(sha256sum "$REPO/genesis/a2o/$FEATURE" | cut -d' ' -f1)"
[ "$have" = "$FEATURE_SHA256" ] || refuse "feature drifted: $have != $FEATURE_SHA256"
# The pinned copy travels in the dna slot; when the executor exposes it, cross-check.
if [ -n "${SWEETTEST_DNA_DIR:-}" ] && [ -r "$SWEETTEST_DNA_DIR/lamad.dna" ]; then
  staged="$(sha256sum "$SWEETTEST_DNA_DIR/lamad.dna" | cut -d' ' -f1)"
  [ "$staged" = "$FEATURE_SHA256" ] || refuse "staged feature != pinned feature"
fi
for p in "${WRITABLE[@]}"; do [ -w "$p" ] || refuse "not writable: $p"; done

# ---- run -----------------------------------------------------------------------
REPORT="$SCRATCH/cucumber.json"
rm -f "$REPORT"
printf 'running %d test\n' "${#SCENARIOS[@]}"
cd "$REPO" || refuse "cannot cd $REPO"
CUCUMBER_JSON_REPORT="$REPORT" "$JUST_BIN" test mesh "$FEATURE"
rc=$?
[ -s "$REPORT" ] || { printf 'STAGE-NO-REPORT: just test mesh exited %d and wrote no report\n' "$rc" >&2; exit 101; }

# ---- libtest result lines + the framed report ----------------------------------
"$NODE_BIN" -e '
const fs=require("fs");
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,96).replace(/-+$/,"");
const prefix=process.argv[1], want=process.argv.slice(2);
const doc=JSON.parse(fs.readFileSync(process.env.REPORT,"utf8"));
const seen=new Map();
for(const f of doc) for(const e of (f.elements||[])){
  if(e.type!=="scenario") continue;
  const ok=(e.steps||[]).every(s=>s.result&&s.result.status==="passed");
  seen.set(slug(e.name), ok);
}
let failed=0;
for(const s of want){
  const v=seen.get(s);
  const verdict = v===true ? "ok" : "FAILED";
  if(v!==true) failed++;
  process.stdout.write(`test ${prefix}::${s} ... ${verdict}\n`);
}
process.stdout.write("\n-----BEGIN ELOHIM STAGE REPORT-----\n");
process.stdout.write(Buffer.from(fs.readFileSync(process.env.REPORT)).toString("base64")+"\n");
process.stdout.write("-----END ELOHIM STAGE REPORT-----\n");
process.stdout.write(`\ntest result: ${failed?"FAILED":"ok"}. ${want.length-failed} passed; ${failed} failed; 0 ignored; 0 measured; 0 filtered out\n`);
process.exit(failed?101:0);
' "$TEST_PREFIX" "${SCENARIOS[@]}"
node_rc=$?
if [ "$rc" -ne 0 ] || [ "$node_rc" -ne 0 ]; then exit 101; fi
exit 0
