// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessGrant } from "./AccessGrant";

/**
 * Output from content_store::grant_access coordinator function.
 */
export type AccessGrantOutput = { action_hash: string, grant: AccessGrant, };
