// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for accepting a custodian commitment.
 */
export type AcceptCommitmentInput = { commitment_id: string, };
