// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AccessGrant wire type. Mirrors the integrity zome's AccessGrant entry type.
 */
export type AccessGrant = { id: string, gate_id: string, learner_agent_id: string, grant_type: string, granted_via: string, payment_event_id: string | null, payment_amount: number | null, payment_unit: string | null, scholarship_sponsor_id: string | null, scholarship_reason: string | null, granted_at: string, valid_until: string | null, renewal_due_at: string | null, is_active: boolean, revoked_at: string | null, revoke_reason: string | null, metadata_json: string, created_at: string, };
