// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agreement } from "./Agreement";

/**
 * Output from content_store::get_agreement coordinator function.
 */
export type AgreementOutput = { action_hash: string, entry_hash: string, agreement: Agreement, };
