// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agreement wire type. Mirrors the integrity zome's Agreement entry type.
 */
export type Agreement = { id: string, name: string | null, note: string | null, created_at: string, };
