// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from batch accepting custodian commitments.
 */
export type BatchAcceptCommitmentsOutput = { accepted_count: number, failed_count: number, errors: Array<string>, };
