// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for batch accepting custodian commitments.
 */
export type BatchAcceptCommitmentsInput = { commitment_ids: Array<string>, };
