// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for batch updating custodian commitment metadata.
 */
export type BatchUpdateCommitmentsInput = { 
/**
 * Vec of (commitment_id, new_cache_priority, new_bandwidth_class).
 */
updates: Array<[string, number, string | null]>, };
