// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commitment wire type. Mirrors the integrity zome's Commitment entry type.
 */
export type Commitment = { id: string, action: string, provider: string, receiver: string, resource_conforms_to: string | null, resource_inventoried_as: string | null, resource_classified_as_json: string, resource_quantity_value: number | null, resource_quantity_unit: string | null, effort_quantity_value: number | null, effort_quantity_unit: string | null, has_point_in_time: string | null, has_beginning: string | null, has_end: string | null, due: string | null, clause_of: string | null, agreed_in: string | null, input_of: string | null, output_of: string | null, satisfies: string | null, in_scope_of_json: string, finished: boolean, state: string, note: string | null, metadata_json: string, created_at: string, updated_at: string, };
