// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Impact summary per content piece.
 */
export type ContentImpactSummary = { content_id: string, recognition_points: bigint, learners_reached: number, mastery_count: number, };
