// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_steward_credential coordinator function.
 */
export type CreateStewardCredentialInput = { steward_presence_id: string, tier: string, domain_tags: Array<string>, mastery_content_ids: Array<string>, mastery_level_achieved: string, peer_attestation_ids: Array<string>, stewarded_presence_ids: Array<string>, stewarded_content_ids: Array<string>, stewarded_path_ids: Array<string>, note: string | null, };
