// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequiredAttestationInput } from "./RequiredAttestationInput";
import type { RequiredMasteryInput } from "./RequiredMasteryInput";
import type { RequiredVouchesInput } from "./RequiredVouchesInput";

/**
 * Input for content_store::create_premium_gate coordinator function.
 */
export type CreatePremiumGateInput = { steward_credential_id: string, steward_presence_id: string, contributor_presence_id: string | null, gated_resource_type: string, gated_resource_ids: Array<string>, gate_title: string, gate_description: string, gate_image: string | null, required_attestations: Array<RequiredAttestationInput>, required_mastery: Array<RequiredMasteryInput>, required_vouches: RequiredVouchesInput | null, pricing_model: string, price_amount: number | null, price_unit: string | null, subscription_period_days: number | null, min_amount: number | null, steward_share_percent: number, commons_share_percent: number, contributor_share_percent: number | null, scholarship_eligible: boolean, max_scholarships_per_period: number | null, scholarship_criteria_json: string | null, note: string | null, };
