// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_agreement coordinator function.
 */
export type CreateAgreementInput = { id: string, name: string | null, note: string | null, };
