// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_rea_economic_event coordinator function.
 */
export type CreateReaEconomicEventInput = { id: string, action: string, provider: string, receiver: string, resource_classified_as: Array<string>, resource_quantity_value: number | null, resource_quantity_unit: string | null, effort_quantity_value: number | null, effort_quantity_unit: string | null, has_point_in_time: string, fulfills: Array<string>, realization_of: string | null, lamad_event_type: string | null, note: string | null, metadata_json: string | null, };
