// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_custodian_commitment coordinator function.
 */
export type CreateCustodianCommitmentInput = { custodian_agent_id: string, beneficiary_agent_id: string, commitment_type: string, basis: string, relationship_id: string | null, category_override_json: string, content_filters_json: string, estimated_content_count: number, estimated_size_mb: number, shard_strategy: string, redundancy_factor: number, shard_assignments_json: string, emergency_triggers_json: string, emergency_contacts_json: string, recovery_instructions_json: string, cache_priority: number | null, bandwidth_class: string | null, geographic_affinity: string | null, note: string | null, metadata_json: string | null, };
