// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_rea_commitment coordinator function.
 */
export type CreateReaCommitmentInput = { id: string, action: string, provider: string, receiver: string, resource_classified_as: Array<string>, resource_quantity_value: number | null, resource_quantity_unit: string | null, effort_quantity_value: number | null, effort_quantity_unit: string | null, has_beginning: string | null, has_end: string | null, due: string | null, clause_of: string | null, in_scope_of: Array<string>, note: string | null, metadata_json: string | null, };
