// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CustodianCommitment wire type. Mirrors the integrity zome's CustodianCommitment entry type.
 */
export type CustodianCommitment = { id: string, custodian_agent_id: string, beneficiary_agent_id: string, commitment_type: string, basis: string, relationship_id: string | null, category_override_json: string, content_filters_json: string, estimated_content_count: number, estimated_size_mb: number, shard_strategy: string, redundancy_factor: number, shard_assignments_json: string, emergency_triggers_json: string, emergency_contacts_json: string, recovery_instructions_json: string, cache_priority: number, bandwidth_class: string, geographic_affinity: string | null, state: string, proposed_at: string, accepted_at: string | null, activated_at: string | null, last_verification_at: string | null, verification_failures_json: string, shards_stored_count: number, last_shard_update_at: string | null, total_restores_performed: number, shefa_commitment_id: string | null, note: string | null, metadata_json: string, created_at: string, updated_at: string, };
