// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustodianCommitment } from "./CustodianCommitment";

/**
 * Output from content_store::create_custodian_commitment coordinator function.
 */
export type CustodianCommitmentOutput = { action_hash: string, entry_hash: string, commitment: CustodianCommitment, };
