// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EconomicEvent wire type. Mirrors the integrity zome's EconomicEvent entry type.
 */
export type EconomicEvent = { id: string, action: string, provider: string, receiver: string, resource_conforms_to: string | null, resource_inventoried_as: string | null, to_resource_inventoried_as: string | null, resource_classified_as_json: string, resource_quantity_value: number | null, resource_quantity_unit: string | null, effort_quantity_value: number | null, effort_quantity_unit: string | null, has_point_in_time: string, has_duration: string | null, input_of: string | null, output_of: string | null, fulfills_json: string, realization_of: string | null, satisfies_json: string, in_scope_of_json: string, note: string | null, state: string, triggered_by: string | null, at_location: string | null, image: string | null, lamad_event_type: string | null, metadata_json: string, created_at: string, };
