// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revenue summary per gate.
 */
export type GateRevenueSummary = { gate_id: string, gate_title: string, total_revenue: number, grant_count: number, };
