// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::grant_access coordinator function.
 */
export type GrantAccessInput = { gate_id: string, grant_type: string, granted_via: string, payment_amount: number | null, payment_unit: string | null, scholarship_sponsor_id: string | null, scholarship_reason: string | null, };
