// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PremiumGate } from "./PremiumGate";

/**
 * Output from content_store::create_premium_gate coordinator function.
 */
export type PremiumGateOutput = { action_hash: string, gate: PremiumGate, };
