// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying custodian commitments.
 */
export type QueryCommitmentsInput = { custodian_agent_id: string | null, beneficiary_agent_id: string | null, commitment_type: string | null, state: string | null, basis: string | null, limit: number | null, };
