// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commitment } from "./Commitment";

/**
 * Output from content_store::get_rea_commitment coordinator function.
 */
export type ReaCommitmentOutput = { action_hash: string, entry_hash: string, commitment: Commitment, };
