// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EconomicEvent } from "./EconomicEvent";

/**
 * Output from content_store::create_rea_economic_event coordinator function.
 */
export type ReaEconomicEventOutput = { action_hash: string, entry_hash: string, event: EconomicEvent, fulfillment_links: Array<string>, };
