// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recent recognition event for the timeline.
 */
export type RecognitionEventSummary = { learner_id: string, content_id: string, flow_type: string, recognition_points: number, occurred_at: string, };
