// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Required vouches for gate access.
 */
export type RequiredVouchesInput = { min_count: number, from_tier: string | null, };
