// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Required mastery for gate access.
 */
export type RequiredMasteryInput = { content_id: string, min_level: string, };
