// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Required attestation for gate access.
 */
export type RequiredAttestationInput = { attestation_type: string, attestation_id: string | null, };
