// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StewardCredential } from "./StewardCredential";

/**
 * Output from content_store::create_steward_credential coordinator function.
 */
export type StewardCredentialOutput = { action_hash: string, credential: StewardCredential, };
