// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateRevenueSummary } from "./GateRevenueSummary";

/**
 * Steward revenue summary across all gates.
 */
export type StewardRevenueSummary = { steward_presence_id: string, total_revenue: number, total_grants: number, revenue_by_gate: Array<GateRevenueSummary>, };
