// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StewardRevenue } from "./StewardRevenue";

/**
 * Output from steward revenue operations.
 */
export type StewardRevenueOutput = { action_hash: string, revenue: StewardRevenue, };
