// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StewardRevenue wire type. Mirrors the integrity zome's StewardRevenue entry type.
 */
export type StewardRevenue = { id: string, access_grant_id: string, gate_id: string, from_learner_id: string, to_steward_presence_id: string, to_contributor_presence_id: string | null, gross_amount: number, payment_unit: string, steward_amount: number, contributor_amount: number, commons_amount: number, steward_economic_event_id: string, contributor_economic_event_id: string | null, commons_economic_event_id: string, status: string, completed_at: string | null, failure_reason: string | null, note: string | null, metadata_json: string, created_at: string, };
