// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * StewardCredential wire type. Mirrors the integrity zome's StewardCredential entry type.
 */
export type StewardCredential = { id: string, steward_presence_id: string, agent_id: string, tier: string, stewarded_presence_ids_json: string, stewarded_content_ids_json: string, stewarded_path_ids_json: string, mastery_content_ids_json: string, mastery_level_achieved: string, qualification_verified_at: string, peer_attestation_ids_json: string, unique_attester_count: number, attester_reputation_sum: number, stewardship_quality_score: number, total_learners_served: number, total_content_improvements: number, domain_tags_json: string, is_active: boolean, deactivation_reason: string | null, note: string | null, metadata_json: string, created_at: string, updated_at: string, };
