/**
 * Thin TypeScript client for the Elohim gate interface.
 *
 * Angular / browser callers import `createGateClient` and invoke `check()` on
 * every relational-impact write path. The client mirrors the Rust `gate-client`
 * crate's public surface (see `elohim/elohim-agent/gate-client/src/lib.rs`).
 *
 * # Phase
 *
 * Phase 1 scope ships two transports:
 * - `mock`: returns an `Allow` decision locally. Mirrors the Rust mock path
 *   used during DevContext rehearsal.
 * - `http`: POSTs to a remote `elohim-agent-service` endpoint. Structurally
 *   wired but the server side does not yet exist; this is exercised
 *   end-to-end in Phase 2.
 *
 * The wire types live in `./generated/` and are regenerated by running
 * `cargo test -p gate-client --features typescript` from the Rust side.
 */

import type { GateDecision } from './generated/GateDecision.js';
import type { EscalationTarget } from './generated/EscalationTarget.js';
import type { RelationalImpactEvent } from './generated/RelationalImpactEvent.js';

/**
 * Configuration for a gate client instance.
 *
 * `transport` selects local mock vs. remote HTTP; `endpoint` is required when
 * `transport === 'http'` and ignored otherwise.
 */
export interface GateClientConfig {
  transport: 'mock' | 'http';
  /** Required when `transport === 'http'`. Base URL of the elohim-agent-service. */
  endpoint?: string;
}

/**
 * The public interface every caller sees.
 *
 * `check` is the universal gate primitive — invoke it before any
 * relational-impact write. `queueForReview` is the escalation companion used
 * when a decision needs human review; in Phase 1 it returns a synthetic UUID
 * under the mock transport.
 */
export interface GateClient {
  check(event: RelationalImpactEvent): Promise<GateDecision>;
  queueForReview(target: EscalationTarget, context: unknown): Promise<string>;
}

/**
 * Factory for gate-client instances.
 *
 * @throws if `transport === 'http'` and `endpoint` is missing.
 */
export function createGateClient(config: GateClientConfig): GateClient {
  if (config.transport === 'http' && !config.endpoint) {
    throw new Error(
      "createGateClient: transport 'http' requires a non-empty `endpoint`.",
    );
  }

  if (config.transport === 'mock') {
    return new MockGateClient();
  }

  return new HttpGateClient(config.endpoint!);
}

// ---------------------------------------------------------------------------
// Mock transport
// ---------------------------------------------------------------------------

/**
 * Placeholder reasoning emitted by the mock transport.
 *
 * Mirrors `ConstitutionalReasoningSummary::mocked()` on the Rust side
 * (`elohim/elohim-agent/gate-client/src/types.rs`). Confidence is 0.0 because
 * no real wisdom invocation ran.
 */
const MOCKED_REASONING = {
  primary_principle: 'dev-context-mock',
  summary: 'Rehearsal phase: wisdom-invoke mocked to Allow.',
  confidence: 0.0,
  phase_note: 'This decision carries no reputation weight.',
} as const;

class MockGateClient implements GateClient {
  async check(_event: RelationalImpactEvent): Promise<GateDecision> {
    // The closed RelationalImpactEvent enum (see events.rs) holds only
    // boundary-crossing variants — there is no "exempt interior" variant the
    // TypeScript caller could construct. Mirror the Rust mock path:
    // always return Allow { exempt: false } in dev-context.
    return {
      status: { status: 'allow', exempt: false },
      reasoning: { ...MOCKED_REASONING },
      side_effects: [],
      decision_attestation_cid: null,
      phase: 'dev-context',
    };
  }

  async queueForReview(
    _target: EscalationTarget,
    _context: unknown,
  ): Promise<string> {
    // Synthetic UUID — the mock transport does not persist escalations.
    // Phase 2 wires in a real queue via the http transport.
    return generateMockReviewId();
  }
}

function generateMockReviewId(): string {
  // RFC-4122 v4 shape; random, not cryptographic. Sufficient for mock mode
  // where the ID is a placeholder carried through to a never-retrieved queue.
  const hex = (n: number) => Math.floor(Math.random() * n).toString(16);
  const segment = (len: number) =>
    Array.from({ length: len }, () => hex(16)).join('');
  return `${segment(8)}-${segment(4)}-4${segment(3)}-${segment(4)}-${segment(12)}`;
}

// ---------------------------------------------------------------------------
// HTTP transport
// ---------------------------------------------------------------------------

class HttpGateClient implements GateClient {
  constructor(private readonly endpoint: string) {}

  async check(event: RelationalImpactEvent): Promise<GateDecision> {
    const response = await fetch(`${this.endpoint}/gate/check`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(event),
    });

    if (!response.ok) {
      throw new Error(
        `gate-client: /gate/check returned ${response.status} ${response.statusText}`,
      );
    }

    return (await response.json()) as GateDecision;
  }

  async queueForReview(
    target: EscalationTarget,
    context: unknown,
  ): Promise<string> {
    const response = await fetch(`${this.endpoint}/gate/queue-review`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ target, context }),
    });

    if (!response.ok) {
      throw new Error(
        `gate-client: /gate/queue-review returned ${response.status} ${response.statusText}`,
      );
    }

    const body = (await response.json()) as { review_id: string };
    return body.review_id;
  }
}
