/**
 * Public entry point for the gate-client module of @elohim/agent-sdk.
 *
 * Angular / browser callers import from here:
 *
 * ```ts
 * import { createGateClient, type RelationalImpactEvent } from '@elohim/agent-sdk/gate-client';
 * ```
 *
 * The underlying wire types are generated by ts-rs from the Rust `gate-client`
 * crate. Regenerate by running:
 *
 * ```bash
 * cd /projects/elohim/elohim && RUSTFLAGS="" cargo test -p gate-client --features typescript
 * ```
 */

export { createGateClient } from './client.js';
export type { GateClient, GateClientConfig } from './client.js';

// Re-export the generated wire types so callers do not need to reach into
// ./generated/ directly.
export type { ConstitutionalReasoningSummary } from './generated/ConstitutionalReasoningSummary.js';
export type { DeclineGrounds } from './generated/DeclineGrounds.js';
export type { EscalationTarget } from './generated/EscalationTarget.js';
export type { GateDecision } from './generated/GateDecision.js';
export type { GateStatus } from './generated/GateStatus.js';
export type { GateTag } from './generated/GateTag.js';
export type { Phase } from './generated/Phase.js';
export type { RelationalImpactEvent } from './generated/RelationalImpactEvent.js';
export type { Severity } from './generated/Severity.js';
export type { SideEffect } from './generated/SideEffect.js';
export type { SpaceContext } from './generated/SpaceContext.js';
export type { SpaceType } from './generated/SpaceType.js';
