// genesis/landing/scripts/render-content.ts
//
// Build-time script: reads manifesto.md from genesis/docs,
// renders it to HTML fragments, and writes to src/generated/ for
// inclusion in the landing page.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENESIS_DOCS = resolve(__dirname, '../../docs/content/elohim-protocol');
const OUTPUT_DIR = resolve(__dirname, '../src/generated');

// Ensure output directory exists
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

// --- Manifesto summary ---
const manifestoMd = readFileSync(resolve(GENESIS_DOCS, 'manifesto.md'), 'utf-8');
// Extract executive summary (between ## **Executive Summary** and the next ##)
const summaryMatch = manifestoMd.match(/## \*\*Executive Summary\*\*\s*\n([\s\S]*?)(?=\n## )/);
const summaryHtml = summaryMatch
  ? (marked.parse(summaryMatch[1].trim()) as string)
  : '<p>The manifesto summary could not be loaded.</p>';

// --- Pillar descriptions ---
const pillars = [
  {
    id: 'lamad',
    name: 'Lamad',
    icon: '\u{1F4DA}',
    description:
      'Learning that transforms — paths curated by stewards, assessed through mastery, governed by the community.',
  },
  {
    id: 'imagodei',
    name: 'ImagoDei',
    icon: '\u{1F464}',
    description:
      'Identity as relationship — you are known by your contributions, not your credentials.',
  },
  {
    id: 'qahal',
    name: 'Qahal',
    icon: '\u{1F3DB}',
    description:
      'Governance as practice — consent, ranked choice, and constitutional limits experienced daily.',
  },
  {
    id: 'shefa',
    name: 'Shefa',
    icon: '\u{1F331}',
    description:
      'Economics that flow — mutual credit, steward recognition, and value that decays without care.',
  },
  {
    id: 'elohim',
    name: 'Elohim',
    icon: '\u{1F525}',
    description:
      'AI guardians that serve — agents bounded by constitutional law, carrying human interests into deliberation.',
  },
];

// Write generated content as JS module for import
const output = `// AUTO-GENERATED by render-content.ts — do not edit
export const manifestoSummary = ${JSON.stringify(summaryHtml)};
export const pillars = ${JSON.stringify(pillars, null, 2)};
`;

writeFileSync(resolve(OUTPUT_DIR, 'content.ts'), output, 'utf-8');
console.log('Generated landing page content to src/generated/content.ts');
