/* eslint-disable @typescript-eslint/consistent-indexed-object-style */
/* Generated from protocol schema: enums/content-type.schema.json -- DO NOT EDIT */

/**
 * Content type vocabulary. Core types are DNA-notarized (three-leg coupled: knowledge+value+governance). Storage-only types are cross-domain entity references. Extensible types are community vocabulary.
 */
export type ContentType =
  | 'epic'
  | 'concept'
  | 'lesson'
  | 'scenario'
  | 'assessment'
  | 'reflection'
  | 'discussion'
  | 'exercise'
  | 'article'
  | 'path'
  | 'human'
  | 'role'
  | 'collective'
  | 'example'
  | 'reference'
  | 'feature'
  | 'practice'
  | 'contributor'
  | 'video'
  | 'audio'
  | 'book'
  | 'book-chapter'
  | 'documentary'
  | 'bible-verse'
  | 'activity'
  | 'narrative'
  | 'course-module'
  | 'module'
  | 'quiz'
  | 'podcast'
  | 'simulation'
  | 'node-context'
  | 'stewardship-context'
  | 'work-story'
  | 'work-project'
  | 'issue-report'
  | 'application'
  | 'gate-process-declaration'
  | 'universal-band-declaration'
  | 'gate-rules-declaration'
  | 'aggregation-spec'
  | 'escalation-target-spec';
