"""seam_matrix.py — the concern x seam MATRIX, generated by the census (plan P4.3, surface 6).

THE UNEXAMINED CELLS ARE THE FORECAST. That is the whole point of this module: the matrix is not a
status report, it is the instrument that turns "we have not looked there" into a ranked, addressable
list — so the next architecture-scale shift finds its walls already named instead of discovering
them bespoke in production.

GENERATED, NEVER HAND-WRITTEN.
  ROWS    = the concern classes, read from BOTH canon homes (`.claude/epr-meta/policies.yaml`
            enforcement rows + `.claude/epr-meta/concerns.yaml` Precedent rows) INCLUDING
            superseded lineage — a class counts ONCE, at its lineage tip. C6a is the worked case:
            `concerns.yaml#c6a-bounded-work@1` is superseded by `policies.yaml#c6a-bounded-work@2`,
            and the row that counts is the tip in the OTHER file.
  COLUMNS = `.claude/epr-meta/seam-catalog.yaml` — the atlas §3 catalog grouped by its §7 planes,
            plus the governing/meta column and the bridges column. Participation track (T1-T4) and
            reach tier are CELL ATTRIBUTES carried from the seam, never axes.
  CELLS   = derived from the `seam-registry.yaml` files by the census read-model.
Nothing in this module authors a judgment; every judgment it reports is traceable to a registry row
or a canon row.

CELL STATE DERIVATION — PRECISION-BIASED, and the bias direction is deliberate.
Let E be the concernIds entries citing class C at decision points routed to seam S:
  E is empty                              -> `unexamined`   (nobody has looked)
  every entry says status `n-a`           -> `n-a`          (declared inapplicable, WITH the
                                                              schema-required justification)
  every non-n-a entry is `answered` AND
    its point cites a contract test that
    exists and contains the named fn      -> `conformant`
  anything else                           -> `variant`
`variant` is therefore doing two jobs, and the plan's own vocabulary is what forces that: a
`partial`/`unbound` entry is a documented, negotiated waiver (variance is standing, not violation),
and an `answered` entry with NO verified contract test is a claim of conformance with nothing
behind it. Reading the second as `conformant` would be exactly the over-claim the census exists to
prevent — a cell that says conformant because someone wrote "answered" is worse than a cell that
says unexamined, because it stops anyone looking. Both surface with a `reason` on the cell, so the
two senses are distinguishable to a reader even though they share a state.

RANKING (unexamined cells only, on the museum's frequency-ranking convention — never flat):
  score = recurrence x severity x rung-proximity
    recurrence      = the canon row's `recurrence.shifts` (unit: distinct shifts), default 1
    severity        = silent-corruption 2.0 / loud-fail 1.0 (a class that fails silently outranks
                      one that fails loudly at equal recurrence — you cannot triage what does not
                      announce itself)
    rung-proximity  = the strongest charter linkage of the seam: active red 4.0 / red 3.0 /
                      active unwired 2.5 / unwired 2.0 / green 1.0 / no linked node 0.5
                      (from `genesis/manifests/charter.yaml`, the DECLARED delivery truth this repo
                      already opens every session on)

SPOT-CHECK BEFORE YOU TRUST THE RANKING. `feedback_verify_the_measure_before_the_ranking`: a drift
audit can be the dominant source of its own findings, and a mis-resolving resolver does not degrade
a ranking, it REORDERS it. `spot_check()` re-derives a random-but-reproducible sample of cells
straight from disk through an INDEPENDENT code path (raw YAML load, line-scan test containment) and
compares to what the census reported. It is written not to share a helper with the census on
purpose — a check that calls the thing it checks is a mirror, which is the exact defect
(`BlobCid::verifies`, 2026-07-24) the anti-mirror discipline exists for. Any mismatch means the
ranking is not trustworthy until it is explained.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from _lib import seam_cascade as _casc
from _lib import seam_census as _sc

try:
    import yaml
except Exception:  # pragma: no cover
    yaml = None

SEAM_CATALOG_REL = ".claude/epr-meta/seam-catalog.yaml"
CHARTER_REL = "genesis/manifests/charter.yaml"
GENERATED_DIR_REL = ".claude/epr-meta/generated"
MATRIX_JSON_REL = f"{GENERATED_DIR_REL}/concern-seam-matrix.json"
MATRIX_MD_REL = f"{GENERATED_DIR_REL}/concern-seam-matrix.md"

_SEVERITY_WEIGHT = {"silent-corruption": 2.0, "loud-fail": 1.0}
_STATE_GLYPH = {"conformant": "✓", "variant": "~", "unexamined": "·", "n-a": "-"}


# ───────────────────────────── inputs ─────────────────────────────

def load_catalog(repo_root: Path) -> tuple[dict, list[str]]:
    """Load the seam catalog -> ({plane_groups, seams, ...}, errors). Missing/unreadable is an
    ERROR, not a legitimate empty: a matrix with no column axis is not a degraded matrix, it is a
    dead instrument, and a dead instrument reads as 'nothing to report'."""
    p = Path(repo_root) / SEAM_CATALOG_REL
    if not p.is_file():
        return {}, [f"{SEAM_CATALOG_REL} not found — the matrix has no column axis"]
    if yaml is None:
        return {}, [f"PyYAML unavailable — {SEAM_CATALOG_REL} not loaded"]
    try:
        data = yaml.safe_load(p.read_text()) or {}
    except Exception as e:  # noqa: BLE001
        return {}, [f"{SEAM_CATALOG_REL} unreadable/invalid: {e}"]
    if not isinstance(data, dict) or data.get("seam-catalog-version") != 1:
        return {}, [f"{SEAM_CATALOG_REL} missing/invalid `seam-catalog-version` (must be 1)"]
    seams = data.get("seams")
    if not isinstance(seams, list) or not seams:
        return {}, [f"{SEAM_CATALOG_REL} has no `seams`"]
    errs: list[str] = []
    good = []
    for i, s in enumerate(seams):
        if not isinstance(s, dict) or not s.get("id") or not s.get("plane"):
            errs.append(f"{SEAM_CATALOG_REL} seams[{i}] needs `id` + `plane`")
            continue
        good.append(s)
    out = dict(data)
    out["seams"] = good
    return out, errs


def load_charter(repo_root: Path) -> tuple[dict, list[str]]:
    """`{node_id: {status, active}}` from the declared delivery charter. A missing charter degrades to
    an empty map with a NOTE (rung-proximity then falls to its floor for every seam) — the matrix
    is still meaningful without it, only less sharply ordered."""
    p = Path(repo_root) / CHARTER_REL
    if not p.is_file() or yaml is None:
        return {}, [f"{CHARTER_REL} unavailable — rung-proximity falls back to its floor for every seam"]
    try:
        data = yaml.safe_load(p.read_text()) or {}
    except Exception as e:  # noqa: BLE001
        return {}, [f"{CHARTER_REL} unreadable: {e}"]
    out = {}
    for n in data.get("articles") or data.get("nodes") or []:
        if isinstance(n, dict) and n.get("id"):
            out[n["id"]] = {"status": n.get("status"), "active": bool(n.get("active"))}
    return out, []


def concern_tips(repo_root: Path) -> tuple[dict, list[str]]:
    """`{concern_id: tip_row}` across BOTH homes, following supersession lineage so a class counts
    ONCE at its tip. Reuses `seam_cascade.canon_rows`/`resolve_tip` rather than re-deriving lineage
    resolution — one home for the lineage walk, which is what keeps a cross-home graduation (C6a)
    from being read as two classes."""
    rows, errs = _casc.canon_rows(repo_root)
    by_concern: dict[str, list[tuple[str, dict]]] = {}
    for key, row in rows.items():
        cid = row.get("concern")
        if cid in _sc._CONCERN_ID_SET:
            by_concern.setdefault(cid, []).append((key, row))
    tips: dict[str, dict] = {}
    for cid, entries in by_concern.items():
        tip_keys = set()
        for key, _row in entries:
            tip, _lineage, lerr = _casc.resolve_tip(rows, key)
            if lerr:
                errs.append(f"{cid}: {lerr}")
            if tip:
                tip_keys.add(tip)
        if len(tip_keys) > 1:
            errs.append(f"class {cid} resolves to MULTIPLE lineage tips {sorted(tip_keys)} — "
                        f"a class must have exactly one tip or a pin to it is ambiguous")
        for tk in sorted(tip_keys):
            r = rows.get(tk)
            if isinstance(r, dict):
                tips[cid] = dict(r, __ref__=tk)
                break
    return tips, errs


# ───────────────────────────── routing ─────────────────────────────

def _routing(catalog: dict) -> tuple[dict, dict]:
    """(crate -> seam id, "crate::point" -> seam id) from the catalog's `registry_crates` and
    `point_overrides`. Point overrides win — steward/node's admission surface is resource
    governance (§3.15), not cluster ops (§3.12), and the atlas says so explicitly."""
    by_crate: dict[str, str] = {}
    by_point: dict[str, str] = {}
    for s in catalog.get("seams", []):
        for c in s.get("registry_crates") or []:
            by_crate[c] = s["id"]
        for k, v in (s.get("point_overrides") or {}).items():
            by_point[k] = v
    return by_crate, by_point


# ───────────────────────────── the matrix ─────────────────────────────

def matrix_data(repo_root: Path) -> dict:
    """Compute the whole matrix. Never raises; every failure degrades to an error string plus the
    narrowest possible loss of resolution."""
    repo_root = Path(repo_root)
    catalog, cat_errs = load_catalog(repo_root)
    charter, charter_errs = load_charter(repo_root)
    tips, tip_errs = concern_tips(repo_root)
    errors = list(cat_errs) + list(charter_errs) + list(tip_errs)

    seams = catalog.get("seams", [])
    seam_ids = [s["id"] for s in seams]
    seam_by_id = {s["id"]: s for s in seams}
    by_crate, by_point = _routing(catalog)

    # ── walk the registries, routing each decision point to a seam column ──
    schema, schema_err = _sc.load_schema(repo_root)
    if schema_err:
        errors.append(schema_err)
    top_v = _sc._build_top_level_validator(schema) if schema else None
    item_v = _sc._build_item_validator(schema) if schema else None

    # (concern, seam) -> list of citing entries
    entries: dict[tuple[str, str], list[dict]] = {}
    points_seen = 0
    for path in _sc.discover_registry_paths(repo_root):
        rel = path.relative_to(repo_root).as_posix()
        data, file_errs, row_errs = _sc.load_registry(path, top_v, item_v)
        if data is None:
            errors.append(f"{rel}: " + "; ".join(file_errs))
            continue
        for e in row_errs:
            errors.append(f"{rel}: {e}")
        crate = data.get("crate", "?")
        for pt in data["decisionPoints"]:
            points_seen += 1
            name = pt.get("name", "?")
            seam_id = by_point.get(f"{crate}::{name}") or by_crate.get(crate)
            if not seam_id:
                errors.append(
                    f"{rel}: crate `{crate}` is not routed to any seam column — add it to a seam's "
                    f"`registry_crates` in {SEAM_CATALOG_REL} (an unrouted registry silently "
                    f"contributes ZERO cells, which reads as unexamined everywhere)")
                continue
            if seam_id not in seam_by_id:
                errors.append(f"{rel}: crate `{crate}` routes to unknown seam `{seam_id}`")
                continue
            # DELIBERATE reach into the census's citation checker: contract-test existence +
            # containment must be decided in exactly ONE place, and that place is the census
            # (interface-first-reuse). Forking it here is what would let the matrix and the census
            # disagree about whether a cell is conformant. If this helper ever graduates to public,
            # this call site is the reason.
            verified, _f = _sc._check_contract_tests(repo_root, crate, pt)
            for cb in pt.get("concernIds", []):
                cid = cb.get("id")
                if cid not in _sc._CONCERN_ID_SET:
                    continue
                entries.setdefault((cid, seam_id), []).append({
                    "crate": crate, "point": name, "status": cb.get("status"),
                    "verified": bool(verified), "file": pt.get("sourceLocation", {}).get("file"),
                })

    # ── derive every cell ──
    cells: list[dict] = []
    for cid in _sc.ALL_CONCERN_IDS:
        tip = tips.get(cid)
        for sid in seam_ids:
            seam = seam_by_id[sid]
            E = entries.get((cid, sid), [])
            state, reason = _derive_state(cid, seam, E)
            cell = {
                "concern": cid, "seam": sid, "plane": seam.get("plane"),
                "state": state, "reason": reason,
                "tracks": seam.get("tracks") or [], "reach_tier": seam.get("reach_tier"),
                "points": E,
            }
            if state == "unexamined":
                cell["score"], cell["score_parts"] = _score(tip, seam, charter)
            cells.append(cell)

    # Light refs, not cell copies: the generated JSON is git-tracked and churns on every substrate
    # move, so the ranking carries only what a ranking needs. The full cell stays in `cells`.
    ranked = [{"concern": c["concern"], "seam": c["seam"], "score": c["score"],
               "score_parts": c["score_parts"]}
              for c in sorted((c for c in cells if c["state"] == "unexamined"),
                              key=lambda c: (-c["score"], c["concern"], c["seam"]))]

    counts: dict[str, int] = {}
    for c in cells:
        counts[c["state"]] = counts.get(c["state"], 0) + 1

    data = {
        "n_concerns": len(_sc.ALL_CONCERN_IDS),
        "n_seams": len(seam_ids),
        "n_cells": len(cells),
        "n_points_routed": points_seen,
        "plane_groups": catalog.get("plane_groups", []),
        "seams": [{k: v for k, v in s.items() if k != "point_overrides"} for s in seams],
        "concern_tips": {cid: {"ref": r.get("__ref__"), "home": r.get("__home__"),
                                 "title": r.get("title", ""),
                                 "severity_class": r.get("severity_class"),
                                 "recurrence_shifts": _recurrence(r)}
                          for cid, r in sorted(tips.items())},
        "counts": counts,
        "cells": cells,
        "ranked_unexamined": ranked,
        "errors": errors,
        "axis_notes": catalog.get("axis_notes", []),
    }
    data["digest"] = matrix_digest(data)
    return data


def _derive_state(cid: str, seam: dict, E: list[dict]) -> tuple[str, str]:
    """See the module docstring's CELL STATE DERIVATION section. Returns (state, reason)."""
    declared_na = seam.get("n_a_concerns") or []
    if cid in declared_na:
        return "n-a", "declared n-a for this seam in the catalog"
    if not E:
        return "unexamined", "no registered decision point at this seam cites this class"
    statuses = [e.get("status") for e in E]
    if all(s == "n-a" for s in statuses):
        return "n-a", f"{len(E)} point(s) declare n-a with justification"
    non_na = [e for e in E if e.get("status") != "n-a"]
    if all(e.get("status") == "answered" and e.get("verified") for e in non_na):
        return "conformant", (f"{len(non_na)} point(s) answered with a cited contract test that "
                              f"exists and contains the named fn")
    weak_status = sorted({e.get("status") for e in non_na if e.get("status") != "answered"})
    unverified = [e["point"] for e in non_na
                  if e.get("status") == "answered" and not e.get("verified")]
    bits = []
    if weak_status:
        bits.append("documented waiver: status " + "/".join(str(s) for s in weak_status))
    if unverified:
        bits.append("answered but NO verified contract test: " + ", ".join(sorted(unverified)[:3]))
    return "variant", "; ".join(bits) or "mixed"


def _recurrence(row: dict | None) -> int:
    if not isinstance(row, dict):
        return 1
    r = row.get("recurrence")
    if isinstance(r, dict) and isinstance(r.get("shifts"), int):
        return max(1, r["shifts"])
    return 1


def rung_proximity(seam: dict, charter: dict) -> tuple[float, str]:
    """The strongest charter linkage of a seam. Returns (weight, explanation)."""
    best, why = 0.5, "no linked charter article"
    for nid in seam.get("charter_articles") or seam.get("spine_nodes") or []:
        n = charter.get(nid)
        if not n:
            continue
        st, act = n.get("status"), n.get("active")
        if st == "red" and act:
            w, lab = 4.0, f"{nid} red+active"
        elif st == "red":
            w, lab = 3.0, f"{nid} red"
        elif st == "unwired" and act:
            w, lab = 2.5, f"{nid} unwired+active"
        elif st == "unwired":
            w, lab = 2.0, f"{nid} unwired"
        else:
            w, lab = 1.0, f"{nid} green"
        if w > best:
            best, why = w, lab
    return best, why


def _score(tip: dict | None, seam: dict, charter: dict) -> tuple[float, dict]:
    rec = _recurrence(tip)
    sev_class = (tip or {}).get("severity_class")
    sev = _SEVERITY_WEIGHT.get(sev_class, 1.0)
    prox, why = rung_proximity(seam, charter)
    return round(rec * sev * prox, 3), {
        "recurrence": rec, "severity": sev, "severity_class": sev_class,
        "rung_proximity": prox, "rung_reason": why,
    }


def matrix_digest(data: dict) -> str:
    """Content digest over the MEANING of the matrix — states and scores — excluding timestamps and
    prose. Two runs over an unchanged tree produce the same digest, which is what makes the
    generated-artifact freshness check honest rather than a mtime race."""
    body = [
        {"c": c["concern"], "s": c["seam"], "st": c["state"], "sc": c.get("score")}
        for c in sorted(data.get("cells", []), key=lambda c: (c["concern"], c["seam"]))
    ]
    canon = json.dumps(body, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canon.encode()).hexdigest()[:32]


# ───────────────────────────── generated artifact ─────────────────────────────

_BANNER = ("<!-- GENERATED by .claude/scripts/_lib/seam_matrix.py — DO NOT HAND-EDIT. "
           "Regenerate: python3 .claude/scripts/seam-audit.py --matrix --write -->")


def write_generated(repo_root: Path, data: dict) -> list[str]:
    """Write the JSON read-model + its markdown projection under `.claude/epr-meta/generated/`.

    WHY THAT HOME: a derived read-model belongs beside the two canon homes it derives from
    (`policies.yaml`, `concerns.yaml`) so a reader finds axis, canon and projection together; and
    the directory name makes the never-hand-edit rule STRUCTURAL rather than a comment somebody
    has to notice. Both files carry a banner and the JSON carries the digest, so a hand-edit is
    detectable by the freshness check rather than merely discouraged."""
    root = Path(repo_root)
    (root / GENERATED_DIR_REL).mkdir(parents=True, exist_ok=True)
    jp, mp = root / MATRIX_JSON_REL, root / MATRIX_MD_REL
    payload = dict(data)
    # Serialization slimming — the artifact is git-tracked and re-generated on every substrate
    # move, so it carries facts, not repetition. An UNEXAMINED cell's `reason` is a constant
    # string and its `points` list is empty by definition; its tracks/reach live on the seam row.
    # The full ranking is a pure sort of `cells` on `score`, so only the head is serialized and
    # the derivation is stated rather than duplicated 235 times.
    payload["cells"] = [
        ({"concern": c["concern"], "seam": c["seam"], "plane": c["plane"],
          "state": c["state"], "score": c.get("score")}
         if c["state"] == "unexamined" else c)
        for c in data.get("cells", [])
    ]
    payload["ranked_unexamined"] = data.get("ranked_unexamined", [])[:40]
    payload["ranked_unexamined_note"] = (
        "head only — the full ranking is `cells` filtered to state=unexamined, sorted by "
        "-score then (concern, seam)")
    payload["_generated"] = {
        "by": ".claude/scripts/_lib/seam_matrix.py",
        "regenerate": "python3 .claude/scripts/seam-audit.py --matrix --write",
        "hand_edit": "never — this file is a derived read-model; edit the registries or the catalog",
    }
    jp.write_text(json.dumps(payload, indent=1, sort_keys=False) + "\n")
    mp.write_text(render_markdown(data))
    return [MATRIX_JSON_REL, MATRIX_MD_REL]


def generated_freshness(repo_root: Path, data: dict) -> tuple[str, str]:
    """('fresh'|'stale'|'absent', detail) for the on-disk generated artifact vs live data."""
    p = Path(repo_root) / MATRIX_JSON_REL
    if not p.is_file():
        return "absent", f"{MATRIX_JSON_REL} has never been generated"
    try:
        on_disk = json.loads(p.read_text()).get("digest")
    except Exception as e:  # noqa: BLE001
        return "stale", f"{MATRIX_JSON_REL} unreadable ({e})"
    if on_disk == data.get("digest"):
        return "fresh", on_disk or ""
    return "stale", f"on-disk {on_disk} != live {data.get('digest')}"


# ───────────────────────────── spot-check ─────────────────────────────

def spot_check(repo_root: Path, n: int = 8, *, seed: str = "") -> dict:
    """INDEPENDENT re-derivation of a sample of decision points straight from disk.

    Deliberately shares NO code with the census: it re-loads each registry with a bare
    `yaml.safe_load`, finds the point by name, and tests contract-test containment with a
    line-scan tokenizer instead of the census's regex. A check that calls the thing it checks is a
    mirror — the 2026-07-24 `BlobCid::verifies` incident is exactly that shape, and the test that
    should have caught it computed both sides the same wrong way and stayed green forever.

    The sample is random-but-REPRODUCIBLE: points are sorted, then selected by a hash-derived
    stride, so re-running on an unchanged tree checks the same points (a spot-check you cannot
    reproduce is an anecdote). Pass `seed` to move the window deliberately.

    Returns {checked, mismatches, verdict}. `verdict == "trust"` iff zero mismatches; ANY mismatch
    means the ranking is not trustworthy until explained — a mis-resolving audit does not degrade
    a ranking, it reorders it."""
    repo_root = Path(repo_root)
    catalog, _ = load_catalog(repo_root)
    by_crate, by_point = _routing(catalog)

    # Independent registry read — raw YAML, no schema validation, no census loader.
    universe: list[tuple[str, str, dict]] = []  # (rel, crate, point)
    for path in _sc.discover_registry_paths(repo_root):
        rel = path.relative_to(repo_root).as_posix()
        try:
            raw = yaml.safe_load(path.read_text()) if yaml else None
        except Exception:  # noqa: BLE001
            continue
        if not isinstance(raw, dict):
            continue
        crate = raw.get("crate", "?")
        for pt in raw.get("decisionPoints") or []:
            if isinstance(pt, dict) and pt.get("name"):
                universe.append((rel, crate, pt))
    universe.sort(key=lambda t: (t[0], str(t[2].get("name"))))

    if not universe:
        return {"checked": [], "mismatches": ["no decision points found on disk at all"],
                "verdict": "no-data", "n_universe": 0}

    offset = int(hashlib.sha256((seed or "spot-check").encode()).hexdigest()[:8], 16) % len(universe)
    stride = max(1, len(universe) // max(1, n))
    picks = [universe[(offset + i * stride) % len(universe)] for i in range(min(n, len(universe)))]

    live = matrix_data(repo_root)
    live_cells = {(c["concern"], c["seam"]): c for c in live["cells"]}

    checked: list[dict] = []
    mismatches: list[str] = []
    for rel, crate, pt in picks:
        name = pt["name"]
        seam_id = by_point.get(f"{crate}::{name}") or by_crate.get(crate)
        disk_concerns = sorted({cb.get("id") for cb in pt.get("concernIds") or []
                                if isinstance(cb, dict)})
        # Independent containment test: line scan for a `fn <name>` token, no regex reuse.
        disk_verified = False
        for ct in pt.get("contractTests") or []:
            if not isinstance(ct, dict):
                continue
            f = repo_root / str(ct.get("path", ""))
            tn = str(ct.get("testName", ""))
            if not tn or not f.is_file():
                continue
            try:
                for line in f.read_text(errors="replace").splitlines():
                    toks = re.split(r"[^A-Za-z0-9_]+", line)
                    if "fn" in toks and tn in toks and toks.index("fn") < toks.index(tn):
                        disk_verified = True
                        break
            except OSError:
                continue
            if disk_verified:
                break
        row = {"registry": rel, "crate": crate, "point": name, "seam": seam_id,
               "disk_concerns": disk_concerns, "disk_verified": disk_verified}
        # Compare against what the live matrix concluded for each of this point's cells.
        for cid in disk_concerns:
            if cid not in _sc._CONCERN_ID_SET or not seam_id:
                continue
            cell = live_cells.get((cid, seam_id))
            if cell is None:
                mismatches.append(f"{rel}:{name} cites {cid} at {seam_id} but the live matrix has "
                                  f"no such cell")
                continue
            if cell["state"] == "unexamined":
                mismatches.append(f"{rel}:{name} cites {cid} at {seam_id} on disk, but the live "
                                  f"matrix scores that cell `unexamined` — the resolver is not "
                                  f"seeing a point that is right there")
            names = {p["point"] for p in cell.get("points", [])}
            if name not in names:
                mismatches.append(f"{rel}:{name} is absent from cell {cid}x{seam_id}'s point list")
            for p in cell.get("points", []):
                if p["point"] == name and p.get("verified") != disk_verified:
                    mismatches.append(
                        f"{rel}:{name} contract-test verification disagrees — census says "
                        f"{p.get('verified')}, independent disk scan says {disk_verified}")
        checked.append(row)

    return {"checked": checked, "mismatches": mismatches, "n_universe": len(universe),
            "verdict": "trust" if not mismatches else "DO-NOT-TRUST"}


# ───────────────────────────── rendering ─────────────────────────────

def render_matrix(data: dict, *, as_json: bool = False, top: int = 12) -> str:
    """The compact terminal section surfaced beside the census in `placement-audit --epr-meta`."""
    if as_json:
        return json.dumps(data, indent=1)
    lines: list[str] = []
    lines.append("CONCERN x SEAM MATRIX  (plan P4.3 — generated by the census, never hand-written)")
    lines.append("=" * 72)
    counts = data["counts"]
    lines.append(
        f"{data['n_concerns']} classes x {data['n_seams']} seams = {data['n_cells']} cells  "
        f"[conformant {counts.get('conformant', 0)} · variant {counts.get('variant', 0)} · "
        f"n-a {counts.get('n-a', 0)} · unexamined {counts.get('unexamined', 0)}]  "
        f"({data['n_points_routed']} decision points routed)")

    seam_order = [s["id"] for s in data["seams"]]
    by_id = {c["concern"] + "|" + c["seam"]: c for c in data["cells"]}
    header = "      " + " ".join(f"{sid:>5}" for sid in seam_order)
    lines.append("")
    lines.append(header)
    for cid in _sc.ALL_CONCERN_IDS:
        row = [f"{_STATE_GLYPH.get(by_id[cid + '|' + sid]['state'], '?'):>5}"
               if (cid + "|" + sid) in by_id else "    ?" for sid in seam_order]
        lines.append(f"  {cid:<4}" + " ".join(row))
    lines.append("      legend: ✓ conformant · ~ variant · · unexamined · - n-a")

    ranked = data["ranked_unexamined"][:top]
    lines.append("")
    lines.append(f"TOP {len(ranked)} UNEXAMINED CELLS (rank = recurrence x severity x rung-proximity):")
    for i, c in enumerate(ranked, 1):
        sp = c.get("score_parts", {})
        lines.append(f"  {i:>2}. {c['concern']:<4} x {c['seam']:<6} score {c['score']:<6} "
                      f"[rec {sp.get('recurrence')} x sev {sp.get('severity')} "
                      f"({sp.get('severity_class')}) x prox {sp.get('rung_proximity')} "
                      f"({sp.get('rung_reason')})]")
    if data["errors"]:
        lines.append("")
        lines.append(f"MATRIX ERRORS ({len(data['errors'])}):")
        for e in data["errors"]:
            lines.append(f"  ⛔ {e}")
    return "\n".join(lines)


def render_markdown(data: dict) -> str:
    """The generated markdown projection — the human-readable face of the JSON read-model."""
    L: list[str] = [_BANNER, "", "# Concern x Seam Matrix", ""]
    counts = data["counts"]
    L.append(f"**{data['n_concerns']} concern classes x {data['n_seams']} seams = "
             f"{data['n_cells']} cells** — conformant {counts.get('conformant', 0)} · "
             f"variant {counts.get('variant', 0)} · n-a {counts.get('n-a', 0)} · "
             f"unexamined {counts.get('unexamined', 0)}.")
    L += ["", f"Digest `{data.get('digest')}`. Rows come from the two canon homes at their lineage "
              "tips; columns from `.claude/epr-meta/seam-catalog.yaml` (atlas §3 grouped by §7 "
              "planes + governing/meta + bridges); cells are derived from every "
              "`seam-registry.yaml` by the census. Participation track and reach tier are cell "
              "attributes, not axes.", ""]
    L += ["State vocabulary: `conformant` = every citing point answered **and** cites a contract "
          "test that exists and contains the named fn · `variant` = a documented waiver "
          "(status partial/unbound) **or** an answered point with no verified test · "
          "`unexamined` = nobody has looked · `n-a` = declared inapplicable with justification.",
          ""]

    # Columns grouped by plane
    L += ["## Columns (by §7 plane)", ""]
    for g in data.get("plane_groups", []):
        seams = [s for s in data["seams"] if s.get("plane") == g.get("id")]
        if not seams:
            continue
        L.append(f"### {g.get('title')} ")
        L.append("")
        L.append("| Seam | Atlas § | Name | Tracks | Reach tier | Charter articles |")
        L.append("|---|---|---|---|---|---|")
        for s in seams:
            L.append(f"| `{s['id']}` | {s.get('source_section')} | {s.get('name')} | "
                     f"{', '.join(s.get('tracks') or []) or '—'} | {s.get('reach_tier') or '—'} | "
                     f"{', '.join(s.get('charter_articles') or s.get('spine_nodes') or []) or '—'} |")
        L.append("")

    # The grid
    seam_order = [s["id"] for s in data["seams"]]
    L += ["## The grid", "", "| Class | " + " | ".join(seam_order) + " |",
          "|---" * (len(seam_order) + 1) + "|"]
    by_id = {c["concern"] + "|" + c["seam"]: c for c in data["cells"]}
    tips = data.get("concern_tips", {})
    for cid in _sc.ALL_CONCERN_IDS:
        cells = [_STATE_GLYPH.get(by_id.get(cid + "|" + sid, {}).get("state"), "?")
                 for sid in seam_order]
        L.append(f"| **{cid}** | " + " | ".join(cells) + " |")
    L += ["", "Legend: `✓` conformant · `~` variant · `·` unexamined · `-` n-a", ""]

    L += ["## Class rows at their lineage tips", "",
          "| Class | Tip | Home | Recurrence (shifts) | Severity |", "|---|---|---|---|---|"]
    for cid in _sc.ALL_CONCERN_IDS:
        t = tips.get(cid)
        if not t:
            L.append(f"| {cid} | — | — | — | — |")
            continue
        L.append(f"| {cid} | `{t.get('ref')}` | {t.get('home')} | {t.get('recurrence_shifts')} | "
                 f"{t.get('severity_class') or '—'} |")
    L.append("")

    L += ["## Ranked unexamined cells", "",
          "Rank = recurrence x severity x rung-proximity (severity: silent-corruption 2.0, "
          "loud-fail 1.0; rung-proximity from `genesis/manifests/charter.yaml`: active red 4.0, "
          "red 3.0, active unwired 2.5, unwired 2.0, green 1.0, unlinked 0.5).", "",
          "| # | Class | Seam | Score | Recurrence | Severity | Rung proximity |",
          "|---|---|---|---|---|---|---|"]
    for i, c in enumerate(data["ranked_unexamined"][:40], 1):
        sp = c.get("score_parts", {})
        L.append(f"| {i} | {c['concern']} | `{c['seam']}` | {c['score']} | {sp.get('recurrence')} | "
                 f"{sp.get('severity')} ({sp.get('severity_class')}) | {sp.get('rung_proximity')} "
                 f"({sp.get('rung_reason')}) |")
    L.append("")

    examined = [c for c in data["cells"] if c["state"] in ("conformant", "variant", "n-a")]
    L += ["## Examined cells", "", "| Class | Seam | State | Why | Points |", "|---|---|---|---|---|"]
    for c in sorted(examined, key=lambda c: (c["concern"], c["seam"])):
        pts = ", ".join(f"`{p['crate']}::{p['point']}`" for p in c.get("points", [])[:4]) or "—"
        L.append(f"| {c['concern']} | `{c['seam']}` | {c['state']} | {c['reason']} | {pts} |")
    L.append("")

    if data.get("axis_notes"):
        L += ["## Axis notes", ""]
        for n in data["axis_notes"]:
            L.append(f"- **{n.get('id')}** — {' '.join(str(n.get('detail', '')).split())}")
        L.append("")
    if data.get("errors"):
        L += ["## Errors", ""]
        for e in data["errors"]:
            L.append(f"- ⛔ {e}")
        L.append("")
    return "\n".join(L)
