import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';
import { CID } from 'multiformats/cid';
import { sha256 } from 'multiformats/hashes/sha2';

import {
  CUSTODY_CLAIM_KEY,
  GOVERNANCE_ATOM_KEY,
  SCHEMA_ATOM_KEY,
  SCHEMA_KEY,
  STEWARDSHIP_CLAIM_KEY,
  buildLandingAtomGraph,
  encodeCanonicalEnvelope,
  landingCustodyFacts,
  landingStewardshipFacts,
  type AtomCoupling,
} from '../seed-epr-atom.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '../../../..');
const VECTORS = join(REPO_ROOT, 'elohim/epr/tests/vectors/signed_eprs.json');

const DAG_CBOR_CODEC = 0x71;

function hexToBytes(hex: string): Uint8Array {
  return Uint8Array.from(Buffer.from(hex, 'hex'));
}

function bytesToHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('hex');
}

/** The Rust vectors serialize CIDs as raw byte arrays (serde-codec form). */
function cidFromVector(raw: unknown): CID {
  if (typeof raw === 'string') return CID.parse(raw);
  if (Array.isArray(raw)) return CID.decode(Uint8Array.from(raw as number[]));
  throw new Error(`unparseable CID in vector: ${JSON.stringify(raw)}`);
}

interface VectorEnvelope {
  claims: unknown[];
  coupling: { knowledge?: unknown; value?: unknown; governance?: unknown };
  issuedAt: string;
  kind: string;
  reach: string;
  schemaKey: string;
  schemaRef: unknown;
  supersedes?: unknown;
}

interface Vector {
  label: string;
  envelope: VectorEnvelope;
  payload_hex: string;
  canonical_bytes_hex: string;
  cid: string;
}

// ===========================================================================
// Byte parity with Rust — the load-bearing test
// ===========================================================================

describe('encodeCanonicalEnvelope — parity with Rust Envelope::canonical_bytes', () => {
  // elohim-storage RECOMPUTES the canonical bytes on ingest and rejects the PUT
  // with "cid mismatch" when they differ (epr_service::ingest stage 1). These
  // vectors are generated by the Rust side, so byte equality here is the only
  // offline proof that a seeded atom is ingestible at all.
  const vectors: Vector[] = JSON.parse(readFileSync(VECTORS, 'utf-8'));

  it('has vectors to check', () => {
    expect(vectors.length).toBeGreaterThan(0);
  });

  for (const v of vectors) {
    it(`reproduces the Rust canonical bytes for "${v.label}"`, () => {
      const coupling: AtomCoupling = {};
      if (v.envelope.coupling.knowledge) coupling.knowledge = cidFromVector(v.envelope.coupling.knowledge);
      if (v.envelope.coupling.value) coupling.value = cidFromVector(v.envelope.coupling.value);
      if (v.envelope.coupling.governance)
        coupling.governance = cidFromVector(v.envelope.coupling.governance);

      const encoded = encodeCanonicalEnvelope({
        claims: v.envelope.claims.map(cidFromVector),
        coupling,
        issuedAt: v.envelope.issuedAt,
        kind: v.envelope.kind,
        payload: hexToBytes(v.payload_hex),
        reach: v.envelope.reach,
        schemaKey: v.envelope.schemaKey,
        schemaRef: cidFromVector(v.envelope.schemaRef),
        supersedes: v.envelope.supersedes ? cidFromVector(v.envelope.supersedes) : undefined,
      });

      expect(bytesToHex(encoded)).toBe(v.canonical_bytes_hex);
    });

    it(`derives the Rust CID for "${v.label}"`, async () => {
      const hash = await sha256.digest(hexToBytes(v.canonical_bytes_hex));
      expect(CID.create(1, DAG_CBOR_CODEC, hash).toString()).toBe(v.cid);
    });
  }

  it('omits absent coupling legs rather than encoding null', () => {
    const schemaRef = CID.parse('bafyreieuo65uskmcbvksntsut35co3vupaeh3n46q25poy4qvjgtmexlhq');
    const gov = CID.parse('bafyreig7vejfip5een25dtk7g42kmodksr7zfiwpjayjiphuk4jy7kjfqy');
    const base = {
      claims: [],
      issuedAt: '2026-01-01T00:00:00Z',
      kind: 'Manifest',
      payload: new Uint8Array([1, 2, 3]),
      reach: 'commons',
      schemaKey: 'x',
      schemaRef,
    };
    const govOnly = encodeCanonicalEnvelope({ ...base, coupling: { governance: gov } });
    const withUndefined = encodeCanonicalEnvelope({
      ...base,
      coupling: { governance: gov, knowledge: undefined, value: undefined },
    });
    expect(bytesToHex(withUndefined)).toBe(bytesToHex(govOnly));

    // …and a present knowledge leg genuinely changes the bytes.
    const withKnowledge = encodeCanonicalEnvelope({
      ...base,
      coupling: { governance: gov, knowledge: schemaRef },
    });
    expect(bytesToHex(withKnowledge)).not.toBe(bytesToHex(govOnly));
  });
});

// ===========================================================================
// The landing atom graph
// ===========================================================================

describe('buildLandingAtomGraph', () => {
  it('mints the five-atom family in dependency order', async () => {
    const graph = await buildLandingAtomGraph();
    expect(graph.atoms.map((a) => a.schemaKey)).toEqual([
      SCHEMA_ATOM_KEY,
      GOVERNANCE_ATOM_KEY,
      STEWARDSHIP_CLAIM_KEY,
      CUSTODY_CLAIM_KEY,
      SCHEMA_KEY,
    ]);
  });

  it('is deterministic — re-running mints identical CIDs (content-addressed idempotency)', async () => {
    const a = await buildLandingAtomGraph();
    const b = await buildLandingAtomGraph();
    expect(b.atoms.map((x) => x.cid.toString())).toEqual(a.atoms.map((x) => x.cid.toString()));
  });

  it("every atom's declared CID is the hash of its own canonical bytes", async () => {
    // The storage layer derives the CID itself and rejects a mismatch. Prove
    // the declared envelope.cid is self-consistent before it ever ships.
    const graph = await buildLandingAtomGraph();
    for (const atom of graph.atoms) {
      const env = atom.body.envelope as { cid: string };
      expect(env.cid).toBe(atom.cid.toString());
      expect(atom.cid.code).toBe(DAG_CBOR_CODEC);
    }
  });

  it('points the landing governance leg at the REAL governance atom, not a literal hash', async () => {
    const graph = await buildLandingAtomGraph();
    const governance = graph.atoms.find((a) => a.schemaKey === GOVERNANCE_ATOM_KEY);
    const env = graph.landing.body.envelope as { coupling: Record<string, string | null> };
    expect(governance).toBeDefined();
    expect(env.coupling.governance).toBe(governance!.cid.toString());

    // Regression guard: the old seeder used sha256("elohim-host-governance-v1")
    // as the governance leg — a CID with nothing on the other end.
    const literal = await sha256.digest(new TextEncoder().encode('elohim-host-governance-v1'));
    const sentinel = CID.create(1, DAG_CBOR_CODEC, literal).toString();
    expect(env.coupling.governance).not.toBe(sentinel);
    for (const atom of graph.atoms) {
      const e = atom.body.envelope as {
        coupling: Record<string, string | null>;
        schemaRef: string;
        claims: string[];
      };
      expect(Object.values(e.coupling)).not.toContain(sentinel);
      expect(e.schemaRef).not.toBe(sentinel);
      expect(e.claims).not.toContain(sentinel);
    }
  });

  it('carries real claims — the stewardship and custody atoms it actually minted', async () => {
    const graph = await buildLandingAtomGraph();
    const stewardship = graph.atoms.find((a) => a.schemaKey === STEWARDSHIP_CLAIM_KEY)!;
    const custody = graph.atoms.find((a) => a.schemaKey === CUSTODY_CLAIM_KEY)!;
    const env = graph.landing.body.envelope as { claims: string[] };
    expect(env.claims).toEqual([stewardship.cid.toString(), custody.cid.toString()]);
    expect(env.claims.length).toBeGreaterThan(0);
  });

  it('satisfies every kind-required coupling leg (EprKind::required_coupling)', async () => {
    const graph = await buildLandingAtomGraph();
    for (const atom of graph.atoms) {
      const env = atom.body.envelope as { coupling: Record<string, string | null>; kind: string };
      if (env.kind === 'Manifest') {
        // Manifest requires Governance.
        expect(env.coupling.governance, `${atom.schemaKey} governance leg`).toBeTruthy();
      } else if (env.kind === 'Claim') {
        // Claim requires Knowledge.
        expect(env.coupling.knowledge, `${atom.schemaKey} knowledge leg`).toBeTruthy();
      }
    }
  });

  it('anchors the knowledge legs on the seeded content rows own anchor CIDs', async () => {
    const graph = await buildLandingAtomGraph();
    // deriveContentAnchor emits CIDv1(raw, sha2-256); the raw multicodec is 0x55.
    expect(CID.parse(graph.anchors.landingAnchor).code).toBe(0x55);
    expect(CID.parse(graph.anchors.manifestoAnchor).code).toBe(0x55);
    const env = graph.landing.body.envelope as { coupling: Record<string, string | null> };
    expect(env.coupling.knowledge).toBe(graph.anchors.landingAnchor);
    // No value leg is fabricated — Manifest does not require one.
    expect(env.coupling.value).toBeNull();
  });

  it('carries the governance state document verbatim as the governance payload', async () => {
    const graph = await buildLandingAtomGraph();
    const governance = graph.atoms.find((a) => a.schemaKey === GOVERNANCE_ATOM_KEY)!;
    const payloadHex = (governance.body as { payload: string }).payload;
    const decoded = JSON.parse(Buffer.from(payloadHex, 'hex').toString('utf-8'));
    expect(decoded.entityId).toBe('elohim-host-landing');
    expect(decoded.entityType).toBe('content');
    // Honest scoping: no invented council ratified the landing surface.
    expect(decoded.status).not.toBe('constitutional');
    expect(decoded.reviews).toEqual([]);
  });
});

// ===========================================================================
// The facts the claims assert
// ===========================================================================

describe('landing backing facts', () => {
  it('stewardship comes from the content own authored declaration', () => {
    const facts = landingStewardshipFacts();
    expect(facts.contentId).toBe('elohim-host-landing');
    expect(facts.provenance).toBe('authored');
    expect(facts.stewards).toEqual([
      { presenceId: 'matthew-dowell', ratio: 1, contributionType: 'original_creator' },
    ]);
  });

  it('custody names the ssr-server self-custody pledge seed-commitments seeds', () => {
    const facts = landingCustodyFacts();
    expect(facts).toMatchObject({
      action: 'custody-blob',
      contentId: 'elohim-host-landing',
      artifactRole: 'ssr-server',
      selfCustody: true,
    });
    // The deploy-time blob hash is deliberately absent — binding it would move
    // the claim CID on every SSR bundle rebuild.
    expect(JSON.stringify(facts)).not.toContain('sha256-');
  });
});
