// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjustmentReasoning } from "./AdjustmentReasoning";

/**
 * Output from content_store::get_adjustment_reasoning coordinator function.
 */
export type AdjustmentReasoningOutput = { action_hash: string, entry_hash: string, reasoning: AdjustmentReasoning, };
