// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoveragePolicy } from "./CoveragePolicy";

/**
 * Output from content_store::get_coverage_policy coordinator function.
 */
export type CoveragePolicyOutput = { action_hash: string, entry_hash: string, policy: CoveragePolicy, };
