// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CoveragePolicy wire type. Mirrors the integrity zome's CoveragePolicy entry type.
 */
export type CoveragePolicy = { id: string, member_id: string, coverage_level: string, governed_at: string, covered_risks_json: string, deductible_value: number | null, deductible_unit: string | null, coinsurance: number, out_of_pocket_maximum_value: number | null, out_of_pocket_maximum_unit: string | null, effective_from: string, renewal_terms: string, renewal_due_at: string, constitutional_basis: string, last_premium_event_id: string | null, last_premium_paid_at: string | null, schema_version: number, validation_status: string, modification_event_ids_json: string, metadata_json: string, created_at: string, updated_at: string, };
