// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_flow_goal coordinator function.
 */
export type CreateFlowGoalInput = { id: string, goal_number: string, plan_id: string, steward_id: string, name: string, description: string | null, goal_type: string, target_metric: string, target_value: number, target_unit: string, current_value: number, starting_value: number, deadline: bigint, progress_percent: number, on_track: boolean, estimated_completion_date: bigint | null, linked_resource_ids_json: string, linked_budget_ids_json: string, blocked_by_json: string, status: string, created_at: bigint, started_at: bigint | null, completed_at: bigint | null, goal_event_ids_json: string, schema_version: number, validation_status: string, };
