// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_service_request coordinator function.
 */
export type CreateServiceRequestInput = { id: string, request_number: string, requester_id: string, title: string, description: string, contact_preference: string, contact_value: string, time_zone: string, time_preference: string, interaction_type: string, date_range_start: string, date_range_end: string | null, service_type_ids_json: string, required_skills_json: string, budget_value: number | null, budget_unit: string | null, medium_of_exchange_ids_json: string, status: string, is_public: boolean, links_json: string, schema_version: number, validation_status: string, metadata_json: string, created_at: string, updated_at: string, };
