// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_flow_plan coordinator function.
 *
 * Note: `steward_id` and timestamps are represented as String/i64
 * because this crate cannot depend on HDK types (AgentPubKey, Timestamp).
 * The zome converts at the construction site.
 */
export type CreateFlowPlanInput = { id: string, plan_number: string, steward_id: string, name: string, description: string | null, time_horizon: string, plan_period_start: bigint, plan_period_end: bigint, resource_scopes: Array<string>, included_resource_ids: Array<string>, goals: Array<string>, milestones: Array<string>, budgets: Array<string>, status: string, confidence_score: number, completion_percent: number, created_at: bigint, activated_at: bigint | null, completed_at: bigint | null, last_reviewed_at: bigint | null, next_review_due: bigint, plan_event_ids_json: string, schema_version: number, validation_status: string, metadata_json: string, };
