// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_flow_scenario coordinator function.
 */
export type CreateFlowScenarioInput = { id: string, scenario_number: string, plan_id: string, steward_id: string, name: string, description: string | null, scenario_type: string, changes_json: string, projections_json: string, baseline_scenario_id: string | null, delta_metrics_json: string, status: string, simulated_at: bigint | null, created_at: bigint, updated_at: bigint, scenario_event_ids_json: string, schema_version: number, validation_status: string, };
