// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_adjustment_reasoning coordinator function.
 */
export type CreateAdjustmentReasoningInput = { id: string, claim_id: string, adjuster_id: string, coverage_decision: string, approved_amount_value: number | null, approved_amount_unit: string | null, plain_language_explanation: string, interpretation_notes: string | null, applied_generosity_principle: boolean, constitutional_basis_documents_json: string, policy_citations_json: string, flagged_for_governance: boolean, governance_review_reason: string | null, adjustment_date: string, created_at: string, };
