// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for content_store::create_flow_milestone coordinator function.
 */
export type CreateFlowMilestoneInput = { id: string, milestone_number: string, plan_id: string, name: string, description: string | null, target_date: bigint, actual_date: bigint | null, success_criteria_json: string, all_criteria_met: boolean, depends_on_goals_json: string, depends_on_milestones_json: string, blocks_goals_json: string, status: string, achieved_at: bigint | null, milestone_event_ids_json: string, schema_version: number, validation_status: string, };
