// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlowProjection wire type. Mirrors the integrity zome's FlowProjection entry type.
 */
export type FlowProjection = { id: string, projection_number: string, plan_id: string | null, scenario_id: string | null, steward_id: string, resource_category: string, resource_id: string | null, projection_start: bigint, projection_end: bigint, projection_horizon: string, data_points_json: string, confidence_level: string, confidence_percent: number, projection_method: string, assumptions_json: string, breakpoints_json: string, created_at: bigint, schema_version: number, validation_status: string, };
