// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlowPlan wire type. Mirrors the integrity zome's FlowPlan entry type.
 */
export type FlowPlan = { id: string, plan_number: string, steward_id: string, name: string, description: string | null, time_horizon: string, plan_period_start: bigint, plan_period_end: bigint, resource_scopes: Array<string>, included_resource_ids: Array<string>, goals: Array<string>, milestones: Array<string>, budgets: Array<string>, status: string, confidence_score: number, completion_percent: number, created_at: bigint, activated_at: bigint | null, completed_at: bigint | null, last_reviewed_at: bigint | null, next_review_due: bigint, plan_event_ids_json: string, schema_version: number, validation_status: string, metadata_json: string, };
