// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlowBudget wire type. Mirrors the integrity zome's FlowBudget entry type.
 */
export type FlowBudget = { id: string, budget_number: string, plan_id: string, steward_id: string, name: string, description: string | null, budget_period: string, period_start: bigint, period_end: bigint, categories_json: string, total_planned: number, total_actual: number, variance: number, variance_percent: number, status: string, health_status: string, created_at: bigint, updated_at: bigint, last_reconciled: bigint, budget_event_ids_json: string, schema_version: number, validation_status: string, };
