// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowPlan } from "./FlowPlan";

/**
 * Output from content_store::get_flow_plan coordinator function.
 */
export type FlowPlanOutput = { action_hash: string, plan: FlowPlan, };
