// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query input for flow plans by steward.
 */
export type GetPlansForStewardInput = { steward_id: string, };
