// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query input for service requests by requester.
 */
export type GetServiceRequestInput = { request_id: string, };
