// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query input for service offers by ID.
 */
export type GetServiceOfferInput = { offer_id: string, };
