// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query input for service matches by ID.
 */
export type GetServiceMatchInput = { match_id: string, };
