// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsuranceClaim } from "./InsuranceClaim";

/**
 * Output from content_store::get_insurance_claim coordinator function.
 */
export type InsuranceClaimOutput = { action_hash: string, entry_hash: string, claim: InsuranceClaim, };
