// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * InsuranceClaim wire type. Mirrors the integrity zome's InsuranceClaim entry type.
 */
export type InsuranceClaim = { id: string, claim_number: string, policy_id: string, member_id: string, filed_date: string, filed_by: string, loss_type: string, loss_date: string, description: string, estimated_amount_value: number | null, estimated_amount_unit: string | null, observer_attestation_ids_json: string, member_document_ids_json: string, status: string, status_history_json: string, adjustment_event_ids_json: string, appeal_event_ids_json: string, settlement_event_ids_json: string, schema_version: number, validation_status: string, metadata_json: string, created_at: string, updated_at: string, };
