// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MemberRiskProfile wire type. Mirrors the integrity zome's MemberRiskProfile entry type.
 */
export type MemberRiskProfile = { id: string, member_id: string, risk_type: string, care_maintenance_score: number, community_connectedness_score: number, historical_claims_rate: number, risk_score: number, risk_tier: string, risk_tier_rationale: string, evidence_event_ids_json: string, evidence_breakdown_json: string, risk_trend_direction: string, last_risk_score: number, assessed_at: string, last_assessment_at: string, next_assessment_due: string, assessment_event_ids_json: string, schema_version: number, validation_status: string, metadata_json: string, created_at: string, updated_at: string, };
