// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRiskProfile } from "./MemberRiskProfile";

/**
 * Output from content_store::get_member_risk_profile coordinator function.
 */
export type MemberRiskProfileOutput = { action_hash: string, entry_hash: string, profile: MemberRiskProfile, };
