// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RecurringPattern wire type. Mirrors the integrity zome's RecurringPattern entry type.
 */
export type RecurringPattern = { id: string, pattern_number: string, steward_id: string, label: string, description: string | null, frequency: string, frequency_value: number | null, expected_amount: number, expected_unit: string, variance_expected: number, start_date: bigint, end_date: bigint | null, next_due_date: bigint, resource_category: string, pattern_type: string, auto_generate: boolean, historical_occurrences_json: string, missed_occurrences: number, average_actual_amount: number | null, reliability: number, status: string, created_at: bigint, updated_at: bigint, schema_version: number, validation_status: string, };
