// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ServiceMatch wire type. Mirrors the integrity zome's ServiceMatch entry type.
 */
export type ServiceMatch = { id: string, request_id: string, offer_id: string, match_reason: string, match_quality: number, shared_service_types_json: string, time_compatible: boolean, interaction_compatible: boolean, exchange_compatible: boolean, status: string, proposal_id: string | null, commitment_id: string | null, schema_version: number, validation_status: string, metadata_json: string, created_at: string, updated_at: string, };
