// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceOffer } from "./ServiceOffer";

/**
 * Output from content_store::get_service_offer coordinator function.
 */
export type ServiceOfferOutput = { action_hash: string, entry_hash: string, offer: ServiceOffer, };
