// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceRequest } from "./ServiceRequest";

/**
 * Output from content_store::get_service_request coordinator function.
 */
export type ServiceRequestOutput = { action_hash: string, entry_hash: string, request: ServiceRequest, };
