// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceMatch } from "./ServiceMatch";

/**
 * Output from content_store::get_service_match coordinator function.
 */
export type ServiceMatchOutput = { action_hash: string, entry_hash: string, service_match: ServiceMatch, };
