// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ServiceOffer wire type. Mirrors the integrity zome's ServiceOffer entry type.
 */
export type ServiceOffer = { id: string, offer_number: string, offeror_id: string, title: string, description: string, contact_preference: string, contact_value: string, time_zone: string, time_preference: string, interaction_type: string, hours_per_week: number, date_range_start: string, date_range_end: string | null, service_type_ids_json: string, offered_skills_json: string, rate_value: number, rate_unit: string, rate_per: string, medium_of_exchange_ids_json: string, accepts_alternative_payment: boolean, status: string, is_public: boolean, links_json: string, schema_version: number, validation_status: string, metadata_json: string, created_at: string, updated_at: string, };
