// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentServer } from "./ContentServer";

/**
 * Output from content server operations.
 */
export type ContentServerOutput = { action_hash: string, server: ContentServer, };
