// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DoorwayRegistration entry fields (mirrors integrity zome).
 */
export type DoorwayRegistration = { id: string, url: string, operator_agent: string, operator_human: string | null, capabilities_json: string, reach: string, region: string | null, bandwidth_mbps: number | null, version: string, tier: string, registered_at: string, updated_at: string, };
