// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One address at which a doorway service can be reached.
 */
export type DoorwayEndpoint = { service: string, url: string, priority: number, ttl_secs: number, };
