// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorwayRegistration } from "./DoorwayRegistration";

/**
 * Output from doorway registration operations.
 */
export type DoorwayOutput = { action_hash: string, doorway: DoorwayRegistration, };
