// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentServerOutput } from "./ContentServerOutput";

/**
 * Output from infrastructure::find_publishers.
 */
export type FindPublishersOutput = { content_hash: string, publishers: Array<ContentServerOutput>, };
