// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for infrastructure::find_publishers.
 */
export type FindPublishersInput = { content_hash: string, capability: string | null, prefer_region: string | null, limit: number | null, online_only: boolean | null, };
