// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HealthAttestation entry fields (mirrors integrity zome).
 */
export type HealthAttestation = { attestor_doorway_id: string, operator_agent: string, subject_doorway_id: string, observed_status: string, response_time_ms: number | null, conductor_healthy: boolean | null, timestamp: bigint, };
