// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthAttestation } from "./HealthAttestation";

/**
 * Output from health attestation queries.
 */
export type HealthAttestationOutput = { action_hash: string, entry_hash: string, attestation: HealthAttestation, author: string, };
