// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for infrastructure::record_heartbeat.
 */
export type RecordHeartbeatInput = { doorway_id: string, status: string, uptime_ratio: number, active_connections: number, content_served: bigint, };
