// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for infrastructure::record_daily_summary.
 */
export type RecordSummaryInput = { doorway_id: string, date: string, uptime_ratio: number, total_content_served: bigint, peak_connections: number, heartbeat_count: number, };
