// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for infrastructure::record_health_attestation.
 */
export type RecordHealthAttestationInput = { attestor_doorway_id: string, subject_doorway_id: string, observed_status: string, response_time_ms: number | null, conductor_healthy: boolean | null, };
