// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for infrastructure::register_doorway coordinator function.
 */
export type RegisterDoorwayInput = { id: string, url: string, capabilities_json: string, reach: string, region: string | null, bandwidth_mbps: number | null, version: string, };
