// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorwayEndpoint } from "./DoorwayEndpoint";

/**
 * Input for infrastructure::register_doorway coordinator function.
 */
export type RegisterDoorwayInput = { id: string, url: string, identity_root: string | null, endpoints: Array<DoorwayEndpoint>, capabilities_json: string, reach: string, region: string | null, bandwidth_mbps: number | null, version: string, };
