// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Storage endpoint input (used in RegisterContentServerInput).
 */
export type StorageEndpointInput = { url: string, protocol: string, priority: number | null, };
