// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Storage endpoint entry fields (mirrors integrity zome).
 */
export type StorageEndpoint = { url: string, protocol: string, priority: number, };
