// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for imagodei::create_human coordinator function.
 */
export type CreateHumanInput = { id: string, display_name: string, bio: string | null, affinities: Array<string>, profile_reach: string, location: string | null, };
