// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Human profile fields.
 *
 * Matches the integrity zome's Human entry type field-for-field.
 * The integrity zome wraps this with `#[hdk_entry_helper]` for DHT storage;
 * this version uses plain serde for wire format compatibility.
 */
export type Human = { id: string, display_name: string, bio: string | null, affinities: Array<string>, profile_reach: string, location: string | null, created_at: string, updated_at: string, };
