// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Human } from "./Human";

/**
 * Output from imagodei::create_human coordinator function.
 */
export type HumanOutput = { action_hash: string, human: Human, };
