/**
 * Smoke tests for EPR view types generated by ts-rs from elohim-storage/src/views.rs.
 *
 * These tests verify that:
 * 1. All generated types are importable (no circular dep / missing file errors)
 * 2. Valid instances can be constructed with the expected field shapes
 * 3. camelCase field names are present (snake_case must not leak from Rust)
 *
 * Re-generate types with:
 *   cd elohim/elohim-storage && cargo test export_bindings
 */

import { describe, expect, it } from 'vitest';
import type { EprCouplingView } from '../src/generated/EprCouplingView';
import type { EprSignatureView } from '../src/generated/EprSignatureView';
import type { EprEnvelopeView } from '../src/generated/EprEnvelopeView';
import type { EprView } from '../src/generated/EprView';
import type { EprVerifyErrorView } from '../src/generated/EprVerifyErrorView';
import type { EprVerifyView } from '../src/generated/EprVerifyView';
import type { EprListView } from '../src/generated/EprListView';
import type { EprPublishInput } from '../src/generated/EprPublishInput';
import type { EprProvidersView } from '../src/generated/EprProvidersView';

// ---------------------------------------------------------------------------
// Shared fixtures
// ---------------------------------------------------------------------------

const EXAMPLE_CID = 'bafyreib2rxk3rybk3aobmv5cjuql3bm2twh4vsfdxnu5ybhq5rnaxrfnqe';
const EXAMPLE_CID2 = 'bafyreib2rxk3rybk3aobmv5cjuql3bm2twh4vsfdxnu5ybhq5rnaxrfnqf';
const EXAMPLE_RFC3339 = '2026-04-21T12:00:00Z';
const EXAMPLE_SIG_HEX = 'a'.repeat(128); // 64 bytes as 128 hex chars

const coupling: EprCouplingView = {
  knowledge: EXAMPLE_CID,
  value: EXAMPLE_CID2,
  governance: null,
};

const signature: EprSignatureView = {
  signer: EXAMPLE_CID,
  algorithm: 'ed25519',
  signature: EXAMPLE_SIG_HEX,
};

const envelope: EprEnvelopeView = {
  cid: EXAMPLE_CID,
  kind: 'Content',
  schemaRef: EXAMPLE_CID2,
  schemaKey: 'concept',
  reach: 'commons',
  coupling,
  claims: [EXAMPLE_CID],
  supersedes: null,
  supersededBy: null,
  issuedAt: EXAMPLE_RFC3339,
  proof: signature,
};

// ---------------------------------------------------------------------------
// EprCouplingView
// ---------------------------------------------------------------------------

describe('EprCouplingView', () => {
  it('accepts a coupling with optional legs', () => {
    const c: EprCouplingView = { knowledge: EXAMPLE_CID, value: null, governance: null };
    expect(c.knowledge).toBe(EXAMPLE_CID);
    expect(c.value).toBeNull();
    expect(c.governance).toBeNull();
  });

  it('accepts a fully empty coupling', () => {
    const c: EprCouplingView = { knowledge: null, value: null, governance: null };
    expect(c).toEqual({ knowledge: null, value: null, governance: null });
  });
});

// ---------------------------------------------------------------------------
// EprSignatureView
// ---------------------------------------------------------------------------

describe('EprSignatureView', () => {
  it('carries camelCase fields (no snake_case leak)', () => {
    const s: EprSignatureView = signature;
    // These field accesses would be TypeScript errors if the field names were wrong
    expect(typeof s.signer).toBe('string');
    expect(typeof s.algorithm).toBe('string');
    expect(typeof s.signature).toBe('string');
    // Verify snake_case field does NOT exist at runtime
    expect((s as unknown as Record<string, unknown>)['signer_cid']).toBeUndefined();
    expect((s as unknown as Record<string, unknown>)['proof_algorithm']).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// EprEnvelopeView
// ---------------------------------------------------------------------------

describe('EprEnvelopeView', () => {
  it('constructs a valid envelope view', () => {
    const e: EprEnvelopeView = envelope;
    expect(e.cid).toBe(EXAMPLE_CID);
    expect(e.kind).toBe('Content');
    expect(e.schemaRef).toBe(EXAMPLE_CID2);  // camelCase, not schema_ref
    expect(e.schemaKey).toBe('concept');       // camelCase, not schema_key
    expect(e.reach).toBe('commons');
    expect(e.issuedAt).toBe(EXAMPLE_RFC3339); // camelCase, not issued_at
    expect(e.supersedes).toBeNull();
    expect(e.supersededBy).toBeNull();        // camelCase, not superseded_by
    expect(Array.isArray(e.claims)).toBe(true);
    expect(e.claims[0]).toBe(EXAMPLE_CID);
  });

  it('coupling is nested (not flattened)', () => {
    expect(typeof envelope.coupling).toBe('object');
    expect(envelope.coupling.knowledge).toBe(EXAMPLE_CID);
  });

  it('proof is nested (not flattened)', () => {
    expect(typeof envelope.proof).toBe('object');
    expect(envelope.proof.algorithm).toBe('ed25519');
  });
});

// ---------------------------------------------------------------------------
// EprView
// ---------------------------------------------------------------------------

describe('EprView', () => {
  it('wraps envelope with hex payload', () => {
    const v: EprView = {
      envelope,
      payload: '68656c6c6f', // 'hello' in hex
      canonicalBytes: null,
    };
    expect(v.payload).toBe('68656c6c6f');
    expect(v.canonicalBytes).toBeNull();
  });

  it('accepts optional canonical bytes', () => {
    const v: EprView = {
      envelope,
      payload: 'deadbeef',
      canonicalBytes: 'cafebabe',
    };
    expect(v.canonicalBytes).toBe('cafebabe');
  });
});

// ---------------------------------------------------------------------------
// EprVerifyErrorView
// ---------------------------------------------------------------------------

describe('EprVerifyErrorView', () => {
  it('carries stage and message', () => {
    const e: EprVerifyErrorView = { stage: 'signature', message: 'ed25519 verification failed' };
    expect(e.stage).toBe('signature');
    expect(e.message).toBe('ed25519 verification failed');
  });
});

// ---------------------------------------------------------------------------
// EprVerifyView
// ---------------------------------------------------------------------------

describe('EprVerifyView', () => {
  it('represents a passing verify result', () => {
    const v: EprVerifyView = {
      cid: EXAMPLE_CID,
      verified: true,
      stagesRun: ['canonicalization', 'signature', 'coupling'],
      stagesSkipped: ['payloadSchema'],
      error: null,
    };
    expect(v.verified).toBe(true);
    expect(v.stagesRun).toContain('canonicalization');
    expect(v.stagesSkipped).toContain('payloadSchema');
    expect(v.error).toBeNull();
    // snake_case must not leak
    expect((v as unknown as Record<string, unknown>)['stages_run']).toBeUndefined();
    expect((v as unknown as Record<string, unknown>)['stages_skipped']).toBeUndefined();
  });

  it('represents a failing verify result with error detail', () => {
    const v: EprVerifyView = {
      cid: EXAMPLE_CID,
      verified: false,
      stagesRun: ['canonicalization', 'signature'],
      stagesSkipped: ['payloadSchema'],
      error: { stage: 'signature', message: 'bad sig' },
    };
    expect(v.verified).toBe(false);
    expect(v.error?.stage).toBe('signature');
  });
});

// ---------------------------------------------------------------------------
// EprListView
// ---------------------------------------------------------------------------

describe('EprListView', () => {
  it('carries items array and optional cursor', () => {
    const l: EprListView = {
      items: [envelope],
      nextCursor: null,
    };
    expect(l.items).toHaveLength(1);
    expect(l.nextCursor).toBeNull();
    // camelCase: not next_cursor
    expect((l as unknown as Record<string, unknown>)['next_cursor']).toBeUndefined();
  });

  it('returns a cursor when there are more pages', () => {
    const l: EprListView = {
      items: [envelope],
      nextCursor: EXAMPLE_CID,
    };
    expect(l.nextCursor).toBe(EXAMPLE_CID);
  });
});

// ---------------------------------------------------------------------------
// EprPublishInput
// ---------------------------------------------------------------------------

describe('EprPublishInput', () => {
  it('accepts envelope + hex payload for PUT /api/v1/epr/:cid', () => {
    const input: EprPublishInput = {
      envelope,
      payload: 'deadbeef',
    };
    expect(input.envelope.cid).toBe(EXAMPLE_CID);
    expect(input.payload).toBe('deadbeef');
  });
});

// ---------------------------------------------------------------------------
// EprProvidersView
// ---------------------------------------------------------------------------

describe('EprProvidersView', () => {
  it('Phase 2a: local node returns ["local"]', () => {
    const p: EprProvidersView = {
      cid: EXAMPLE_CID,
      providers: ['local'],
    };
    expect(p.cid).toBe(EXAMPLE_CID);
    expect(p.providers).toEqual(['local']);
  });

  it('Phase 2a: empty providers when atom not held', () => {
    const p: EprProvidersView = {
      cid: EXAMPLE_CID,
      providers: [],
    };
    expect(p.providers).toHaveLength(0);
  });

  it('Phase 2c preview: multiple peer providers', () => {
    const p: EprProvidersView = {
      cid: EXAMPLE_CID,
      providers: ['local', 'peer:12D3KooWABC', 'peer:12D3KooWXYZ'],
    };
    expect(p.providers).toHaveLength(3);
    expect(p.providers[1]).toMatch(/^peer:/);
  });
});
