//! Byte-parity tests for the native cite writer (`epr flow cites`).
//!
//! The oracle these pin is `.claude/scripts/memory-kit/{cite-gen,cite-propagate,cites-migrate}.py`,
//! which this module replaces. Every expectation below was GENERATED by running that oracle against
//! the checked-in fixtures on 2026-09-10 and recorded here, so the pins survive the scripts'
//! deletion — a parity test whose oracle no longer exists must carry the oracle's answer, not a
//! call to it.
//!
//! ## The fixture corpus
//!
//! `tests/fixtures/.cite-writer/tree/` is a 21-file miniature repository: the ten documents whose
//! `cite-gen --seal` fixed-point digests station three recorded, at their recorded pre-seal state
//! (verbatim repository bytes — the corpus is AT its fixed point, so pre-seal and post-seal are the
//! same bytes, which the `pristine` leg asserts), plus the 11 documents their envelopes resolve to,
//! reduced to frontmatter-only stubs. The stubs are safe: `seal` recomputes a fingerprint only when
//! CONVERTING a legacy cite, and none of the ten cites a stubbed target by path, so every recorded
//! digest reproduces exactly — verified against the oracle in the same tree.
//!
//! The directory name starts with a dot ON PURPOSE. Two of the fixtures are `CLAUDE.md` files
//! carrying live `id:` slugs, and the gospel walk (in both the oracle and [`super`]) prunes
//! dot-prefixed directories — so the fixture cannot shadow the real gospel it was copied from in
//! the live slug index.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use sha2::{Digest, Sha256};

/// The ten baseline documents, in the order station three recorded them.
const BASELINE_DOCS: &[&str] = &[
    "genesis/docs/superpowers/specs/2026-05-28-in-flight-memory-coherence-design.md",
    "genesis/docs/superpowers/specs/2026-06-02-semantic-computable-links-design.md",
    "genesis/docs/superpowers/specs/2026-06-05-omnibar-consolidation-epr-native-links-design.md",
    "genesis/docs/superpowers/plans/2026-05-10-iroh-gossip-dual-publish.md",
    "genesis/docs/superpowers/plans/2026-05-11-tiered-quilt-delivery-master.md",
    "genesis/docs/superpowers/plans/2026-05-23-spa-blob-deploy-drift.md",
    ".claude/memory/feedback_codegen_prettier_oscillation.md",
    ".claude/memory/feedback_diesel_migration_timestamp_collision.md",
    ".claude/memory/feedback_lint_autofix_string_scan_poison.md",
    "app/elohim-app/src/app/qahal/CLAUDE.md",
];

/// `(sha256, exit)` after `seal`, per mode, aligned with [`BASELINE_DOCS`].
///
/// `pristine` reproduces the ten digests station three recorded in `task-3-report.md` §2a — the
/// fixed-point identity. The other four legs are the writer proof: the document is PERTURBED in a
/// way `seal` must repair, and the recorded digest is the oracle's answer for that repair. A
/// perturbation whose repair does not restore the original bytes (the memory entries' `id:` sits
/// above `title:`, which `seal` cannot reproduce; the qahal gospel carries an UNQUOTED `path:`
/// envelope, which any rewrite quotes) is pinned at its own recorded digest rather than dropped —
/// the oracle's real behaviour is the contract, not the round trip we might have preferred.
type Row = (&'static str, u8);

const SEAL_PRISTINE: &[Row] = &[
    (
        "8a9a51a757fc4e38d5918defe1041b1e39a2f79ecaa6dfcd273d8b522261da14",
        0,
    ),
    (
        "9ed38bbede03272c7c5fe104050e9601ef50a03b955bdb5d1a55667e0ddaf35a",
        1,
    ),
    (
        "1de47a7e43f0e3242be6b529f5d73ef25067588978e6956dcfee611c85f46d80",
        0,
    ),
    (
        "a4f6fedcd93e948f5a1d64b4246218e004bb2300b4d3326da822c560c0178d85",
        1,
    ),
    (
        "3135cd780875fa2226fd36c5b5dd74baedd7286a53f91b760924def4677cf253",
        1,
    ),
    (
        "eb32e2097191ae2836378b821d7cada09f0a24ee331db0b406e9a4c52e02340f",
        0,
    ),
    (
        "ef8080891f8d2280f79ef87e7b46cc7619fe355b58d1e1b78d1e0b3f3a5dc9f3",
        1,
    ),
    (
        "db09c81ced1d016435053ed17b0b4b5d23d292f3143caf6fd07c5da0e14ac5e5",
        1,
    ),
    (
        "d9d4c5b271b845f606e61e419d1d865a627335a088291b61b158a1efb626c75d",
        0,
    ),
    (
        "363f8ae962bf6f213add0d2c7c97d13e6c41962b3884c973cff9a29a9d9e963a",
        0,
    ),
];

const SEAL_NO_ID: &[Row] = &[
    (
        "8a9a51a757fc4e38d5918defe1041b1e39a2f79ecaa6dfcd273d8b522261da14",
        0,
    ),
    (
        "9ed38bbede03272c7c5fe104050e9601ef50a03b955bdb5d1a55667e0ddaf35a",
        1,
    ),
    (
        "1de47a7e43f0e3242be6b529f5d73ef25067588978e6956dcfee611c85f46d80",
        0,
    ),
    (
        "a4f6fedcd93e948f5a1d64b4246218e004bb2300b4d3326da822c560c0178d85",
        1,
    ),
    (
        "3135cd780875fa2226fd36c5b5dd74baedd7286a53f91b760924def4677cf253",
        1,
    ),
    (
        "eb32e2097191ae2836378b821d7cada09f0a24ee331db0b406e9a4c52e02340f",
        0,
    ),
    (
        "b18a67bc1acf7bd8d94aaf7df006ab414ae4ae2668101d9ca4c2b44022124b33",
        1,
    ),
    (
        "77186ac0e459c9ac060f5dcdb889917d160fd66b6e4230e927a42ea10bf55ad3",
        1,
    ),
    (
        "df6b83ed6ac93dacd618e9081f9c39cd6bc6b1e49919dba1f91e9d209180e738",
        0,
    ),
    (
        "984765fc3d0cc35c36d7f96347b755d108a7b81e541423cc26458a7240af9a26",
        0,
    ),
];

const SEAL_BAD_PATH: &[Row] = &[
    (
        "8a9a51a757fc4e38d5918defe1041b1e39a2f79ecaa6dfcd273d8b522261da14",
        0,
    ),
    (
        "9ed38bbede03272c7c5fe104050e9601ef50a03b955bdb5d1a55667e0ddaf35a",
        1,
    ),
    (
        "1de47a7e43f0e3242be6b529f5d73ef25067588978e6956dcfee611c85f46d80",
        0,
    ),
    (
        "a4f6fedcd93e948f5a1d64b4246218e004bb2300b4d3326da822c560c0178d85",
        1,
    ),
    (
        "3135cd780875fa2226fd36c5b5dd74baedd7286a53f91b760924def4677cf253",
        1,
    ),
    (
        "eb32e2097191ae2836378b821d7cada09f0a24ee331db0b406e9a4c52e02340f",
        0,
    ),
    (
        "ef8080891f8d2280f79ef87e7b46cc7619fe355b58d1e1b78d1e0b3f3a5dc9f3",
        1,
    ),
    (
        "db09c81ced1d016435053ed17b0b4b5d23d292f3143caf6fd07c5da0e14ac5e5",
        1,
    ),
    (
        "d9d4c5b271b845f606e61e419d1d865a627335a088291b61b158a1efb626c75d",
        0,
    ),
    (
        "ccc549d32bc34e802a5e2cc48f22c907fb2f5afb28651eeba267b45ba4e8f066",
        0,
    ),
];

const SEAL_NO_PATH: &[Row] = SEAL_BAD_PATH;

const SEAL_LEGACY: &[Row] = &[
    (
        "8a9a51a757fc4e38d5918defe1041b1e39a2f79ecaa6dfcd273d8b522261da14",
        0,
    ),
    (
        "fb9b09b73be0244098f0e40dc1da53e620795ce54e431aed97a44b83a5356106",
        1,
    ),
    (
        "5b8b03de9207c9e922a3455b4ddd640a21fa6939af62ffa8bf117b71e29e3ca4",
        0,
    ),
    (
        "a4f6fedcd93e948f5a1d64b4246218e004bb2300b4d3326da822c560c0178d85",
        1,
    ),
    (
        "3135cd780875fa2226fd36c5b5dd74baedd7286a53f91b760924def4677cf253",
        1,
    ),
    (
        "eb32e2097191ae2836378b821d7cada09f0a24ee331db0b406e9a4c52e02340f",
        0,
    ),
    (
        "ef8080891f8d2280f79ef87e7b46cc7619fe355b58d1e1b78d1e0b3f3a5dc9f3",
        1,
    ),
    (
        "db09c81ced1d016435053ed17b0b4b5d23d292f3143caf6fd07c5da0e14ac5e5",
        1,
    ),
    (
        "d9d4c5b271b845f606e61e419d1d865a627335a088291b61b158a1efb626c75d",
        0,
    ),
    (
        "a4d466f9e0459b6be04fbd3381e16378aa07577a881611464bf62d1d5e2358a7",
        0,
    ),
];

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    // tests/ -> epr-cli -> eprfs -> elohim -> <repo>
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for _ in 0..3 {
        p = p
            .parent()
            .expect("manifest dir has ancestors")
            .to_path_buf();
    }
    p
}

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/.cite-writer")
}

fn epr_binary() -> PathBuf {
    // The integration-test binary lives beside the `epr` binary cargo just built.
    let mut dir = std::env::current_exe().expect("test binary path");
    dir.pop();
    if dir.ends_with("deps") {
        dir.pop();
    }
    dir.join("epr")
}

fn copy_tree(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).expect("create fixture copy");
    for entry in std::fs::read_dir(src).expect("read fixture dir") {
        let entry = entry.expect("fixture entry");
        let to = dst.join(entry.file_name());
        if entry.path().is_dir() {
            copy_tree(&entry.path(), &to);
        } else {
            std::fs::copy(entry.path(), &to).expect("copy fixture file");
        }
    }
}

/// A private copy of one fixture corpus. Returned as `(tempdir, root)` so the guard outlives use.
fn staged(name: &str) -> (tempfile::TempDir, PathBuf) {
    let dir = tempfile::tempdir().expect("tempdir");
    let root = dir.path().join("r");
    copy_tree(&fixtures().join(name), &root);
    (dir, root)
}

fn sha256_of(path: &Path) -> String {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn run_cites(root: &Path, args: &[&str]) -> (i32, String) {
    let output = Command::new(epr_binary())
        .arg("flow")
        .arg("cites")
        .args(args)
        .arg("--root")
        .arg(root)
        .output()
        .expect("run epr flow cites");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).into_owned()
            + &String::from_utf8_lossy(&output.stderr),
    )
}

/// The four perturbations `seal` must repair. Applied only inside the frontmatter block.
fn perturb(root: &Path, mode: &str) {
    for doc in BASELINE_DOCS {
        let path = root.join(doc);
        let text = std::fs::read_to_string(&path).expect("read baseline doc");
        let lines: Vec<&str> = text.lines().collect();
        if lines.first().map(|l| l.trim()) != Some("---") {
            continue;
        }
        let Some(end) = lines
            .iter()
            .enumerate()
            .skip(1)
            .find(|(_, l)| l.trim() == "---")
            .map(|(i, _)| i)
        else {
            continue;
        };
        let mut out: Vec<String> = Vec::new();
        for (i, line) in lines.iter().enumerate() {
            let mut line = (*line).to_string();
            if i >= 1 && i < end {
                if mode == "no-id" && line.starts_with("id:") {
                    continue;
                }
                let is_item = line.trim_start().starts_with("- ");
                if is_item {
                    if let Some(at) = line.find("| path:") {
                        match mode {
                            "no-path" => {
                                let tail = trailing_quote(&line);
                                line = format!("{}{tail}", line[..at].trim_end());
                            }
                            "bad-path" => {
                                let tail = trailing_quote(&line);
                                line = format!("{}| path: WRONG/PLACE.md{tail}", &line[..at]);
                            }
                            "legacy" => {
                                let locator = line[at + "| path:".len()..]
                                    .trim()
                                    .trim_end_matches('"')
                                    .trim()
                                    .to_string();
                                line = format!("  - {locator}");
                            }
                            _ => {}
                        }
                    }
                }
            }
            out.push(line);
        }
        let mut joined = out.join("\n");
        if text.ends_with('\n') {
            joined.push('\n');
        }
        std::fs::write(&path, joined).expect("write perturbed doc");
    }
}

/// `"` when the envelope line is a quoted YAML scalar, otherwise empty.
fn trailing_quote(line: &str) -> &'static str {
    if line.trim_end().ends_with('"') {
        "\""
    } else {
        ""
    }
}

fn assert_seal_mode(mode: &str, expected: &[Row]) {
    let (_guard, root) = staged("tree");
    if mode != "pristine" {
        perturb(&root, mode);
    }
    for (doc, (want_sha, want_exit)) in BASELINE_DOCS.iter().zip(expected) {
        let (code, _) = run_cites(&root, &["seal", doc]);
        let got = sha256_of(&root.join(doc));
        assert_eq!(
            &got, want_sha,
            "[{mode}] {doc}: sealed bytes differ from the recorded cite-gen --seal output"
        );
        assert_eq!(
            code as u8, *want_exit,
            "[{mode}] {doc}: dissolution-gate exit differs from the oracle"
        );
    }
}

// ---------------------------------------------------------------------------
// (a) seal reproduces the recorded fixed-point digests, byte for byte
// ---------------------------------------------------------------------------

#[test]
fn seal_reproduces_the_recorded_fixed_point_digests() {
    assert_seal_mode("pristine", SEAL_PRISTINE);
}

#[test]
fn seal_reassigns_a_stripped_id_exactly_as_the_oracle_does() {
    assert_seal_mode("no-id", SEAL_NO_ID);
}

#[test]
fn seal_repairs_a_wrong_path_locator_exactly_as_the_oracle_does() {
    assert_seal_mode("bad-path", SEAL_BAD_PATH);
}

#[test]
fn seal_restamps_a_missing_path_locator_exactly_as_the_oracle_does() {
    assert_seal_mode("no-path", SEAL_NO_PATH);
}

#[test]
fn seal_converts_a_downgraded_legacy_cite_exactly_as_the_oracle_does() {
    // The conversion path: description from the target's title, fingerprint recomputed from its
    // canonical body, locator restamped, envelope quoted at mint.
    assert_seal_mode("legacy", SEAL_LEGACY);
}

#[test]
fn seal_is_idempotent_on_an_already_sealed_document() {
    let (_guard, root) = staged("tree");
    for doc in BASELINE_DOCS {
        run_cites(&root, &["seal", doc]);
        let first = sha256_of(&root.join(doc));
        run_cites(&root, &["seal", doc]);
        assert_eq!(
            first,
            sha256_of(&root.join(doc)),
            "{doc}: seal is not idempotent"
        );
    }
}

// ---------------------------------------------------------------------------
// (b) verify agrees with the oracle on live documents
// ---------------------------------------------------------------------------

/// `(doc, exit, problem-count)` for twenty live documents, measured 2026-09-10 with
/// `cite-gen.py --verify` and the native verb agreeing on all twenty.
const LIVE_VERIFY: &[(&str, i32, usize)] = &[
    ("genesis/docs/superpowers/specs/2026-04-16-agentic-developer-loop-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-04-19-gate-challenge-and-indemnification-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-04-21-bootstrap-steward-authority-frame-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-04-22-recovery-protocol-phase-2-revised-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-04-26-storage-phase-11-zome-forwarding-bridge-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-04-30-trust-compute-gradient-brainstorm.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-05-01-atproto-lexicon-projection-doorway-design.md", 0, 0),
    ("genesis/docs/superpowers/specs/2026-05-01-computation-attestation-graduated-rigor-design.md", 0, 0),
    ("genesis/docs/superpowers/plans/2026-04-26-storage-phase-11-zome-forwarding-bridge.md", 0, 0),
    ("genesis/docs/superpowers/plans/2026-05-05-visual-validation-plan.md", 1, 1),
    ("genesis/docs/superpowers/plans/2026-05-07-iroh-parallel-stack.md", 0, 0),
    ("genesis/docs/superpowers/plans/2026-05-08-iroh-bench-expansion-plan.md", 1, 1),
    ("genesis/docs/superpowers/plans/2026-05-08-iroh-phase11-prep.md", 0, 0),
    ("genesis/docs/superpowers/plans/2026-05-10-iroh-delivery-master.md", 0, 0),
    (".claude/memory/MEMORY.md", 0, 0),
    (".claude/memory/feedback-backend-authoritative-frontend-senses.md", 0, 0),
    (".claude/memory/feedback-cleanup-toward-p2p-dataplane-trajectory.md", 0, 0),
    (".claude/memory/feedback-decide-clear-calls-not-over-ask.md", 0, 0),
    ("genesis/docs/architecture/README.md", 0, 0),
    ("genesis/docs/architecture/content-pipeline.md", 0, 0),
];

#[test]
fn verify_agrees_with_the_oracle_on_twenty_live_documents() {
    let root = repo_root();
    let mut checked = 0;
    for (doc, want_exit, want_problems) in LIVE_VERIFY {
        if !root.join(doc).is_file() {
            // A live document that moved is not a parity failure; the pin is stale, and the
            // remaining nineteen still answer the question.
            continue;
        }
        let (code, out) = run_cites(&root, &["verify", doc]);
        assert_eq!(
            code, *want_exit,
            "{doc}: verify exit differs from the recorded oracle answer"
        );
        assert_eq!(
            out.matches("   - ").count(),
            *want_problems,
            "{doc}: verify problem count differs from the recorded oracle answer"
        );
        checked += 1;
    }
    assert!(
        checked >= 15,
        "only {checked} of the twenty live pins were resolvable"
    );
}

// ---------------------------------------------------------------------------
// (c) stamp writes exactly the strings the contract names, and is idempotent
// ---------------------------------------------------------------------------

/// The five `status:` strings the contract fixes. Changing one of these is a corpus-wide diff.
const CONTRACT_HINTS: &[(&str, &str)] = &[
    ("held", "held — target sequestered (see cluster-state.yaml)"),
    ("stale", "stale — target content moved on; re-verify"),
    (
        "remote",
        "remote — resolvable on the substrate, absent locally",
    ),
    ("dead", "dead — target no longer resolves"),
];

#[test]
fn stamp_writes_the_contract_strings_for_every_verdict() {
    let (_guard, root) = staged("stamp");
    let (code, out) = run_cites(&root, &["stamp", "--all", "--write"]);
    assert_eq!(code, 0, "stamp refused: {out}");
    // Counts, matching `cite-propagate.py --apply` on the same fixture (measured 2026-09-10).
    assert!(out.contains("7 docs"), "{out}");
    assert!(out.contains("status stamped: 4"), "{out}");
    assert!(out.contains("cleared (recovered/healthy): 1"), "{out}");
    assert!(out.contains("path: stamped/refreshed: 1"), "{out}");
    assert!(out.contains("docs touched: 2"), "{out}");

    let citer = std::fs::read_to_string(root.join("genesis/docs/superpowers/specs/citer.md"))
        .expect("read citer");
    for (verdict, hint) in CONTRACT_HINTS {
        assert!(
            citer.contains(&format!("status: {hint}")),
            "the {verdict} edge did not carry the contract string `{hint}`:\n{citer}"
        );
    }
    // `ok` REMOVES the field rather than writing one.
    let ok_line = citer
        .lines()
        .find(|l| l.contains("ok-target |"))
        .expect("ok edge present");
    assert!(
        !ok_line.contains("status:"),
        "an ok edge must carry no status: {ok_line}"
    );
    // A dead slug keeps its last known path as a forensic breadcrumb, never blanked.
    let dead_line = citer
        .lines()
        .find(|l| l.contains("gone-target |"))
        .expect("dead edge present");
    assert!(
        dead_line.contains("path: genesis/docs/superpowers/specs/gone-target.md"),
        "a dead slug must keep its breadcrumb path: {dead_line}"
    );
    // A legacy path cite is skipped entirely — its ref IS the path, it carries no status.
    assert!(
        citer.contains("  - elohim/elohim-storage/src/db/mod.rs"),
        "the legacy path cite was rewritten:\n{citer}"
    );
    // A recovered edge clears its stale hint and has its wrong locator refreshed.
    let second =
        std::fs::read_to_string(root.join("genesis/docs/superpowers/specs/second-citer.md"))
            .expect("read second citer");
    assert!(
        !second.contains("status:"),
        "the recovered edge kept a status hint:\n{second}"
    );
    assert!(
        !second.contains("WRONG/PLACE.md"),
        "the locator was not refreshed:\n{second}"
    );
}

#[test]
fn stamp_is_idempotent_and_byte_stable() {
    let (_guard, root) = staged("stamp");
    run_cites(&root, &["stamp", "--all", "--write"]);
    let before: BTreeMap<String, String> = ["citer.md", "second-citer.md"]
        .iter()
        .map(|f| {
            let p = root.join("genesis/docs/superpowers/specs").join(f);
            ((*f).to_string(), sha256_of(&p))
        })
        .collect();
    let (code, out) = run_cites(&root, &["stamp", "--all", "--write"]);
    assert_eq!(code, 0, "{out}");
    assert!(
        out.contains("status stamped: 0"),
        "second pass stamped again:\n{out}"
    );
    assert!(out.contains("cleared (recovered/healthy): 0"), "{out}");
    assert!(out.contains("path: stamped/refreshed: 0"), "{out}");
    assert!(out.contains("docs touched: 0"), "{out}");
    for (name, digest) in &before {
        let p = root.join("genesis/docs/superpowers/specs").join(name);
        assert_eq!(&sha256_of(&p), digest, "{name}: second stamp changed bytes");
    }
}

#[test]
fn stamp_defaults_to_a_dry_run_and_touches_nothing() {
    let (_guard, root) = staged("stamp");
    let citer = root.join("genesis/docs/superpowers/specs/citer.md");
    let before = sha256_of(&citer);
    let (code, out) = run_cites(&root, &["stamp", "--all"]);
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("[DRY-RUN]"), "{out}");
    assert!(out.contains("status stamped: 4"), "{out}");
    assert_eq!(sha256_of(&citer), before, "a dry run wrote to disk");
}

#[test]
fn stamp_refuses_a_run_whose_slug_index_is_ambiguous() {
    // Refusal 5 — two documents declaring the same `id:` make every verdict on that slug
    // untrustworthy, so the WHOLE run is refused by name. The oracle silently resolved the
    // collision by walk order; this is a deliberate divergence toward refusing rather than guessing.
    let (_guard, root) = staged("dup-id");
    let (code, out) = run_cites(&root, &["stamp", "--all", "--write"]);
    assert_ne!(code, 0, "an ambiguous slug index must refuse: {out}");
    assert!(out.contains("duplicate id:"), "{out}");
    assert!(
        out.contains("twin"),
        "the refusal must name the colliding slug: {out}"
    );
    assert!(
        out.contains("one.md") && out.contains("two.md"),
        "the refusal must name both: {out}"
    );
}

#[test]
fn stamp_refuses_a_named_document_with_no_frontmatter() {
    // Refusal 1 — never synthesize a frontmatter block.
    let (_guard, root) = staged("stamp");
    let (code, out) = run_cites(
        &root,
        &[
            "stamp",
            "genesis/docs/superpowers/specs/no-frontmatter.md",
            "--write",
        ],
    );
    assert_ne!(code, 0, "{out}");
    assert!(out.contains("no frontmatter"), "{out}");
}

#[test]
fn stamp_skips_a_document_with_no_cites_key_silently() {
    // Refusal 2 — most documents have no `cites:` and that is not an error.
    let (_guard, root) = staged("stamp");
    let (code, out) = run_cites(
        &root,
        &[
            "stamp",
            "genesis/docs/superpowers/specs/no-cites.md",
            "--write",
        ],
    );
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("docs touched: 0"), "{out}");
    assert!(!out.contains("refused"), "{out}");
}

// ---------------------------------------------------------------------------
// (d) migrate reports the oracle's counts and drains to zero
// ---------------------------------------------------------------------------

#[test]
fn migrate_reports_the_oracle_counts_on_the_fixture_corpus() {
    // `cites-migrate.py` on this fixture, measured 2026-09-10:
    //   5 docs · pass 1: 3 assigned (2 already had one) · pass 2: 2 converted across 1 docs
    let (_guard, root) = staged("migrate");
    let (code, out) = run_cites(&root, &["migrate"]);
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("[DRY-RUN]: 5 docs"), "{out}");
    assert!(
        out.contains("pass 1: 3 id: slugs assigned (2 already had one)"),
        "{out}"
    );
    assert!(
        out.contains("pass 2: 2 cites converted to envelopes across 1 docs"),
        "{out}"
    );
}

#[test]
fn migrate_dry_run_writes_nothing() {
    let (_guard, root) = staged("migrate");
    let plan = root.join("genesis/docs/superpowers/plans/plan-one.md");
    let before = sha256_of(&plan);
    run_cites(&root, &["migrate"]);
    assert_eq!(sha256_of(&plan), before, "a migrate dry run wrote to disk");
}

#[test]
fn migrate_apply_drains_the_corpus_to_zero_pending() {
    let (_guard, root) = staged("migrate");
    let (code, out) = run_cites(&root, &["migrate", "--apply"]);
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("[APPLIED]"), "{out}");
    let (code, out) = run_cites(&root, &["migrate"]);
    assert_eq!(code, 0, "{out}");
    assert!(
        out.contains("pass 1: 0 id: slugs assigned (5 already had one)"),
        "{out}"
    );
    assert!(
        out.contains("pass 2: 0 cites converted to envelopes across 0 docs"),
        "{out}"
    );

    // The minted envelope is byte-identical to the oracle's, INCLUDING its unquoted form:
    // `cites-migrate.py` does not YAML-quote what it mints, while `cite-gen --into` does, and the
    // corpus carries both. Reproducing that divergence is what makes a migrate pass comparable.
    let plan = std::fs::read_to_string(root.join("genesis/docs/superpowers/plans/plan-one.md"))
        .expect("read migrated plan");
    assert!(
        plan.contains(
            "  - target-a | Target A | sha256:2530afdb1630ffb4 | path: genesis/docs/superpowers/specs/target-a.md"
        ),
        "{plan}"
    );
    assert!(
        plan.contains(
            "  - target-b | Target B | sha256:b9f22c8ad5f2f2a5 | path: genesis/docs/superpowers/specs/target-b.md"
        ),
        "a title's first dash-segment is the migration-default description:\n{plan}"
    );
    assert!(
        plan.contains("  - elohim/elohim-storage/src/db/mod.rs"),
        "a code path cite must stay legacy:\n{plan}"
    );
}

#[test]
fn live_corpus_migrate_reports_zero_pending() {
    // The dissolution gate the plan names: the four Python cite scripts delete only after a corpus
    // dry run reports zero. Measured against `cites-migrate.py` before the drain (899 docs · 226
    // ids · 10 conversions across 7 docs — identical on both implementations), then drained.
    let root = repo_root();
    if !root.join("genesis/docs").is_dir() {
        return; // not a live checkout; the fixture legs carry the parity claim
    }
    let (code, out) = run_cites(&root, &["migrate"]);
    assert_eq!(code, 0, "{out}");
    assert!(
        out.contains("pass 1: 0 id: slugs assigned"),
        "the corpus has re-accumulated un-slugged documents; run `epr flow cites migrate --apply`:\n{out}"
    );
    assert!(
        out.contains("pass 2: 0 cites converted"),
        "the corpus has re-accumulated legacy doc cites; run `epr flow cites migrate --apply`:\n{out}"
    );
}

// ---------------------------------------------------------------------------
// The reader divergences the corpus forced
// ---------------------------------------------------------------------------

#[test]
fn an_empty_inline_cites_sequence_declares_no_cites() {
    // `cites: []` is nine live documents. The oracle stores it as the scalar `"[]"`, iterates the
    // string, and mints two phantom edges named `[` and `]` — 18 of the 22 `dead` verdicts its
    // 2026-09-10 corpus pass reported. Refused: a bracket is not a citation.
    let dir = tempfile::tempdir().expect("tempdir");
    let root = dir.path();
    let doc = root.join("genesis/docs/superpowers/specs/empty.md");
    std::fs::create_dir_all(doc.parent().unwrap()).unwrap();
    std::fs::write(
        &doc,
        "---\ntitle: Empty\nid: empty\ncites: []\n---\n\nBody.\n",
    )
    .unwrap();
    let (code, out) = run_cites(root, &["stamp", "--all", "--write"]);
    assert_eq!(code, 0, "{out}");
    assert!(
        out.contains("status stamped: 0"),
        "phantom bracket edges were stamped:\n{out}"
    );
    assert_eq!(
        std::fs::read_to_string(&doc).unwrap(),
        "---\ntitle: Empty\nid: empty\ncites: []\n---\n\nBody.\n",
        "the document was rewritten"
    );
}

#[test]
fn describe_sets_authored_hints_without_disturbing_the_envelope() {
    let (_guard, root) = staged("stamp");
    let citer = "genesis/docs/superpowers/specs/citer.md";
    let (code, out) = run_cites(
        &root,
        &[
            "describe",
            citer,
            "--slug",
            "ok-target",
            "--desc",
            "an authored relationship hint",
        ],
    );
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("1 description(s) set"), "{out}");
    let text = std::fs::read_to_string(root.join(citer)).unwrap();
    let line = text.lines().find(|l| l.contains("ok-target |")).unwrap();
    assert!(line.contains("an authored relationship hint"), "{line}");
    assert!(
        line.contains("sha256:"),
        "the fingerprint was disturbed: {line}"
    );
    assert!(
        line.contains("path: genesis/docs/superpowers/specs/ok-target.md"),
        "{line}"
    );
    // Idempotent: a second identical run sets nothing.
    let (_, out) = run_cites(
        &root,
        &[
            "describe",
            citer,
            "--slug",
            "ok-target",
            "--desc",
            "an authored relationship hint",
        ],
    );
    assert!(out.contains("0 description(s) set"), "{out}");
}

#[test]
fn describe_accepts_the_oracle_positional_json_shape() {
    let (_guard, root) = staged("stamp");
    let citer = "genesis/docs/superpowers/specs/citer.md";
    let (code, out) = run_cites(
        &root,
        &[
            "describe",
            citer,
            "{\"stale-target\": \"a hint via the json shape\"}",
        ],
    );
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("1 description(s) set"), "{out}");
}

#[test]
fn assign_id_is_idempotent_and_inserts_after_the_title() {
    let dir = tempfile::tempdir().expect("tempdir");
    let root = dir.path();
    let doc = root.join("genesis/docs/superpowers/specs/2026-01-01-fresh-design.md");
    std::fs::create_dir_all(doc.parent().unwrap()).unwrap();
    std::fs::write(
        &doc,
        "---\nstatus: proposed\ntitle: Fresh\nclass: devflow\n---\n\nBody.\n",
    )
    .unwrap();
    let (code, out) = run_cites(
        root,
        &[
            "assign-id",
            "genesis/docs/superpowers/specs/2026-01-01-fresh-design.md",
        ],
    );
    assert_eq!(code, 0, "{out}");
    assert_eq!(
        std::fs::read_to_string(&doc).unwrap(),
        "---\nstatus: proposed\ntitle: Fresh\nid: fresh-design\nclass: devflow\n---\n\nBody.\n"
    );
    let before = sha256_of(&doc);
    run_cites(
        root,
        &[
            "assign-id",
            "genesis/docs/superpowers/specs/2026-01-01-fresh-design.md",
        ],
    );
    assert_eq!(sha256_of(&doc), before, "assign-id is not idempotent");
}
