// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for adding a step to a path.
 */
export type AddPathStepInput = { path_id: string, chapter_id: string | null, module_id: string | null, section_id: string | null, order_index: number, step_type: string, resource_id: string, step_title: string | null, step_narrative: string | null, is_optional: boolean, learning_objectives: Array<string> | null, reflection_prompts: Array<string> | null, practice_exercises: Array<string> | null, estimated_minutes: number | null, completion_criteria: string | null, attestation_required: string | null, attestation_granted: string | null, mastery_threshold: number | null, metadata_json: string | null, };
