// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attestation record fields.
 */
export type AttestationRecord = { agent_id: string, category: string, attestation_type: string, display_name: string, description: string, icon_url: string | null, tier: string | null, earned_via_json: string, expires_at: string | null, };
