// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestationRecord } from "./AttestationRecord";

/**
 * Output from attestation operations.
 */
export type AttestationOutput = { action_hash: string, attestation: AttestationRecord, };
