// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentOutput } from "./ContentOutput";

/**
 * Output for batch content retrieval.
 */
export type BatchGetContentOutput = { found: Array<ContentOutput>, not_found: Array<string>, };
