// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddPathStepInput } from "./AddPathStepInput";

/**
 * Input for batch adding steps to a path.
 */
export type BatchAddPathStepsInput = { steps: Array<AddPathStepInput>, };
