// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for batch content retrieval by IDs.
 */
export type BatchGetContentInput = { ids: Array<string>, };
