// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output from bulk content creation.
 */
export type BulkCreateContentOutput = { import_id: string, created_count: number, action_hashes: Array<string>, errors: Array<string>, };
