// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateContentInput } from "./CreateContentInput";

/**
 * Input for bulk content creation.
 */
export type BulkCreateContentInput = { import_id: string, contents: Array<CreateContentInput>, };
