// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chapter wire type. Mirrors the integrity zome's PathChapter entry.
 */
export type Chapter = { id: string, path_id: string, order_index: number, title: string, description: string | null, learning_objectives_json: string, estimated_minutes: number | null, is_optional: boolean, attestation_granted: string | null, mastery_threshold: number | null, metadata_json: string, created_at: string, updated_at: string, };
