// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";

/**
 * Output for a chapter.
 */
export type ChapterOutput = { action_hash: string, chapter: Chapter, };
