// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for checking attestation access.
 */
export type CheckAttestationInput = { path_id: string, required_attestation: string, };
