// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for batch ID existence check.
 */
export type CheckIdsExistInput = { ids: Array<string>, };
