// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output for batch ID existence check.
 */
export type CheckIdsExistOutput = { existing_ids: Array<string>, };
