// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for completing a step.
 */
export type CompleteStepInput = { path_id: string, step_index: number, content_id: string | null, affinity_score: number | null, notes: string | null, reflection_responses: Array<string> | null, };
