// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentGraphNode } from "./ContentGraphNode";
import type { ContentOutput } from "./ContentOutput";

/**
 * Content graph output.
 */
export type ContentGraph = { root: ContentOutput | null, related: Array<ContentGraphNode>, total_nodes: number, };
