// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ContentAttestation wire type. Trust claims about content.
 */
export type ContentAttestation = { id: string, content_id: string, attestation_type: string, reach_granted: string, granted_by_json: string, granted_at: string, expires_at: string | null, status: string, revocation_json: string | null, evidence_json: string | null, scope_json: string | null, metadata_json: string, created_at: string, updated_at: string, schema_version: number, validation_status: string, };
