// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentOutput } from "./ContentOutput";

/**
 * Content graph node for tree traversal.
 */
export type ContentGraphNode = { content: ContentOutput, relationship_type: string, confidence: number, children: Array<ContentGraphNode>, };
