// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content statistics output.
 */
export type ContentStats = { total_count: number, by_type: { [key in string]?: number }, };
