// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content wire type. Mirrors the integrity zome's Content entry type.
 */
export type Content = { id: string, content_type: string, title: string, description: string, summary: string | null, content: string, content_format: string, tags: Array<string>, source_path: string | null, related_node_ids: Array<string>, author_id: string | null, reach: string, trust_score: number, estimated_minutes: number | null, thumbnail_url: string | null, metadata_json: string, created_at: string, updated_at: string, schema_version: number, validation_status: string, blob_cid: string | null, content_size_bytes: bigint | null, content_hash: string | null, };
