// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./Content";

/**
 * Output from content_store::get_content coordinator function.
 */
export type ContentOutput = { action_hash: string, entry_hash: string, content: Content, };
