// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a knowledge map.
 */
export type CreateKnowledgeMapInput = { id: string | null, map_type: string, owner_id: string, title: string, description: string | null, subject_type: string, subject_id: string, subject_name: string, visibility: string, shared_with_json: string, nodes_json: string, path_ids_json: string, overall_affinity: number, content_graph_id: string | null, mastery_levels_json: string, goals_json: string, metadata_json: string, };
