// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a path extension.
 */
export type CreatePathExtensionInput = { id: string | null, base_path_id: string, base_path_version: string, extended_by: string, title: string, description: string | null, insertions_json: string, annotations_json: string, reorderings_json: string, exclusions_json: string, visibility: string, shared_with_json: string, forked_from: string | null, forks_json: string, upstream_proposal_json: string | null, stats_json: string, };
