// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a content relationship.
 */
export type CreateRelationshipInput = { source_id: string, target_id: string, relationship_type: string, confidence: number, inference_source: string, metadata_json: string | null, };
