// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a learning path.
 */
export type CreatePathInput = { id: string, version: string, title: string, description: string, purpose: string | null, difficulty: string, estimated_duration: string | null, visibility: string, path_type: string, tags: Array<string>, metadata_json: string | null, };
