// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a chapter.
 */
export type CreateChapterInput = { path_id: string, order_index: number, title: string, description: string | null, learning_objectives: Array<string>, estimated_minutes: number | null, is_optional: boolean, attestation_granted: string | null, mastery_threshold: number | null, metadata_json: string | null, };
