// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying relationships by content ID.
 */
export type GetRelationshipsInput = { content_id: string, direction: string, };
