// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for granting attestation.
 */
export type GrantAttestationInput = { path_id: string, attestation_id: string, reason: string, source_type: string, source_id: string, };
