// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output for import status.
 */
export type ImportStatusOutput = { id: string, batch_type: string, blob_hash: string, total_items: number, status: string, processed_count: number, error_count: number, errors_json: string, created_at: string, started_at: string | null, completed_at: string | null, author_id: string | null, schema_version: number, };
