// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for processing a chunk of import data.
 */
export type ImportChunkInput = { batch_id: string, chunk_index: number, is_final: boolean, items_json: string, };
