// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeMap } from "./KnowledgeMap";

/**
 * Output for knowledge map operations.
 */
export type KnowledgeMapOutput = { action_hash: string, knowledge_map: KnowledgeMap, };
