// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LearningPath wire type. Mirrors the integrity zome's LearningPath entry.
 */
export type LearningPath = { id: string, version: string, title: string, description: string, purpose: string | null, created_by: string, difficulty: string, estimated_duration: string | null, visibility: string, path_type: string, tags: Array<string>, metadata_json: string, created_at: string, updated_at: string, schema_version: number, validation_status: string, };
