// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for paginated content query by tag.
 */
export type PaginatedByTagInput = { tag: string, page_size: number, offset: number, };
