// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentOutput } from "./ContentOutput";

/**
 * Output for paginated content query.
 */
export type PaginatedContentOutput = { items: Array<ContentOutput>, total_count: number, offset: number, has_more: boolean, };
