// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningPath } from "./LearningPath";

/**
 * Lightweight path overview (no step content, just counts).
 */
export type PathOverviewOutput = { action_hash: string, path: LearningPath, step_count: number, };
