// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathExtension } from "./PathExtension";

/**
 * Output for path extension operations.
 */
export type PathExtensionOutput = { action_hash: string, path_extension: PathExtension, };
