// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathStep } from "./PathStep";

/**
 * Output for a path step.
 */
export type PathStepOutput = { action_hash: string, step: PathStep, };
