// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningPath } from "./LearningPath";
import type { PathStepOutput } from "./PathStepOutput";

/**
 * Output for learning path with steps.
 */
export type PathWithStepsOutput = { action_hash: string, path: LearningPath, steps: Array<PathStepOutput>, };
