// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PathStep wire type. Mirrors the integrity zome's PathStep entry.
 */
export type PathStep = { id: string, path_id: string, chapter_id: string | null, module_id: string | null, section_id: string | null, order_index: number, step_type: string, resource_id: string, step_title: string | null, step_narrative: string | null, is_optional: boolean, learning_objectives_json: string, reflection_prompts_json: string, practice_exercises_json: string, estimated_minutes: number | null, completion_criteria: string | null, attestation_required: string | null, attestation_granted: string | null, mastery_threshold: number | null, metadata_json: string, created_at: string, updated_at: string, schema_version: number, validation_status: string, };
