// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step input embedded in PathImportInput.
 */
export type PathImportStepInput = { step_type: string, resource_id: string, order_index: number, step_title: string | null, step_narrative: string | null, is_optional: boolean, module_id: string | null, chapter_id: string | null, section_id: string | null, };
