// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying progress.
 */
export type QueryProgressInput = { status: string | null, path_id: string | null, limit: number | null, };
