// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying content by ID.
 */
export type QueryByIdInput = { id: string, };
