// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying knowledge maps.
 */
export type QueryKnowledgeMapInput = { owner_id: string | null, map_type: string | null, limit: number | null, };
