// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying related content with traversal.
 */
export type QueryRelatedContentInput = { content_id: string, relationship_types: Array<string> | null, depth: number | null, };
