// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying path extensions.
 */
export type QueryPathExtensionInput = { base_path_id: string | null, extended_by: string | null, limit: number | null, };
