// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for querying content by type.
 */
export type QueryByTypeInput = { content_type: string, limit: number | null, };
