// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for queuing an import batch.
 */
export type QueueImportInput = { id: string, batch_type: string, blob_hash: string, total_items: number, schema_version: number, };
