// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relationship wire type. Mirrors the integrity zome's Relationship entry.
 */
export type Relationship = { id: string, source_id: string, target_id: string, relationship_type: string, confidence: number, inference_source: string, metadata_json: string | null, created_at: string, };
