// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for starting path progress.
 */
export type StartPathProgressInput = { path_id: string, };
