// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updating a path.
 */
export type UpdatePathInput = { path_id: string, title: string | null, description: string | null, purpose: string | null, difficulty: string | null, estimated_duration: string | null, visibility: string | null, tags: Array<string> | null, };
