// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updating a chapter.
 */
export type UpdateChapterInput = { chapter_id: string, title: string | null, description: string | null, learning_objectives: Array<string> | null, estimated_minutes: number | null, is_optional: boolean | null, order_index: number | null, attestation_granted: string | null, mastery_threshold: number | null, };
